### ISSUE TITLE
not creating new tickets

### ISSUE THREAD

**Issue by linainvers** [ladybirdweb/faveo-helpdesk#10]
ErrorException thrown with message "Trying to get property of non-object"

Stacktrace:
#39 ErrorException in /home/linainvers/www/code/app/Http/Controllers/Client/helpdesk/FormController.php:157
#38 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /home/linainvers/www/code/app/Http/Controllers/Client/helpdesk/FormController.php:157
#37 App\Http\Controllers\Client\helpdesk\FormController:postedForm in <#unknown>:0
#36 call_user_func_array in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:246
#35 Illuminate\Routing\Controller:callAction in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:162
#34 Illuminate\Routing\ControllerDispatcher:call in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:107
#33 Illuminate\Routing\ControllerDispatcher:Illuminate\Routing\{closure} in <#unknown>:0
#32 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
#31 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#30 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101
#29 Illuminate\Pipeline\Pipeline:then in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:108
#28 Illuminate\Routing\ControllerDispatcher:callWithinStack in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:67
#27 Illuminate\Routing\ControllerDispatcher:dispatch in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php:204
#26 Illuminate\Routing\Route:runWithCustomDispatcher in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php:134
#25 Illuminate\Routing\Route:run in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php:701
#24 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#23 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#21 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101
#20 Illuminate\Pipeline\Pipeline:then in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php:703
#19 Illuminate\Routing\Router:runRouteWithinStack in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php:670
#18 Illuminate\Routing\Router:dispatchToRoute in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php:628
#17 Illuminate\Routing\Router:dispatch in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:214
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in <#unknown>:0
#15 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:55
#13 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
#12 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:61
#11 Illuminate\Session\Middleware\StartSession:handle in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:36
#9 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:40
#7 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
#6 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:42
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#3 call_user_func in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101
#2 Illuminate\Pipeline\Pipeline:then in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:115
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/linainvers/www/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:84
#0 Illuminate\Foundation\Http\Kernel:handle in /home/linainvers/www/index.php:53
![error](https://cloud.githubusercontent.com/assets/170334/11930476/e45cdf88-a80d-11e5-82ef-c8083c48d582.jpg)

**Comment by linainvers** [comment]
I tried turn off debug, the result is the same, but without stack.

**Comment by sujit223** [comment]
Please go through the settings page and input all the settings in the settings page then this error might fix. We will come up with a version in nearest future in which users has to setup least possible settings. Most of the settings will be running out of the box. If you still face the issue please let us know.
Thank You

**Comment by linainvers** [comment]
thx for help

**Comment by linainvers** [comment]
thx for help, сan I prevent unregistered users to leave the tickets?

**Comment by sujit223** [comment]
This feature currently does not exist but whenever a user opens a ticket they gets registered in the system. 
Thank You.
