### ISSUE TITLE
Open a notification which user does not have right to open

### ISSUE THREAD

**Issue by thanhpt** [ladybirdweb/faveo-helpdesk#100]
I got this error when click on notification icon to open a ticket which is not visible to my account.

Log : 

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/faveo/resources/views/themes/default1/agent/helpdesk/ticket/timeline.blade.php)' in /var/www/faveo/storage/framework/views/e6f99524c4f267bd4e02e1244ad6f34781a9262b.php:12

**Comment by sujit223** [comment]
Thanks for notifying us. This will be fixed by our next release.

**Comment by thanhpt** [comment]
Please tell me any hot fix or hint to fix this ?

**Comment by sujit223** [comment]
Clear the user_notification and notifications table in database.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC. Agents will only see notification related to their department and admin will see all other notification.
