### ISSUE TITLE
Plugin.js is transfer as css 

### ISSUE THREAD

**Issue by thanhpt** [ladybirdweb/faveo-helpdesk#102]
Resource interpreted as Stylesheet but transferred with MIME type application/javascript: "http://domain.name/lb-faveo/plugins/filebrowser/plugin.js".

**Comment by sujit223** [comment]
Sorry for this we will make a fix to it in the next release

**Comment by mathieu-aubin** [comment]
quick, easy temporary fix to get you up and running...

On nginx webserver:
```
location = /lb-faveo/plugins/filebrowser/plugin.js {
    add_header Content-Type "application/javascript";
}
```

in Apache, htaccess file...
```
AddType application/javascript .js
AddType text/css .css
```
A little hack i'd use to temporarily get by...

**Comment by mathieu-aubin** [comment]
After having a look at the file... i noticed i had been badly copy pasted thus rendering bad js

The proper file can be downloaded at: https://raw.githubusercontent.com/ckeditor/ckeditor-dev/master/plugins/filebrowser/plugin.js

And will be updated here shortly.

**Comment by thanhpt** [comment]
You mean we need to replace the current file with this file ?

https://raw.githubusercontent.com/ckeditor/ckeditor-dev/master/plugins/filebrowser/plugin.js

**Comment by mathieu-aubin** [comment]
yes, if you look at the current file you have... you'll see it's not valid. It has been copy/pasted wrongfully

**Comment by mathieu-aubin** [comment]
The repository now contains the right file, i have updated it when notified of this issue
you can see the commit [here](https://github.com/ladybirdweb/faveo-helpdesk/commit/ea4b2e9ce9b674dd0efa995e2598fe1ba28e37da)

**Comment by thanhpt** [comment]
Thank you Mathieu!

**Comment by mathieu-aubin** [comment]
@thanhpt my pleasure. Did it fix your problem alright?

**Comment by thanhpt** [comment]
I got your file but it keep on saying that :

plugin.js:389Uncaught ReferenceError: CKEDITOR is not defined(anonymous function) @ plugin.js:389(anonymous function) @ plugin.js:417

dataTables.bootstrap.js:6Uncaught TypeError: Cannot read property 'ext' of undefined(anonymous function) @ dataTables.bootstrap.js:6

So I think still need futhur investigation.

**Comment by mathieu-aubin** [comment]
different problem then, open another issue for this problem please

**Comment by mathieu-aubin** [comment]
If it can help, make sure all the templates references to file ckeditor.js are valid..

**Comment by mathieu-aubin** [comment]
I believe thoses files don't link correctly to plugin.js -- maybe i'm wrong but... it seems they should link to:
lb-faveo/plugins/filebrowser/plugin.js instead of plugins/filebrowser/plugin.js
```
resources/views/themes/default1/layouts/kb.blade.php:        <link href="{{asset("plugins/filebrowser/plugin.js")}}" rel="stylesheet" type="text/css" />
resources/views/themes/default1/layouts/kb.blade.php:                    <script src="{{asset("plugins/filebrowser/plugin.js")}}"></script>
resources/views/themes/default1/layouts/blank.blade.php:        <link href="{{asset("plugins/filebrowser/plugin.js")}}" rel="stylesheet" type="text/css" />
resources/views/themes/default1/layouts/blank.blade.php:                    <script src="{{asset("plugins/filebrowser/plugin.js")}}"></script>
```
make backups and try to see if that changes anything... or give me a means to reproduce your error

**Comment by thanhpt** [comment]
I think plugin.js use the definition of CKEditor but CKEditor is not defined anywhere.
Maybe you are right but in agent/dashboard it is correctly pointed to lb-faveo/plugins/filebrowser/plugin.js

**Comment by mathieu-aubin** [comment]
try it out and tell me... if it solves the problem then i'll update the repository.
