### ISSUE TITLE
error on install: "Trying to get property of non-object"

### ISSUE THREAD

**Issue by tttp** [ladybirdweb/faveo-helpdesk#103]
when trying to reach the url after the install, I get:

Trying to get property of non-object (View:.../faveo-helpdesk/resources/views/themes/default1/client/helpdesk/guest-user/index.blade.php)

The line in error seems to be:
<?php if(App\Model\helpdesk\Settings\System::first()->status == 1): ?>

Background: I'm trying to install using a different user on the shell than www-data, I had to change the owner of a few folders, I might have make a mistake, but right now, it's the only error I see.

Any suggestion on where to dig?

X+

**Comment by sujit223** [comment]
How did you installed the application? 
There seems to be no issue with the application. We re-tested after you created this issue here at github.

**Comment by tttp** [comment]
Hi,
Several errors, but the main one is that the files on my install aren't owned by www-data (security precaution) and a few folders had to be owned by www-data to get it working

**Comment by karenpommeroy** [comment]
Hi,
Can you tell us which folders require www-data ownerwship?

**Comment by mathieu-aubin** [comment]
It's a simple simple fact that the user under which the webserver is running (www-data in your case) has to have full READ permissions on the content being delivered. No matter what is being delivered.

As far as write permissions, that greatly varies... 

I am very very curious as to what type of 'security precaution' you are refering to.

As far as i'm concerned, a low priviledged-user such as 'nginx/apache/www-data' etc. along with about half an ounce of simple php security (like disabling some functions for a start) gets the whole 'danger' flag out of the equation pretty fast. But... i'm very very .. very often wrong. Could you explain?
