### ISSUE TITLE
500 error when open ticket after being assigned

### ISSUE THREAD

**Issue by thanhpt** [ladybirdweb/faveo-helpdesk#105]
The scenario is described below

Step 1 : Create Ticket and assign it to Support Department
Step 2 : Assign Ticket to Agent who belong to IT Department
Step 3 : Login using the Agent above and open the ticket that he/she was assigned
Result : 500 error

Cause : 

Ticket is created with Support Department as dept_id. Re-assign this ticket to member who belong to other department does not update dept_id with his/her primary_dpt.

When he/she open the ticket TicketController:thread($id) is called and the ticket detail is select from database with the following sql :  

> $dept = Department::where('id', '=', Auth::user()->primary_dpt)->first();
> $tickets = Tickets::where('id', '=', $id)->where('dept_id', '=', $dept->id)->first();

The $id is correct but the dept_id does not match with current user's primary_dpt as described below and cause null returned in $tickets. 

How to fix : 

In TicketController:assign() function by updating the ticket's dept_id with user's primary_dpt will solve the problem :

> elseif ($assign_to[0] == 'user') {
>             $ticket->assigned_to = $assign_to[1];
>             $user_detail = User::where('id', '=', $assign_to[1])->first();
>             $assignee = $user_detail->first_name.' '.$user_detail->last_name;
> 
> ```
>         $company = $this->company();
>         $system = $this->system();
> 
>         $ticket_number = $ticket->ticket_number;
>         $ticket->dept_id = $user_detail->primary_dpt; //Fix assign bug
>         $ticket->save();
> ```

That's a temporary fix.

**Comment by sujit223** [comment]
Thanks for notifying us this issue. We will try to make a better fix by our next release.

**Comment by thanhpt** [comment]
You are welcome! I will try my best to propose the fix also.

**Comment by SarfrazS** [comment]
I have tested this issue. Created new ticket with support dept and assigned to support Agent.
Again same ticket i assigned to sale dept Agent no error occurs.working fine.
