### ISSUE TITLE
wysihtml and bootstrap (css, js) are not correctly formated

### ISSUE THREAD

**Issue by thanhpt** [ladybirdweb/faveo-helpdesk#106]
This cause to some display error so by using the the bootstrap.min2.cs and wysihtml downloaded from AdminLTE will solve the problem.

**Comment by mathieu-aubin** [comment]
I only wish you would write more details about your errors...
which files (right filenames), what links, what error you got -- copy paste makes wonders when troubleshooting.

**Comment by thanhpt** [comment]
Sorry! It is not really a bugs so I just want to give share information with those who using community version : 
1- The symbols which is used on wysihtml editor tool bar are defined in bootstrap.min.css but seem that the font is broken with undefined characters. Using bootstrap.min2.css will solve the problem
2- The wysihtml it self seem to be old and may contain bugs like character disappear when fast typing ( I make a test with Vietnamese font and saw this problem). I downloaded the css and js from AdminLTE site and replace the old files with downloaded new one and it solve the problem.

Let say it is not a bug of faveo but the plugin it self.
