### ISSUE TITLE
workflow based on the recipient email?

### ISSUE THREAD

**Issue by tttp** [ladybirdweb/faveo-helpdesk#107]
Hi,
We are using the same email (say help@example.org) for different languages. It's the same email, but with different names (so "Bob" <help@example.org is english, but "Maria" <help@example.org> is spanish).
I want to set different workflows based on the name "Bob" vs "Maria" and route them to different agents, but didn't manage.

Is this possible or is the email rule based on the email name of the sender instead of the recipient?
Assuming it's the case, I'd like to implement a different filter criteria, would it be something to pull request?

**Comment by sujit223** [comment]
Hi,
Can you check if this is possible. We hope this might work. If this what you want.

![captureworkflow](https://cloud.githubusercontent.com/assets/11830376/16801551/114adee4-4919-11e6-9464-8277bc490067.PNG)

Do let us know. If it worked.
Also you can follow this link to make a pull request any time https://github.com/ladybirdweb/faveo-helpdesk/wiki/Contribution-Guide

**Comment by tttp** [comment]
Hey, 

thanks it works. Not sure why (it might be a case sensitive vs. insensitive)
