### ISSUE TITLE
Can't close ticket using 'Change Status' > 'Close'

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#108]
In the agent view of a ticket, there is a button to change status of the ticket. When clicking close, it does nothing.

Currently, I can work around it by going to the ticket list and selection the ticket checkbox, then clicking close.

**Comment by mverma16** [comment]
Hello @ajanes3,
We've tried to replicate your problem by closing the tickets from agent view tickets. But it seems to be working at our end. We'll test it and try to provide the solution in next release if this issue persist in current version.

**Comment by ajanes3** [comment]
Ok. I will continue testing and see if I can narrow down whats causing it on my end.
