### ISSUE TITLE
Error opening Departments as Administrator

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [ladybirdweb/faveo-helpdesk#11]
In line 107 sla_plan -> Sla_plan

/var/www/helpdesk.app/resources/views/themes/default1/admin/helpdesk/agent/departments/index.blade.php:
  105  									$sla = "";
  106  								} else {
  107: 									$sla = App\Model\helpdesk\Manage\Sla_plan::whereId($department->sla)->first();
  108  									$sla = $sla->grace_period;
  109  								}

**Comment by bhanu2217** [comment]
We are looking into the issue

**Comment by bhanu2217** [comment]
Issue resolved. Version 1.0.5.1 released with fix.
