### ISSUE TITLE
Assignment to a team doesn't work

### ISSUE THREAD

**Issue by guyguy333** [ladybirdweb/faveo-helpdesk#112]
Hi Faveo Team,

When you assign a ticket to a team, the assignment is not updated. In the left column, "Assignment" field is left to "Unassigned". However, in the ticket history, a message is displayed : "This Ticket has been assigned to Level 1 Support".
This issue also happens:
-  with Workflow in case you assign all new tickets to a team (works fine in case of a person). 
- in case the ticket was previously assigned to a person

Thanks

**Comment by mathieu-aubin** [comment]
Just a simple quick question... have you tried busting your browser's cache and retrying?
What configuration are you using, which webserver?

**Comment by guyguy333** [comment]
Hi @mathieu-aubin,

Yes, I did the test with a fresh browser without cache (Chromium and Safari). The system works well in case you assign to an agent (you've to refresh the page to get the left column updated) but not with a team.
I'm using Faveo v1.0.7.8 (f08b7e8e45213d03032e1516491eaec7df2f19aa) with Apache 2.4.6 and PHP 5.6.13 on CentOS 7.

Thanks

**Comment by mverma16** [comment]
Removing my assignment as @arindam85  is working on team module.
