### ISSUE TITLE
ASCII mails unsupported

### ISSUE THREAD

**Issue by guyguy333** [ladybirdweb/faveo-helpdesk#113]
Hi Faveo Team,

In case of an ASCII mail (not HTML), people replying to a mail will use the ">" character.
However, it completely destroys the ticket and becomes unreadable.
The issues disappears when you force your mail client to use HTML instead of ASCII (Tested with Thunderbird).

Thanks

**Comment by bhanu2217** [comment]
We are just working with UTF8 for now, We need to do more R&D on both reading and writing non UTF 8 characters. If you already have some ideas on this do share.

**Comment by sujit223** [comment]
Can you tell us in what scenario you require ASCII.

**Comment by mathieu-aubin** [comment]
@sujit223 
There are many situations where text/plain mail is required or the preferred way...  i understand it can be hard to visualize from a _win-user_ point of view where pretty much everything's graphical...
On linux, if configured to do so, Cron daemon per example, sends it's result output by mail in text/plain, most command-line applications, unless explicitely configured to do so, use text/plain.

Example header from cron deamon.. 
```
From root@example.com - Mon Jul 18 03:30:12 2016
[....some data removed...]
[....some data removed...]
Return-Path: <root@example.com>
Delivered-To: admin@example.com
Received: by mail.example.com (Postfix)
	id 9FC5D144276; Mon, 18 Jul 2016 03:30:03 -0400 (EDT)
Delivered-To: postmaster@example.com
Received: by mail1.example.com (Postfix, from userid 0)
	id 9583E145308; Mon, 18 Jul 2016 03:30:03 -0400 (EDT)
From: root@example.com (Cron Daemon)
To: root@example.com
Subject: Cron <root@example> /bin/sh /usr/bin/sql-backup
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <MailTo=>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20160718073003.9583E145308@example.com>
Date: Mon, 18 Jul 2016 03:30:03 -0400 (EDT)
```

Another thing that comes to mind is open source software mailing lists, still very popular today amongst developpers.. Most of them forbid the use of html formatting, thus text/plain has to be used.

html/mime also makes for much larger data being sent, negligeable you might say but it depends on your environment i suppose. There are a few more reasons that could apply to faveo as well, just can't think of any at the moment... heh

oH, yeah... html/mime messages are also one of the topmost source of spreading viruses, worms and trojans... not mentionning they also leave alot of undesirable attachments files on the user's system..

**Comment by bhanu2217** [comment]
This is what i am thinking of:

Currently in the mail header we don't read **_charset_** , We assume the charset is UTF8.
Probably we need to read the header charset and if it's non UTF8 convert it to UTF8 and then save this data in the system

Let me know your thoughts

**Comment by bhanu2217** [comment]
Came across this: http://stackoverflow.com/questions/7979567/php-convert-any-string-to-utf-8-without-knowing-the-original-character-set-or

**Comment by mathieu-aubin** [comment]
I honestly haven't had time to check on the situation and see what the output looks like when using text/plain against faveo.. One thing for sure, charset won't help. It could be any charsets and still produce the error from what i understand. Following your logic tho, i suggest evaluating the **_Content-Type_** headers of incoming emails and adjusting accordingly.

html/mime messages will most likely have `Content-Type: text/html;` as opposed to a non-html message which will have, as shown above, `Content-Type: text/plain;` for headers.

@bhanu2217 , again... charset isn't the problem as i understand... text/plain could have UTF-8 or any other charsets... **Faveo is assuming all emails are sent/received as html** (correct me if i'm wrong). Thus when a text/plain email is received, **faveo reads the data and "sees" characters** `<` and `>` as if they were HTML open/close brackets and tries to read/interpret them... Of course, the string `<user@example.com>` is **not a valid html code** in any way, "confusing" poor faveo, trying to understand that as if it was a `<span>` (or any other valid html code) per example.

Reading the Content-Type and adjusting the way faveo interprets the email is what i **think** will solve this issue.

**Comment by mathieu-aubin** [comment]
When you set your client back to html, the headers go back to being VALID and _**faveo's a happy camper**_!

**Comment by bhanu2217** [comment]
We do differentiate between text & HTML email while reading. Text & HTML mail via IMAP/POP come in separate arrays.

Character by default we assume is UTF8, thats why ASCII characters are not being read. There is an option to read characters in the email header but we are currently not reading

Here is another class to convert non UTF8 to UTF8

While sending emails we can send in UTF8.

**Comment by mathieu-aubin** [comment]
Okay, good then! I like when my assumptions are wrong... teaches me not to assume stuff :)

@bhanu2217 -- UTF8 is **Fully compatible with ASCII**
Playing with iconv... [have a look at this specific about locales](http://php.net/manual/en/function.iconv.php#74101)

**Comment by mathieu-aubin** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/UTF-8)

> "The encoding is variable-length and uses 8-bit code units. It was designed for backward compatibility with ASCII and to avoid the complications of endianness and byte order marks in the alternative UTF-16 and UTF-32 encodings."

**Comment by bhanu2217** [comment]
We will run some test on this and update a solution
