### ISSUE TITLE
Email function not working

### ISSUE THREAD

**Issue by yasiriqbal1** [ladybirdweb/faveo-helpdesk#1147]
Dear,
I installed and it worked fine. But, email function is not working.
I have installed on centos 7.

All requirements of system are OK. All functions work fine except Send email function. I want to integrate my exchange server email server with faveo. SMTP setting work fine but give error on imap and pop3.
PHP imap extension is also installed.

**Comment by JelleDijkhuizen** [comment]
Hi, i wrote i fix for that see #1931

**Comment by skullchap** [comment]
@yasiriqbal1  Did this PR fixed your problem? I'm facing the same issue when trying to bind Faveo to Microsoft Exchange server. SMTP works fine but imap gives an error.
@JelleDijkhuizen
