### ISSUE TITLE
Emails not retrieving properly

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#115]
Hello Faveo Team,

I am attempting to run the '/readmails' route to retrieve emails tickets. However, I am running into the following error.

> FatalThrowableError in MailController.php line 105:
> Call to undefined method PhpImap\Mailbox::get_overview()

I attempted to look over the Mailbox class to find the correct function. But none seem to match. Any idea what this is supposed to be?

**Comment by sujit223** [comment]
What version of faveo are you using?
Did u try to do composer update on the code?

**Comment by ajanes3** [comment]
I did do composer update. I checked the vendor source first but just checked your modified vendor source. Copying direct from your source has corrected the issue.

Is there anyway to break out the modifications from original vendor sources so that developers can utilize composer update?

**Comment by sujit223** [comment]
Yes, you just need to `composer require package name` this will install only one package. Without affecting the other packages.

**Comment by ajanes3** [comment]
Yes. But modifications to the original source defeats the purpose of utilizing external sources. From what I remember, there is a way to add your own custom functions to an existing vendor class, without having to modify the original source.

I have not done this yet. But I do remember it is possible.
