### ISSUE TITLE
Ticket is always created with default HelpTopic

### ISSUE THREAD

**Issue by thanhpt** [ladybirdweb/faveo-helpdesk#116]
What : When client creates a new ticket, how much he/she try to set the HelpTopic,  the ticket will be created with the HelpTopic's ID is the first one in the table.
Why : Let take a look at this file app/Http/Controller/Client/helpdesk/FormController
-> Line 151 :  $helptopic = $ticket_settings->first()->help_topic;
As we can see above line is not correct.
How : Comment out above line and replace with 
$helptopic = $request->input('helptopic');

Seem that developers forgot to correct the input.

**Comment by sujit223** [comment]
This issue have been fixed in our upcoming release. You may have a look here https://github.com/mverma16/faveo-helpdesk/blob/1f9f2ccbb10940ab34345bfcde9fb3d5926bea92/app/Http/Controllers/Client/helpdesk/FormController.php
Thanks for posting it here. You can keep notifying us for more like these.

**Comment by thanhpt** [comment]
Got it!
Thank you!

**Comment by sujit223** [comment]
@SarfrazS Please test this.

**Comment by SarfrazS** [comment]
I have tested, Successfully working.
