### ISSUE TITLE
Cannot end a section without first starting one.

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [ladybirdweb/faveo-helpdesk#12]
Cannot end a section without first starting one. (View: /var/www/helpdesk.app/resources/views/themes/default1/admin/helpdesk/emails/emails/index.blade.php)

The same is happening on the following routes :

http://helpdesk.app/emails
http://helpdesk.app/getdiagno
http://helpdesk.app/helptopic
http://helpdesk.app/sla
http://helpdesk.app/getcompany
http://helpdesk.app/getsystem
http://helpdesk.app/getemail
http://helpdesk.app/getticket
http://helpdesk.app/getresponder
http://helpdesk.app/getalert
http://helpdesk.app/plugins

**Comment by andersondeoliveiramachado** [comment]
removed all @stop who are before the <! - / Content -> and all routes began operating

That :

@stop


That is why :

**Comment by bhanu2217** [comment]
We are looking into the issue

**Comment by bhanu2217** [comment]
Issue resolved. Version 1.0.5.1 released with fix.
