### ISSUE TITLE
Interface Consistency

### ISSUE THREAD

**Issue by mbiolsi** [ladybirdweb/faveo-helpdesk#120]
Just a recommendation, that the terms in the agent interface remain consistent. See this: http://screencast.com/t/quaEvQ72GDx

**Comment by thanhpt** [comment]
I agree with you. The ticket's status is not defined well. You may also notice that when a ticket is closed it will be displayed in closed screen by accessing from tool bar but totally disappear from closed screen by access from side bar. This is a bug as there are 2 definitions of closed ticket  
- status == 2
- status == 2 and status ==3

**Comment by bhanu2217** [comment]
Custom status is already part of our roadmap, Hopefully in August you should see them. We will have consistency in the naming also as pointed out in the upcoming releases.

**Comment by DhanyaChengappa** [comment]
@KNaveenraj-ladybird 
1. Please get more clarity on the inconsistency that is mentioned
2. Get details on custom status Issue link

**Comment by KNaveenraj-ladybird** [comment]
> Just a recommendation, that the terms in the agent interface remain consistent. See this: http://screencast.com/t/quaEvQ72GDx


@mbiolsi hello sir can u share the video link for the issue if it still exists, has the link is expired or removed.

**Comment by bhanu2217** [comment]
@SarfrazS We are not able to replicate this issue. Can you check once and see if this issue is still existing.

**Comment by SarfrazS** [comment]
> I agree with you. The ticket's status is not defined well. You may also notice that when a ticket is closed it will be displayed in closed screen by accessing from tool bar but totally disappear from closed screen by access from side bar. This is a bug as there are 2 definitions of closed ticket
> 
> * status == 2
> * status == 2 and status ==3

Status == 2 is for Resolved
Status == 3 is for Closed 
There is no issue it working fine. In a community, we have very basic and less features.

**Comment by SarfrazS** [comment]
> Just a recommendation, that the terms in the agent interface remain consistent. See this: http://screencast.com/t/quaEvQ72GDx

This one I can't replicate because Screencast not opening for us now. So I'm closing this issue.

**Comment by KNaveenraj-ladybird** [comment]
@SarfrazS thanks for the confirmation sir
