### ISSUE TITLE
RuntimeException in GET /scogo_core_platform/public/agents

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#1214]
## Error in Faveo Community

**RuntimeException** in **GET /scogo_core_platform/public/agents**
No supported encrypter found. The cipher and / or key length are invalid.

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5c7ffc7fa90021001ac58920?event_id=5c7ffc7f0036c550d6720000&i=gh&m=ci)

## Stacktrace

    \app\Http\Middleware\NoCache.php:21 - App\Http\Middleware\NoCache::handle
    \app\Http\Middleware\HttpsProtocol.php:15 - App\Http\Middleware\HttpsProtocol::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5c7ffc7fa90021001ac58920?event_id=5c7ffc7f0036c550d6720000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 and custom tags from forked repositories will not checked as chances of them being already fixed in the newer versions are most likely and users are encouraged to update their system.
