### ISSUE TITLE
Auto complete ticket create forms

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#124]
**Link:** http://ladybirdweb.com/support/create-ticket
if the user is logged in the details should be autofilled

**Link:** http://ladybirdweb.com/support/newticket
In the agent panel, ticket create page give option for auto complete search and filling user details based on this

**Comment by arindam85** [comment]
Fixed,Tested by @SarfrazS ...

**Comment by arindam85** [comment]
released by @sujitprasad12
