### ISSUE TITLE
Illuminate\Database\QueryException in GET /public/ticket/get-closed

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#1285]
## Error in Faveo Community

**Illuminate\Database\QueryException** in **GET /public/ticket/get-closed**
SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared (SQL: select max(`id`) as aggregate from `ticket_thread` where `ticket_id` = 64 and `is_internal` = 0)

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5c8799d33264910018b96533?event_id=5c8799d300375a9c5b9a0000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Agent/helpdesk/TicketController.php:2331 - Illuminate\Database\Eloquent\Builder::max
    app/Http/Controllers/Agent/helpdesk/TicketController.php:2331 - App\Http\Controllers\Agent\helpdesk\TicketController::App\Http\Controllers\Agent\helpdesk\{closure}
    app/Http/Controllers/Agent/helpdesk/TicketController.php:2393 - App\Http\Controllers\Agent\helpdesk\TicketController::getTable
    app/Http/Controllers/Agent/helpdesk/TicketController.php:225 - App\Http\Controllers\Agent\helpdesk\TicketController::get_closed
    app/Http/Middleware/Authenticate.php:52 - App\Http\Middleware\Authenticate::handle
    app/Http/Middleware/CheckUpdate.php:35 - App\Http\Middleware\CheckUpdate::handle
    app/Http/Middleware/LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5c8799d33264910018b96533?event_id=5c8799d300375a9c5b9a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 will not checked as chances of them being already fixed in the newer version are most likely and users are encouraged to update their system.
