### ISSUE TITLE
Inbox page style issue

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#129]
**Link:** http://ladybirdweb.com/support/ticket/inbox

The no of records per page button is joining the delete, also in Mozilla it is sharp corners and in chrome it becomes rounded.

**Screenshot:**
![faveo help desk 2016-07-21 10-16-13](https://cloud.githubusercontent.com/assets/240898/17011486/349e37a6-4f2c-11e6-851c-948041dd441e.png)

**Comment by mverma16** [comment]
Gap between no of records and delete button has been provided, button has sharp corners in all browsers in windows but in round corner in mozilla in mac. Need to check.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.7.9.1 Delete and No of record have space.
I tested on two browser crome and mozilla.
