### ISSUE TITLE
Environment.php

### ISSUE THREAD

**Issue by dabaptist24** [ladybirdweb/faveo-helpdesk#13]
Your installation guides aren't very complete, yet I tried to install Faveo but there is no environment.default.php under the boostrap directory.

**Comment by bhanu2217** [comment]
I just checked and there is mistake in our guide, we are rectifying it now and will update you in a while.

**Comment by bhanu2217** [comment]
We have updated the guide http://www.ladybirdweb.com/support/category-list/installation-and-upgrade-guide
