### ISSUE TITLE
Change Help topic form

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#132]
Make changes to help topic custom form, to have multi level child elements which can further have dynamic forms linked to them. Child elements are triggered with status change on drop drop,radio button, checkboxes etc.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC working fine.

**Comment by louisServeurcom** [comment]
In 1.10 I got issuewhen I select an option my child appear but others who are requiered failed the sending of the form, that could be fixed?
