### ISSUE TITLE
Ticket Editor Links open in new tab

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk#137]
In the current ticket editor whenever links are added there is an option to check "open the links in new tab" but when displayed those links the links don't open in new tab.

**Comment by bhanu2217** [comment]
Also, one needs to to keep pressing enter to move to new line, There are issues with enter key in the editor, it gets you back on same line

**Comment by mverma16** [comment]
In current editor when you add link you can set the target as per your requirement. Select "_blank" for opening the links in new tab.
