### ISSUE TITLE
Id injection has issue with valid route.

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk#138]
There are some routes which are system routes and require some Id.
The routes looks like `thread/{id}`. These types of routes require just to pass an Id in the system for a normal case scenario.
But in case of Id injetion the routes returns 500 error for reason that the injected id was not found in the system. 
As per faveo these ID should be integer Id and should be valid in the system. But if text id is passed it will return a `trying to get property of non object error` this id needs to be checked and validated.
Task:-
1. find a global solution to such routes.
2. If failed point 1 fix each route manually in every controller.

**Comment by bhanu2217** [comment]
**Ideally** 

- 404 error page should be shown in case of ID injection if the id doesn't exist in the system.
- Security error or illegal access page should be shown if ID exists but user doesn't have permission to view that ID.
