### ISSUE TITLE
showing wrong count of comments in client panel

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#139]
In client panel ticket lists page, table is showing the wrong count of comments(thread conversation). Internal notes are also getting count in threads. Client should only see the count of conversation between agents and him/herself. Exclude system comments and internal notes from this count.

**Comment by mverma16** [comment]
Issue fixed and will be released in next version after testing.

**Comment by SarfrazS** [comment]
I have tested  count of conversation between agents and him/herself coming correct.
