### ISSUE TITLE
POP3 unable to fetch

### ISSUE THREAD

**Issue by SharkWipf** [ladybirdweb/faveo-helpdesk#148]
When trying to configure email to fetch with POP3, Faveo will try to fetch for 60 seconds before showing an (IMAP related?) error message: 

```
Alert!×
Incoming email connection failed! Please check email credentials or Imap Settings
```

The Dovecot mailserver it tries to connect to shows the following in the logs, confirming Faveo is at least setting up a connection (IPs changed for privacy reasons):

```
Jul 29 20:59:03 tauri dovecot[967]: pop3-login: Disconnected (no auth attempts in 60 secs): user=<>, rip=111.111.111.111, lip=111.111.111.112, session=<2OYb2Mo4ob2NaXks>
```

Connecting with IMAP works just fine.

Faveo Version: Community 1.0.7.8 
Host OS: CentOS 7 with DirectAdmin, Nginx and PHP 7.0.9.
PHP IMAP and all the other required PHP extensions are all installed and enabled.
Mailserver: Dovecot 2.2.24
No firewalls are blocking Faveo.

Possibly related: I also could not get SMTP to work, only PHP-SMTP worked.

**Comment by bhanu2217** [comment]
The error message is common, we will correct that.

Is it possible for you to share your pop server details with us, so we can run some checks and see what is the issue. You can email us on support@ladybirdweb.com

**Comment by SharkWipf** [comment]
I'm afraid I'm not in a position where I can share our server details with you, I'm sorry.
I can share the configuration of the servers, both POP3 server and Faveo server are fairly standard DirectAdmin servers (DirectAdmin + Nginx + PHP7.0.9 (+ Faveo required modules and Imagick) + Dovecot 2.2.24, all custombuild 2.0)

I'll probably be setting up Faveo on a different, personal server in a few days, if I run into the issue there again I can give you access.

**Comment by mathieu-aubin** [comment]
Hi, 
Most important things, considering that's pretty much all you could have given as far as information, you havn't mentionned... Connection scheme used and the authentification method (client **and** server). Also appart from the fact you say it's not working _in faveo_, we have yet to know if it's working at all.

login thru ssh and check for openssl version (my openssl is a build i compiled not long ago) but all in all, you should have at least 1.0.2h(3may2016).
```bash
root@mail:~$ openssl version
OpenSSL 1.1.0-pre6-dev  17 July 2016 CUSTOM BUILT
```
Now, verify your host has the properly configured ports open
```bash
IPv4="$(curl -s v4.ident.me)"
nmap -sT -O ${IPv4} | grep "pop3\|smtp\|imap\|submission"
25/tcp  open   smtp
110/tcp open   pop3
143/tcp open   imap
587/tcp open   submission
993/tcp open   imaps
995/tcp open   pop3s
```
Install nmap if it's not installed `root@mail:~$ yum install nmap -y`

Now, if you know you are allowed to send plaintext and you are not using a ssl port, you can use
```bash
root@mail:~$ telnet blahblah.com 110
Trying 111.2.103.121.2...
Connected to blahblah.com.
Escape character is '^]'.
+OK Dovecot (Ubuntu) ready.
root@mail:~$ USER root@blahblah.com
-ERR [AUTH] Plaintext authentication disallowed on non-secure (SSL/TLS) connections.
...
```

Meaning i'm using SSL.. the you need tu use openssl on the ssl port
```bash
root@mail:~$ openssl s_client -connect blahblah.com:995
...
```

You should see the ssl handshake and be able to login. Watch your logs.. /var/log/dovecot.log - and maillog or mail.log
If you can't connect in any way, just use imap. I ll see how faveo does it's work... i believe there isn't much error checking but only a timeout so if you get kicked out by trying PLAIN TEXT, it won't do anything and give you the error.

Let me know

**Comment by SharkWipf** [comment]
Right, I forgot to mention the connection scheme I'm using. I've tried both StartTLS and None for encryption, neither worked.
I'm connecting on port 110 on "mail.example.com", the only available authentication method seems to be "Normal Password". I did not tick the "Validate Certificates" box in Faveo.

I can confirm POP3 is working as I import my own mail over POP3 within Gmail from the same server.
See also the tests below.

Nmap result, from the "Faveo server" to the "Mail server":

```
nmap mail.example.com

Starting Nmap 6.40 ( http://nmap.org ) at 2016-08-03 20:37 CEST
PORT     STATE SERVICE
25/tcp   open  smtp
53/tcp   open  domain
80/tcp   open  http
110/tcp  open  pop3
143/tcp  open  imap
443/tcp  open  https
465/tcp  open  smtps
587/tcp  open  submission
888/tcp  open  accessbuilder
993/tcp  open  imaps
995/tcp  open  pop3s
```
Plus some higher ports used by our own applications.

```
$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
Same on both servers, the latest available on CentOS 7 without self-compiling it. Should have any security issues patched by the CentOS team.

```
support@support.example.com$ nc mail.example.com 110
+OK Dovecot DA ready.
USER faveotest@example.com
+OK
PASS $ecur3P@$$w0rd
+OK Logged in.
LIST
+OK 1 messages:
1 2814
.
RETR 1
+OK 2814 octets
{snip}
quit
+OK Logging out.
```

With OpenSSL:
```
support@support.example.com $ openssl s_client -connect mail.example.com:995
CONNECTED(00000003)

{Lots of certificate stuff snip}

    Start Time: 1470250444
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
+OK Dovecot DA ready.
USER faveotest@example.com
+OK
PASS PHEoAM4P0Haaa
+OK Logged in.
LIST
+OK 1 messages:
1 2814
.
quit
+OK Logging out.
closed
```

Bonus: TCPDump on the mail server, only thing connecting is Faveo:
```
# tcpdump -i eth0 -l -A -s2000 port 110 and host support.example.com
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 2000 bytes
21:19:27.748658 IP support.example.com.59454 > mail.example.com.pop3: Flags [S], seq 493128494, win 29200, options [mss 1460,sackOK,TS val 4150787768 ecr 0,nop,wscale 7], length 0
\............iy,.iy..>.n.d........r.
.g..........
21:19:27.748718 IP mail.example.com.pop3 > support.example.com.59454: Flags [S.], seq 302608143, ack 493128495, win 28960, options [mss 1460,sackOK,TS val 1078180454 ecr 4150787768,nop,wscale 7], length 0
\.........-..iy..iy,.n.>.	o..d./..q 
@C.f.g......
21:19:27.748843 IP support.example.com.59454 > mail.example.com.pop3: Flags [.], ack 1, win 229, options [nop,nop,TS val 4150787769 ecr 1078180454], length 0
T.....@.@....iy,.iy..>.n.d./.	o.....
.g..@C.f
21:19:27.749457 IP mail.example.com.pop3 > support.example.com.59454: Flags [P.], seq 1:24, ack 1, win 227, options [nop,nop,TS val 1078180455 ecr 4150787769], length 23
k.....@.@.X	.iy..iy,.n.>.	o..d./....
@C.g.g..+OK Dovecot DA ready.

21:19:27.749631 IP support.example.com.59454 > mail.example.com.pop3: Flags [.], ack 24, win 229, options [nop,nop,TS val 4150787769 ecr 1078180455], length 0
T.....@.@....iy,.iy..>.n.d./.	o'....
.g..@C.g


{nothing here until timeout below}


21:20:27.766757 IP support.example.com.59454 > mail.example.com.pop3: Flags [F.], seq 1, ack 24, win 229, options [nop,nop,TS val 4150847787 ecr 1078180455], length 0
T.....@.@....iy,.iy..>.n.d./.	o'....
.h.+@C.g
21:20:27.766923 IP mail.example.com.pop3 > support.example.com.59454: Flags [F.], seq 24, ack 2, win 227, options [nop,nop,TS val 1078240472 ecr 4150847787], length 0
T.....@.@.X..iy..iy,.n.>.	o'.d.0....
@D...h.+
21:20:27.767059 IP support.example.com.59454 > mail.example.com.pop3: Flags [.], ack 25, win 229, options [nop,nop,TS val 4150847787 ecr 1078240472], length 0
T.....@.@....iy,.iy..>.n.d.0.	o(....
.h.+@D..
```
As you can see Faveo opens a connection, Dovecot replies it is ready, and the authentication process seems to stop there.

**Comment by bhanu2217** [comment]
@sujit223 Can you please share some sample php script to test email connection to figure out the issue, if the issue is with script or server setting

**Comment by bhanu2217** [comment]
We can created some test for you to run, These are simple php scripts. If they fail than it could be issues with server setting, if they pass than issue is with Faveo. 

**Link:** https://github.com/ladybirdweb/faveo-testing-tools/

**Comment by SharkWipf** [comment]
````
Email = faveotest@example.com
Password = $ecur3P@$$w0rd
Host = mail.example.com
Port = 110
Protocol = /pop3
Encryption = /tls/novalidate-cert



email config = string(52) "{mail.example.com:110/pop3/tls/novalidate-cert}" Result = resource(4) of type (imap) if result comes in 'resource' then the connection was succesfull
```
So that seems to be working fine.

I've also ran Faveo Probe (however, I've had to modify it slightly, it currently does not run on Nginx: `Uncaught Error: Call to undefined function apache_get_modules()`), everything returned "ok".

**Comment by mathieu-aubin** [comment]
Move to port 995. Tested working
And please, do yourself a favor, update openssl
https://www.openssl.org/source/

**Comment by SharkWipf** [comment]
Port 995, SSL, no cert validation: Works. (TLS and STARTTLS do not, but that makes sense)
Port 110, TLS, no cert validation: Works. (SSL and STARTTLS do not, but that makes sense)
Port 110, encryption disabled (what I originally tested with): Does not work (works in faveo-testing-tools as `mail.example.com:110/pop3/notls`)

So it seems it is "just" unencrypted POP3 not working. I'd swear I tested port 110 with TLS before too, but apparently not.

I currently have no reason to update OpenSSL, CentOS' version is stable, well-tested and patched against all known security issues and I'm not going to risk breaking live servers by compiling OpenSSL from source. The only issue with this version is that it won't work with HTTP/2 due to lack of ALPN, but most of our traffic is within our own company anyway.
