### ISSUE TITLE
Error 500 after admin login

### ISSUE THREAD

**Issue by eduardohs** [ladybirdweb/faveo-helpdesk#149]
I have a fresh install of faveo, after login with admin i get a error message

You are here : 500

Sorry, Something went wrong
Were working on it and we'll get it fixed as soon as we can.

I followed steps from this issue https://github.com/ladybirdweb/faveo-helpdesk/issues/95

```
In App\Http\Middleware\CheckUpdate.php
Replace \Carbon\Carbon::now(-24); With \Carbon\Carbon::yesterday();
```

but doesn't work for me..

**Comment by sujit223** [comment]
Go to root path/.env
Edit this file
Search for DEBUG = false and change it to true.
Send us the screen shot of the error occured

**Comment by flygav1** [comment]
{!! $notification->notification->type->message !!} with id "{!!$notification->notification->model->ticket_number!!}"

is the error im getting , same error 500 as op

**Comment by flygav1** [comment]
{!! $notification->notification->type->message !!} with id "{!!$notification->notification->model->ticket_number!!}" same error here sadly, bricked my site cant assess dashboard after admin login
