### ISSUE TITLE
Cannot create workflows: "Alert ! Undefined index: b"

### ISSUE THREAD

**Issue by SharkWipf** [ladybirdweb/faveo-helpdesk#151]
Creating workflows does not seem to work in the latest version of Faveo.

Workflow Action is lacking the required fields (only the Condition can be set, the Rules field is empty).
Saving the workflow, even with a condition that does not need extra info like the "Reject Message" option, displays a message saying "× Alert ! Undefined index: b".

Faveo Version: Community 1.0.7.8
Host OS: CentOS 7 with DirectAdmin, Nginx and PHP 7.0.9.
All the required PHP extensions are installed and enabled.

**Comment by sujit223** [comment]
Thanks for raising this issue. Can you please send an screen shot of the issue. And step by step activity. We would like to replicate the issue.

**Comment by SharkWipf** [comment]
Of course: 
1. Create a new workflow
2. Choose any rule, doesn't matter what
3. Choose any action
4. Fill in the other required fields and hit submit
5. Aforementioned error pops up, the workflow is created, but without any assigned actions

On editing an existing workflow the actions aren't saved either, but the error doesn't show up.

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/751205/17301423/4497683c-5817-11e6-9399-aea8e84073e9.png)
![image](https://cloud.githubusercontent.com/assets/751205/17301433/4bcc4be0-5817-11e6-8703-4a2ca3e3f104.png)
![image](https://cloud.githubusercontent.com/assets/751205/17301439/536f0fd6-5817-11e6-99de-565adcfecee4.png)

(BTW, aside from the bugs I'm really liking Faveo so far, the community edition already is better than other FOSS alternatives and, once it becomes more stable, we might very well be looking into buying the Support Desk version.)

**Comment by sujit223** [comment]
Can you check if javascript is working.

**Comment by sujit223** [comment]
We also tried most known browsers. Could not replicate the issue. Please help us figure this out. Please raise a ticket at our support@ladybirdweb.com

**Comment by SharkWipf** [comment]
Hmm, strange. Javascript seems to be working fine, I am seeing 3 errors in the console though (on all pages, not just these): 
![image](https://cloud.githubusercontent.com/assets/751205/17325737/8955e994-58ad-11e6-9932-a9e1de1ca551.png)

I am seeing the following errors pop up in the Laravel log on pretty much every page too, not sure if related:
```
Next ErrorException: Undefined variable: errors (View: /home/support/domains/support.example.com/resources/views/themes/default1/client/layout/client.blade.php) in /home/support/domains/support.example.com/storage/framework/views/4ebf6bd10e73df789f302eb951d39e707bf982bb.php:122
Next ErrorException: Undefined variable: errors (View: /home/support/domains/support.example.com/resources/views/themes/default1/client/layout/client.blade.php) (View: /home/support/domains/support.example.com/resources/views/themes/default1/client/layout/client.blade.php) in /home/support/domains/support.example.com/storage/framework/views/4ebf6bd10e73df789f302eb951d39e707bf982bb.php:122
```

I'm using the latest stable Google Chrome on Windows. I've just tried it in Edge (ew), but the same problem appears there.

I'll set up a Faveo installation on a clean, non-DirectAdmin VM in a bit to see if I get the same problem(s) there. I'll raise a ticket with your support afterwards (if I haven't figured out the cause yet then).

**Comment by sujit223** [comment]
The above two errors that got reported in Laravel log have been fixed in the upcoming version. But they are not related to workflow. 
It seems quite strange about the workflow error. It should not be happeing that way. Anyways you can try a fresh install even though the error still occurs, please raise a ticket.

**Comment by SharkWipf** [comment]
Okay, I've been diving into the code a bit, it seems everything is executed fine right until the selectAction() function in `app/Http/Controllers/Admin/helpdesk/WorkflowController.php`.
Here, `$request->option` seems to be NULL.
As such, http://support.example.com/workflow/action-rule/0?option=priority and the other options return an empty file.

I suspect this might be an issue in my Nginx configuration, I had to be a little creative with it in order to get it working with DirectAdmin and Nginx. I'll mess around with my configs a bit and see if I can figure it out.
Feel free to close this issue if you want.

**Comment by SharkWipf** [comment]
Alright, I've managed to solve the problem, it was indeed an Nginx configuration issue on my end.
I had almost everything working right, the only thing I had wrong was: 
```
location /
{
    try_files $uri $uri/ /index.php;
}
```

Which should have been: 
```
location /
{
    try_files $uri $uri/ /index.php?$args;
}
```

After changing this it started working correctly.
Thank you for your patience and assistance in debugging this problem.

**Comment by sujit223** [comment]
Its good to know that you got it fixed.
