### ISSUE TITLE
Deleting the "default" template breaks templates altogether

### ISSUE THREAD

**Issue by SharkWipf** [ladybirdweb/faveo-helpdesk#152]
Deleting the "default" e-mail template makes Faveo throw a 500 error every time you try to edit a template.
This makes creating and editing other templates impossible.
Problem only goes away when manually re-adding the default template to the database.

Faveo Version: Community 1.0.7.8
Host OS: CentOS 7 with DirectAdmin, Nginx and PHP 7.0.9.
All the required PHP extensions are installed and enabled.

**Comment by sujit223** [comment]
Thanks for notifying us.

**Comment by bhanu2217** [comment]
Check throughout the system default option shouldn't be delete able, Other template or any one template can be made default but whatever is default shouldn't be delete able

**Comment by mverma16** [comment]
Fixed in template deletion but need to check complete system for the issue.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC default template should not delete able.Only inactive template Delete able.
