### ISSUE TITLE
"Banning" e-mail addresses doesn't work

### ISSUE THREAD

**Issue by SharkWipf** [ladybirdweb/faveo-helpdesk#153]
Currently, it seems the only thing banning a user does is displaying a message on tickets sent in by that user.
The user can, however, still send in tickets by e-mail and they will still be created as normal.
They will also still get the "new ticket created" e-mail.

Faveo Version: Community 1.0.7.8
Host OS: CentOS 7 with DirectAdmin, Nginx and PHP 7.0.9.
All the required PHP extensions are installed and enabled.

**Comment by SarfrazS** [comment]
Ban  user can, however, still send in tickets by e-mail and they will still be created as normal.
They will also still get the "new ticket created" e-mail.
