### ISSUE TITLE
Image create from string error for incomplete downloaded Inline images

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk#155]
There are some issue with the inline for larger file sizes. Need to test in multiple case scenario and larger data sizes.

**Comment by bhanu2217** [comment]
Ideally there should be a reload email button on every ticket to reload the email or attachment content incase for some reason there was failure, more R&D needs to be done on this.

But even if the attachment or email was not loaded properly it shouldn't' result in failure but proper exception handling.
