### ISSUE TITLE
File upload check

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#157]
A check needs to put where, file upload option is available to see which all kind of files can be uploaded.

**e.g**
System logo should be: png, jpg or gif. So no other file can be uploaded other than these types

**Comment by mathieu-aubin** [comment]
hey guys, what about svg? or even base64 encoded? @sujit223 let me know were this gets processed so i can have go at it -- would be an ok mod for pro version
