### ISSUE TITLE
User can login without activating their account

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#158]
After registration user has to activate his account by clicking on the activation link he receives in his mailbox otherwise he'll not be able to login to the system. Although if user tries to reset password, after resetting password he logs into the system without activation of his account.

**Comment by bhanu2217** [comment]
As the password  reset email is also going on the email address and user resets the password via the link sent on email. That should be understood as email verification, so i think it solves the purpose

**Comment by mverma16** [comment]
Yes, I think I missed that part.
