### ISSUE TITLE
Auto Installer

### ISSUE THREAD

**Issue by dabaptist24** [ladybirdweb/faveo-helpdesk#16]
I got your code to the point where it goes through the installation steps, but runs into "500 Internal Server Error." Why has this happened? Is there an error log? I met all the criteria.

**Comment by bhanu2217** [comment]
There is a issue with auto installer, we are working on it

**Comment by mmeckens** [comment]
Curious as to when we are expecting an update? 
I have tried to perform a manual install, although when running: php artisan db:seed I get an Integrity constraint violation. Any ideas?

**Comment by bhanu2217** [comment]
We are working on the update, fixing few bugs. Hopefully we should be able to release the update by evening today IST.
Have added new additional features to this upcoming release like rating tickets, also option to have different from address for different department, user editable email templates for all the emails that go out from the system.

**Comment by sujit223** [comment]
We have fixed this issue
