### ISSUE TITLE
Variable Question/Issue

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#161]
https://github.com/ladybirdweb/faveo-helpdesk/blob/master/app/Http/Controllers/Client/helpdesk/GuestController.php

Line 322, is that variable supposed to be $id1 ?

It seems like it is done that way to bypass the id decrypt, in which case the whole line should be removed.

Or something else. You tell me.

**Comment by sujit223** [comment]
There is no use of it. Will be removed in the next version.
