### ISSUE TITLE
How to setup e-mails?

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk#162]
I have setup 3 e-mail addresses but they are not receiving e-mails.
The cron jobs are setup this way: 
![screenshot from 2016-08-07 21-10-35](https://cloud.githubusercontent.com/assets/3397477/17539454/8b34b46a-5f02-11e6-8c24-d05eb05f77e0.png)
What am I doing wrong?

**Comment by bhanu2217** [comment]
If you run this url http://faveo.jeeja.biz/public/readmails directly in the browser, does it read email? If yes than you need to figure out correct command from your hosting provider to execute this url in cron

**Comment by SharkWipf** [comment]
I just ran into an issue where the 2nd mailbox (and possibly others?) is not checked for mail when the first mailbox doesn't have any new mail. Still investigating this issue.
The moment you send to the first mailbox Faveo will suddenly fetch all e-mails from all boxes, and will keep fetching it just fine until visiting /readmails shows the "no new mail" message again.
I suspect this may happen when the first mailbox hasn't had any new mail in a few days (Faveo doesn't import any older mails), I'm still investigating the specifics though.
@francesco1119 If you send an e-mail to all your configured mailboxes, will they start working afterwards?

**Comment by francesco1119** [comment]
Tried now and after few minutes still no e-mails getting through.

**Comment by francesco1119** [comment]
Right, but now that I run this http://faveo.jeeja.biz/public/readmails  yes it worked.
So that means that my cron job is not setup correctly

**Comment by bhanu2217** [comment]
May be cron job command on your server is different not to use curl....
You should check with your server hosting company once how to execute URL's in cron

**Comment by bhanu2217** [comment]
@SharkWipf once you are sure of the 2nd mailbox not reading issue, do update us so we can also check

**Comment by francesco1119** [comment]
The issue looks solved guys. The hosting is running a normal cPanel.
I just setup the cron job to run every 5 minutes instead of every minute. 
Not sure if it was an issue with my hosting or Faveo

**Comment by bhanu2217** [comment]
Every hosting company sets different limit on their server, your hosting company probably doesn't allow running cron every minute

**Comment by SharkWipf** [comment]
@bhanu2217 I've opened a new issue for my problem in #167, as it ended up not being related to this thread's original issue. This issue can probably be closed.
