### ISSUE TITLE
UI issue fix patch for Google Chrome

### ISSUE THREAD

**Issue by n3zsistemas** [ladybirdweb/faveo-helpdesk#1665]
- Faveo Version :  v1.10.5 
- PHP version :   7.1.28
- Database Driver & Version : Mysql 
- Server specification : Ubuntu 16.04

#### Description:
Even after updating to the latest version v1.10.5 that corrected the bug UI issue fix patch for Google Chrome, when as soon as user write a new ticket the information is still blank using chrome in firefox everything is correct this in the central Support.

#### Steps To Reproduce:
Firefox;
![image](https://user-images.githubusercontent.com/7523358/56157700-8b669600-5f96-11e9-8a7b-ba8e28122208.png)

Chrome;

![image](https://user-images.githubusercontent.com/7523358/56157745-a9cc9180-5f96-11e9-9eeb-313f52aa2bfb.png)

#### Downloaded from
- [X ] master-branch

- [ ] release-tag
- [ ] development-branch

**Comment by mverma16** [comment]
@n3zsistemas thanks for reporting the issue, we totally missed it for client panel.

Please check [this commt](https://github.com/ladybirdweb/faveo-helpdesk/commit/e94cc7cfce970bb259e3766f50590affb82a9a77) for the patch or update to v1.10.6
