### ISSUE TITLE
Mail not fetched from 2nd+ box if messages in 1st are over a day old

### ISSUE THREAD

**Issue by SharkWipf** [ladybirdweb/faveo-helpdesk#167]
(Opening a new issue for this since #162 seems to have been a different problem)
Possibly related: #59 

When having more than 1 mailbox, if the latest messages in the first checked (?) mailbox are over a day old, other mailboxes are no longer checked for new mail, no matter how many new mails there are.
This is regardless of if the latest message has already been fetched/marked read or not.
Visiting the `/readmails` URL will display the `Mailbox is empty` message.

When sending a new e-mail to the first mailbox, all mail from all mailboxes will be fetched at once.
Faveo will then continue to behave as expected, fetching all mail from all mailboxes without issues, until the latest mail is over a day old again.
While Faveo is working, visiting `/readmails` returns an empty page, even when there is no new mail to fetch.

Setup: 
2  mailboxes connecting to the same server on different domains:
- support@domain1.com (IMAP, port 143, TLS, novalidate-cert): Primary mailbox and first fetched
- support@domain2.com (IMAP, port 143, TLS, novalidate-cert): Secondary mailbox

Changing what mailbox is primary does not change what mailbox is fetched first and thus does not seem to affect this problem.
Secondary mailbox is not fetched when the first one only has "old" messages.
Otherwise both work perfectly fine.

Faveo Version: Community 1.0.7.8 
Host OS: CentOS 7 with DirectAdmin, Nginx and PHP 7.0.9.
PHP IMAP and all the other required PHP extensions are all installed and enabled.
Mailserver: Dovecot 2.2.24
OpenSSL version: OpenSSL 1.0.1e-fips (I know, I know, CentOS stable version)
No firewalls are blocking Faveo.

**Comment by SharkWipf** [comment]
Did some quick digging, the issue seems to be caused by the `die()` in [MailController.php#L109-L111](https://github.com/ladybirdweb/faveo-helpdesk/blob/bda543a/app/Http/Controllers/Agent/helpdesk/MailController.php#L109-L111).
I do see the code there changed slightly compared to version 1.0.7.8 I'm running, but as far as I can see the issue is still there.

**Comment by sujit223** [comment]
Thanks for the idea. This will be fixed by our next release.
