### ISSUE TITLE
email address alias and suddent ErrorException

### ISSUE THREAD

**Issue by darkysabertooth** [ladybirdweb/faveo-helpdesk#168]
Hello,

Is Faveo Helpdesk Community (version #) compatible with email aliases for example: info@(company) is a real address. Payment@(company) emails info@(company) as it is an alias.

The question above is related to the issue. During our tests something broke, when clicking "create a ticket" from (website/faveo/public/create-ticket) you end up with the following errors after adding an e-mail through admin that is an alias for outgoing mail.
ErrorException in d505258985aed0a09d091757732351f46e1459d7.php line 108:

I have removed the outgoing e-mail (that is an alias) through the admin panel and despite verifying that the default e-mail is the non-alias account when attempting to create a ticket I get the same error as above.

My Faveo install is now currently unable to create tickets through the "create ticket button"

**Comment by bhanu2217** [comment]
Can you provide us the link and access to your Faveo installation, so we can login and check.

**Comment by quyetpawz** [comment]
Hello, I am working with Darky on testing Faveo for our purposes. We actually wound up deleting everything and starting over entirely. 

Could you tell us directly whether Faveo's e-mail system is compatible with -sending from- e-mail aliases?

**Comment by bhanu2217** [comment]
The SMTP details you enter should be working & correct. Faveo is just sending email from email account that you provide.

If you don't want to use SMTP, you can also use PHP mail function

**Comment by quyetpawz** [comment]
E-mail aliases to "send from" don't necessarily have passwords which your system seems to require. If there a way to configure the system to use aliases to e-mail from?
