### ISSUE TITLE
Client panel issues

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#169]
**Version:** 1.0.7.9
**Link:** http://www.faveohelpdesk.com/demo/helpdesk/public/client-profile
- Radio button and text needs one word gap
- Change password text boxes remove placeholders from input control as there is label also

**Link:** http://www.faveohelpdesk.com/demo/helpdesk/public/mytickets
Click on any ticket, gives something went wrong error

**Comment by mverma16** [comment]
made changes in view will be a part of next release
