### ISSUE TITLE
Error, Désolé, un imprévu a eu lieu

### ISSUE THREAD

**Issue by dirlanda** [ladybirdweb/faveo-helpdesk#1728]
- Faveo Version :1.10.6
- PHP version : 7.1.28
- Database Driver & Version : 5.5.60-MariaDB
- Server specification : windows 10

#### Description:

I use the application 2 days all goes well
 today I decided to authenticate and I found this problem in the picture
even I clone the same app and want to login 
i find the same problem please some help and thank you

![ca1](https://user-images.githubusercontent.com/19295129/56612185-93b07800-660b-11e9-8ba6-55c2e58d5ddb.PNG)

#### Downloaded from
- [] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by lwsalerts** [comment]
@dirlanda have you been able to rectify this issue?

**Comment by dirlanda** [comment]
Hello,

No this is my problem in the video i have 2 pages white the same problem i can’t login or do nothing

**Comment by dirlanda** [comment]
3days and im using the app without any problem today i found this problem,
I.ve installed it from the beginning always the same problem please help me
I forgot Im using :
faveo version 1.10.6
php 7.1.28
windows 10   xampp

Le mer. 24 avr. 2019 à 20:22, soufiane afia <soufianeafia@gmail.com> a
écrit :

>
> Hello,
>
> No this is my problem in the video i have 2 pages white the same problem i
> can’t login or do nothing
>
>
