### ISSUE TITLE
Username maximum 30 characters issues 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#175]
**Issue:** On user profile page if username is larger than 30 characters the edit profile will not happen.

**Link:** http://www.faveohelpdesk.com/demo/helpdesk/public/profile-edit

**Solution:**
- Remove 30 characters limitation on profile page for user name
- Places where we are displaying username, put excerpt function to limit the number of characters while display, so as to not break HTML design

**Comment by bhanu2217** [comment]
- Tool tip, Title can be used to show full username on profile page
- Regarding username limit, see how other systems are working.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC working. I created username greater than 30 character and tool tip also working. When we put cursor on username and email id view full name and email id.
