### ISSUE TITLE
Same style Radio button through out the portal

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#176]
**Links:**
- http://www.faveohelpdesk.com/demo/helpdesk/public/user/4/edit
- http://www.faveohelpdesk.com/demo/helpdesk/public/profile-edit

both these links have different style of Radio button.

**Solution:**
Use same style radio button throughout the portal

**Comment by arindam85** [comment]
fixed hand over to @SarfrazS for testing
