### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk#177]
On a previous Faveo version I could see the social icons on the main page when I activate them.
I have now activated few of them and they are not showing.

**Comment by vijaysebastian** [comment]
We have changed database structure. So please delete widget table from your database and import this attached file
[widgets.txt](https://github.com/ladybirdweb/faveo-helpdesk/files/432697/widgets.txt).
In our new version we have seeding for this table. But unfortunately, in update database dumb we haven't included. Sorry....

**Comment by francesco1119** [comment]
mmm... I just can import SQL, XML, CSV, MediaWiki Tables, OpenDocument Spreadsheet, ESRI Shape File
I'm using PHPMyAdmin. 
I've tried to import using CSV following some guide but it created a nonsense table

**Comment by vijaysebastian** [comment]
Copy the content from widgets.txt file >> open PHPMyAdmin >> open your database >> click on SQL on top navigation >> paste the content >> click ok
![screen shot 2016-08-24 at 11 40 25 am](https://cloud.githubusercontent.com/assets/10737619/17920089/de4cb268-69ef-11e6-8742-bd67795ce736.png)

**Comment by francesco1119** [comment]
now my [website ](http://faveo.jeeja.biz/public)has got your footer?!

**Comment by francesco1119** [comment]
Understood, I can edit this from widget. Fixed

**Comment by vijaysebastian** [comment]
Open Admin panel >> Social and check can you see 
![screen shot 2016-08-24 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/10737619/17920535/c57af486-69f2-11e6-87da-6374e85fa3b2.png)

**Comment by francesco1119** [comment]
I cannot see them in the main page of my site? Where should they be?

**Comment by vijaysebastian** [comment]
Login as an admin click on admin panel. Here you can see a block called widgets; From there choose social

**Comment by bhanu2217** [comment]
You need to enter the url in the admin panel, once you have entered the url they will show in the footer of the website here http://faveo.jeeja.biz/public/

**Comment by francesco1119** [comment]
No, they are not in the footer once I add the URL, I remember this was working on a previous version of Faveo

**Comment by francesco1119** [comment]
I now have it: I can see the social icons for Chrome and IE but not for FireFox!

**Comment by bhanu2217** [comment]
I can see the icons in all browsers including firefox
