### ISSUE TITLE
Ticket - Inline image mail issue

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#179]
**Link:** http://ladybirdweb.com/support/thread/1981

This ticket has inline images in the email/ticket

**Issue:**
When this ticket creation notification goes to agent's email the body of email instead of images has broken HTML

**Comment by SarfrazS** [comment]
I m trying to test above issue But today cron is not working so i will check tomorrow.

**Comment by bhanu2217** [comment]
@SarfrazS What is the status on this issue?
