### ISSUE TITLE
Ticket Assignment to a team doesn't show only Agents shows

### ISSUE THREAD

**Issue by dirlanda** [ladybirdweb/faveo-helpdesk#1811]
- Faveo Version : 1.10.6
- PHP version : 7.1.28
- Database Driver & Version : mysql 
- Server specification : windows 10 - xampp

#### Description:
HELLO,

i have 3 teams active suppor1 , support2 , developers each team with 2 agents and 1 chief when i want to assign a ticket i click in assign they show me lists of agents of all the teams logically i need to assign the ticket to agents of the team i choice. look to the picture.

i don't now if this a issue or not but I hope you help me to fix it or i need to activate something to show me the list of teams not agents 

Thank you

![Capture000](https://user-images.githubusercontent.com/19295129/56843916-64199e00-689f-11e9-890d-fb314bb4c06e.PNG)

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by dirlanda** [comment]
Any help !!

**Comment by mverma16** [comment]
The teams will only appear in the dropdown if there is a team leader assigned to them.
