### ISSUE TITLE
Ticket Internal note

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#184]
When an internal note is posted the success message is "You can successfully replied to your ticket" This should be changed to "Internal note added to the ticket"

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC. Internal note replied showing only agent panel.

**Comment by mverma16** [comment]
@SarfrazS please try to understand the statement of issues before testing and closing them. BTW I've fixed the issue.
