### ISSUE TITLE
Select all check box is not working

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#185]
As an agent when I open client's profile I can see all the tickets created by the client. In that table there's once checkbox to select all tickets. which does not work.
![4](https://cloud.githubusercontent.com/assets/10759797/17919837/e53d3a04-69ed-11e6-88cb-96c32aee2df1.PNG)

Also when I move to "closed" tab it shows "close" button which should not be there as I am seeing the list of closed tickets. 
![5](https://cloud.githubusercontent.com/assets/10759797/17919896/816bf8ac-69ee-11e6-9539-722366ed5c18.PNG)

**Comment by SarfrazS** [comment]
@sujitprasad12 ,
I have tested in version 1.0.7.9.1 not working.

**Comment by mverma16** [comment]
@arindam85 has solved the issue and it's working in [v1.0.8.0](https://github.com/ladybirdweb/faveo-helpdesk/releases/tag/v1.0.8.0)
