### ISSUE TITLE
Security page error| Link access errors

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#186]
I believe [this link](http://www.faveohelpdesk.com/demo/helpdesk/public/security) is accessible by authenticated admin users only. But when I am not authenticated and try to open this link it gives me 500 error. Test and try all the links for following cases
- Links that are accessible by non-authenticated users
- Links that can only be accessed by authenticated users
- Links that can only be accessed by agents
- Links that can only be accessed by admins

Team make a list of such routes and prepare the sheet for a tester,
@SarfrazS  please understand this scenario and test the whole system for this error.

**Comment by bhanu2217** [comment]
Can we display more meaningful error message in case someone is opening a page they are not authorized to open?
