### ISSUE TITLE
For some reason your reply was not posted

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk#187]
This is the banner I receive every time I try to reply to a ticket 
```
Alert!
For some reason your reply was not posted. Please try again later
```

**Comment by francesco1119** [comment]
![screenshot from 2016-08-25 21 14 39](https://cloud.githubusercontent.com/assets/3397477/17963549/3223ca0a-6b0a-11e6-8f79-39acda4ae5ce.png)

**Comment by SarfrazS** [comment]
Hi Francesce,

Please update database from 1.0.7.8 to 1.0.7.9

https://github.com/ladybirdweb/faveo-helpdesk/wiki/Manual-Upgrade-from-v1.0.7.8-to-v1.0.7.9

**Comment by francesco1119** [comment]
Done thank you

**Comment by SarfrazS** [comment]
Is it working or not? If it is working then you may close the issues.
