### ISSUE TITLE
2 bugs in files

### ISSUE THREAD

**Issue by smazelerat-insita** [ladybirdweb/faveo-helpdesk#19]
Hi,

I recently installed the solution and have fix two issues:

1. In file app/Http/Controllers/Agent/helpdesk/TicketController.php on line 33
Change 
`use App\Model\Helpdesk\Manage\Sla_plan;`
by
`use App\Model\helpdesk\Manage\Sla_plan;`

2. In file app/Http/Controllers/Agent/helpdesk/MailController.php on line 88
Change 
`$overview = $mailbox->get_overview($mailId);`
by
`$overview = $mailbox->getMailsInfo(array($mailId));`

**Comment by sujit223** [comment]
We have fixed this issue
