### ISSUE TITLE
Knowledge base category list error

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#190]
When in client panel user try to open categories of the articles it shows 500 error page.
check this [link](http://www.ladybirdweb.com/support/category-list).
It's working fine when there was not any article listed under any category but when I added articles, it started throwing error page.

**Comment by vijaysebastian** [comment]
This is a bug; that we have fixed but somehow came back 

solution : 

Locate : resources >> views >> themes >> default1 >> client >> kb >> article-list >> categoryList.blade.php 

find this code 
`$article = App\Model\kb\Article::where('id', $id)->get();`
`$article = $article->where('status', 1);`
`$article = $article->where('type', 1);`
` $article = $article->orderBy('publish_time','desc');` 

change with 
` $article = App\Model\kb\Article::where('id', $id);`
`if (!Auth::user() || Auth::user()->role == 'user') {`
` $article = $article->where('status', 1);`
`$article = $article->where('type', 1);`
`  }`
`$article = $article->orderBy('publish_time', 'desc');`
`$article = $article->get();`

**Comment by bhanu2217** [comment]
Please push the code to development branch/fork on  Community & Pro version both
