### ISSUE TITLE
Show my tickets also in inbox if assigned to  user

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk#191]
If a ticket is from different department assigned to a user of different department then the assigned tickets are showing only under mytickets but not on inbox.
The inbox tickets should include all the tickets related to the user that the user can access.

**Comment by mverma16** [comment]
Done.

**Comment by SarfrazS** [comment]
Assigned Tickets showing under mytickets as well as inbox.
