### ISSUE TITLE
InvalidArgumentException in GET /faveo-servicedesk-community/public/_debugbar/open

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#1915]
## Error in Faveo Community

**InvalidArgumentException** in **GET /faveo-servicedesk-community/public/_debugbar/open**
View [themes.default1.agent.helpdesk.dept-ticket.open] not found.

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5cce5dde8debb20019a58193?event_id=5cce5dde0038cdf9eaa20000&i=gh&m=ci)

## Stacktrace

    \app\Http\Controllers\Agent\helpdesk\TicketController.php:2004 - App\Http\Controllers\Agent\helpdesk\TicketController::deptopen
    \app\Http\Middleware\Authenticate.php:54 - App\Http\Middleware\Authenticate::handle
    \app\Http\Middleware\CheckUpdate.php:35 - App\Http\Middleware\CheckUpdate::handle
    \app\Http\Middleware\LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5cce5dde8debb20019a58193?event_id=5cce5dde0038cdf9eaa20000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 and custom tags from forked repositories will not checked as chances of them being already fixed in the newer versions are most likely and users are encouraged to update their system.
