### ISSUE TITLE
Customer to choose priority

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#195]
Build an admin panel option where customer can select the priority of ticket while creating ticket from client panel, By default this is disabled. Incase admin wants to enable it

**Comment by arindam85** [comment]
fixed,hand over to manish......

**Comment by bhanu2217** [comment]
**Change the URL:** http://ladybirdweb.com/support/ticket_priority
remove underscore

**Change the heading** 
**Current:** User Priority Status
**New:** Show priority in create ticket form

Put a tool tip here
**Content:**  If active user can select the priority while creating ticket

**Comment by bhanu2217** [comment]
**Change Default Priority Colors:**
Current default colours in the system are not sooting to the eye.

**Make these colours as default:**
- Blue: 00c0ef
- Red: dd4b39
- Green: 00a65a
- Yellow: f39c12

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC.  Admin panel option where customer can select the priority of ticket while creating ticket from client panel, By default this is disabled. Incase admin wants to enable it
