### ISSUE TITLE
UnexpectedValueException in GET /servicedesk/

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#1950]
## Error in Faveo Community

**UnexpectedValueException** in **GET /servicedesk/**
The stream or file "C:\inetpub\wwwroot\faveo-servicedesk-community\storage/logs/laravel-2019-05-09.log" could not be opened: failed to open stream: Permission denied

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5bec61783554ee001a228a3d?event_id=5cd39e340039e0d33bd60000&i=gh&m=ci)

## Stacktrace

    \app\Exceptions\Handler.php:56 - App\Exceptions\Handler::report
    \app\Http\Middleware\LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5bec61783554ee001a228a3d?event_id=5cd39e340039e0d33bd60000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by syaiful1254** [comment]
im sorry can you help me to fi it https://github.com/ladybirdweb/faveo-helpdesk/issues/1935
please, thanks
