### ISSUE TITLE
Illuminate\Database\QueryException in GET /shipmentadd

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#1956]
## Error in Faveo Community

**Illuminate\Database\QueryException** in **GET /shipmentadd**
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'shipment_duty' cannot be null (SQL: insert into `shipments` (`agent_id`, `shipment_type`, `shipment_duty`, `BL`, `ETD`, `ETA`, `ATD`, `ATA`, `POL`, `POD`, `shipment_company`, `operator_id`, `updated_at`, `created_at`) values (13, 3, , 988-87224863, 2019/03/16, 2019/03/19, , , , ,  OZ970 , 5, 2019-05-09 13:51:41, 2019-05-09 13:51:41))

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5cd4306d67b84b0018bdaf5d?event_id=5cd4306d0039c63cf0210000&i=gh&m=ci)

## Stacktrace

    app/Model/helpdesk/Shipments/Shipments.php:22 - App\Model\helpdesk\Shipments\Shipments::save
    app/Http/Controllers/Agent/helpdesk/ShipmentController.php:283 - App\Http\Controllers\Agent\helpdesk\ShipmentController::shipment_save
    app/Http/Controllers/Agent/helpdesk/ShipmentController.php:236 - App\Http\Controllers\Agent\helpdesk\ShipmentController::shipmentadd
    app/Http/Middleware/Authenticate.php:54 - App\Http\Middleware\Authenticate::handle
    app/Http/Middleware/LanguageMiddleware.php:33 - App\Http\Middleware\LanguageMiddleware::handle
    app/Http/Middleware/VerifyCsrfToken.php:33 - App\Http\Middleware\VerifyCsrfToken::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5cd4306d67b84b0018bdaf5d?event_id=5cd4306d0039c63cf0210000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 and custom tags from forked repositories will not checked as chances of them being already fixed in the newer versions are most likely and users are encouraged to update their system.
