### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#2]
Do you have a roadmap for new features and an ETA for them ?
This is a really interesting product.

**Comment by bhanu2217** [comment]
We are working continuously on this product.
By next week we will be able to release a stable, fully working version of this product.
We also plan to put up User manual by next week and Versions for softaculous & Fantastico will follow very soon.

**Comment by guestisp** [comment]
Ok, I looking forward to hearing from you. We would like to start to develop on this.

Any ETA for APIs and mail parse? (if scheduled, RESTFul APIs would be better)

What do you mean with the organization feature? Would be possible to create multiple helpdesks based on organizations ?

**Comment by bhanu2217** [comment]
Organisation means you can see all users who raised tickets from particular organisation. You can assign a account manager for a organisation. You can search tickets, users based on organisation name.

Regarding ETA & API we will need some more time. Right now our focus is to come up with fully working edition of the product with a self installer build with capabilities for future update notifications.

**Comment by guestisp** [comment]
Do you think to release a stable version this week ?

**Comment by guestisp** [comment]
BTW please publish a roadmap so that other developers could start integrating without interfere with your works. Doens't make sense to develop the same things in two.

**Comment by bhanu2217** [comment]
Please check Roadmap here https://github.com/ladybirdweb/faveo-helpdesk

**Comment by guestisp** [comment]
Thank you. Just a question: is automated mail parsing already supported?

**Comment by bhanu2217** [comment]
Yes it is. Basic Ticket based support system is already functional including mail parsing, we are right now fixing bugs and checking if all the tabs, buttons are working and nothing is missed out and whatever is missed out on finishing that.

Though i am not sure if we have latest code posted on Github, it will take us a while to post latest code here.

We will be doing next update on Github only once we have a stable version ready

**Comment by guestisp** [comment]
Ok.
So, mail parsing is working for creating ticket and replying from agent and customers? 

We'll wait for a stable version posted on github to bring this in production on our environment.

But, why don't you push on github on regular basis ? You could use GH as git server thus allowing developers to stay always updated

**Comment by bhanu2217** [comment]
Yes mail Parsing is working for creating tickets and replying.

Regarding involving Developers:
We are still in very initial phases, our focus is more right now on the end users who can start using our application. Where we start getting feedback and improve the product further.

We would like to come out with a Developer manual(Codex), video tutorials and refine the code further, so it's easy for developer to understand & contribute to this code & use it in their application. It will still take us few months to reach at this stage.

After we have first fully working version ready we will push more often. Before the end of this month we will release the first fully working version.

Thank You.

**Comment by guestisp** [comment]
Any new code update? I've seen just a couple of commit... A stable version was planned for September...

**Comment by sujit223** [comment]
please have a check the current version is a stable one

**Comment by guestisp** [comment]
Ok, will try.
Won't you fix the directory structure as per my PR #5 ?

**Comment by guestisp** [comment]
Another question: is multibrand available or supported? For example, we would like to configure 2 different brands, with different agents, departments and support email. Is this possible or we have to use two different faveo installations ?

**Comment by sujit223** [comment]
Here we have separate departments for different types of agents. 
And an agent of one department cannot access tickets of other unless he is an admin.
You can use the department separation for multi brands.
But for more precise answer we don't have multi brand feature at this moment. We are currently working on making this current version more perfect. Later we will be working on making multiple functionality. And we are strictly following our road map.

**Comment by guestisp** [comment]
we can't use departments as we need many departments for each brand, i.e: "brand1 sales", "brand1 tech", "brand2 sales", "brand2 tech"

**Comment by sujit223** [comment]
We might look into this Idea. But currently we are focused with our roadmap.

**Comment by guestisp** [comment]
In requirements you wrote that PHP 5.5 is needed but you are using Laravel 5.0 that is compatible with PHP 5.4.

Is 5.5 really needed ?

**Comment by sujit223** [comment]
Yes 5.5 is really need. We keep using classes from composers. Due to which some classes are more updated than Laravel 5. And so these classes mostly require php 5.5.

**Comment by guestisp** [comment]
Any new release?

**Comment by bhanu2217** [comment]
We will be releasing new version by end of this week.
