### ISSUE TITLE
Console Kernal has bad code

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#201]
https://github.com/ladybirdweb/faveo-helpdesk/blob/master/app/Console/Kernel.php

Line 33

There is a schedule to create a new user every 5 minutes. This is causing an error every 5 minutes since the class is not being called to 'use' before hand. But either way, production faveo shouldn't make a user every 5 minutes. :)

**Comment by vijaysebastian** [comment]
We have changed
