### ISSUE TITLE
ErrorException in POST /service/public/help-topic-pdf

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#2037]
## Error in Faveo Community

**ErrorException** in **POST /service/public/help-topic-pdf**
Undefined offset: 1 (View: /home/alfajerfm/public_html/service/resources/views/themes/default1/agent/helpdesk/report/pdf.blade.php)

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5ce52af13077fa0018603384?event_id=5ce52af10039eda0586d0000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Agent/helpdesk/ReportController.php:263 - App\Http\Controllers\Agent\helpdesk\ReportController::helptopicPdf
    app/Http/Middleware/CheckRoleAgent.php:25 - App\Http\Middleware\CheckRoleAgent::handle
    app/Http/Middleware/Authenticate.php:54 - App\Http\Middleware\Authenticate::handle
    app/Http/Middleware/CheckUpdate.php:35 - App\Http\Middleware\CheckUpdate::handle
    app/Http/Middleware/LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5ce52af13077fa0018603384?event_id=5ce52af10039eda0586d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 and custom tags from forked repositories will not checked as chances of them being already fixed in the newer versions are most likely and users are encouraged to update their system.
