### ISSUE TITLE
Team and Agent are inactive but still it showing in ticket assign page.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#206]
When we are open ticket and go to assign button Team and Agent are inactive but still showing on that assign page and also we can assign with inactive agent.please check and fix it.

**Comment by arindam85** [comment]
fixed ...i will hand over to manish

**Comment by SarfrazS** [comment]
I tested in v1.0.8.RC it's working. Only active agent showing over there.
