### ISSUE TITLE
Help topic custom form not working

### ISSUE THREAD

**Issue by stevieg83** [ladybirdweb/faveo-helpdesk#207]
I've set a new help topic and assigned a custom form to that topic but when I change the subject from `/create-ticket` nothing changes

**Comment by wittie** [comment]
Do we have updates on this issue?

Thank you

**Comment by jakobii** [comment]
It appears the the custom form is supposed to change the questions asked when someone goes to update the ticket, although I have as of yet to see the purpose for the 'custom forms' area in the admin panel.

Between Custom Forms and HTTPS support this application would be almost perfect, in my opinion.

**Comment by bhanu2217** [comment]
**How Custom forms currently works**
- Custom forms are linked to help topic
- Different forms can be created for different help topic
- When a help topic is selected based on that if there is any custom form linked to that help topic it is shown on the create ticket page

**Custom form in coming releases**
- We are looking at some nice form builder scripts which we can integrate, so it makes it easy to create custom forms

**Future of Help topics**
- Help topics will be removed from system
- Multiple level department will be available
- Custom form will be linked to department.
- Eventually custom form will be enhanced further and even the default form can be changed and custom forms can be linked with anything in the form, this might take longer

**Comment by bhanu2217** [comment]
@vijaysebastian Please provide fix for this today

**Comment by vijaysebastian** [comment]
@stevieg83 Which Faveo version  you are using ?

**Comment by vijaysebastian** [comment]
We have fixed form related issue in 1.0.8.0 which will release this week

**Comment by wittie** [comment]
Hi Team,
Im using Version Community 1.0.7.9.1

I really like the software its user friendly even without reading the manual or wiki.

Thank you

**Comment by vijaysebastian** [comment]
@wittie we have released 1.0.8.0. With new exciting features and bug fixes, Please try and send your feedback

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC  now it's working.
