### ISSUE TITLE
Extension zip

### ISSUE THREAD

**Issue by raisiqueira** [ladybirdweb/faveo-helpdesk#208]
Error — Extension 'zip' is required in order to run Faveo Helpdesk

I have installed php7.0-zip and show this error!

**Comment by mverma16** [comment]
Hello @raisiqueira, 
Faveo requires PHP zip extension to handle processing of zip files. Faveo checks various extensions  are enabled or not while installation. You can check if this extension is enabled or not using phpinfo(). Please refer [this link](http://php.net/manual/en/book.zip.php) to read more about zip extension and how to enable it.
Hope that will solve your problem.

**Comment by jakobii** [comment]
has anyone figured out a solution to this problem yet?

**Comment by jakobii** [comment]
This is what i did to get it working, hopefully this is all that i did to get it to work i kinda spammed c/p and google. I'm going to rebuild the server anyway and will update otherwise:

-ububtu 16.04-
sudo apt install php5.6-zip
phpenmod zip
nginx -s reload
