### ISSUE TITLE
NGINX/PHP-FPM Config Files 

### ISSUE THREAD

**Issue by brianjking** [ladybirdweb/faveo-helpdesk#209]
Hello,

Can you please provide me with a NGINX Configuration for CentOS 6.8? The files linked in http://www.ladybirdweb.com/support/show/how-to-install-faveo-helpdesk-on-centos-6 seem to be broken.

I checked the CentOS 7, Ubuntu and others at the Faveo KB and they all appear to be broken.

Thanks!

**Comment by brianjking** [comment]
This is the command I'm referencing: 

````
wget -O /etc/nginx/conf.d/faveo-helpdesk.conf http://ladybirdweb.com/support/uploads/centos6/nginx-config.txt
````

**Comment by bhanu2217** [comment]
@brianjking This NGINX config file is created by @mathieu-aubin 

@mathieu-aubin Can you please help on this

**Comment by brianjking** [comment]
Thanks @bhanu2217. Hope to hear back from @mathieu-aubin on this.

**Comment by mathieu-aubin** [comment]
Hi, yes it's broken because i'm no longer hosting the files required due to some issues regarding copyright. What are your needs

**Comment by brianjking** [comment]
@mathieu-aubin @bhanu2217 I got it resolved, the standard Laravel NGINX config I was using wouldn't work until I set my `document root` to include the `public` directory.

On this server I use nDeploy (https://github.com/AnoopAlias/nDeploy) to use NGINX & PHP-FPM directly instead of Apache on cPanel. This is the config that I was able to get working:

````
root DOCUMENTROOT;
index index.php index.html index.htm;



location / {
        try_files $uri $uri/ /index.php?$query_string;
}

location /NaxsiRequestDenied {
       return 418;
   }

location ~ ^/pingphpfpm$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:SOCKETFILE;
}

location ~* /\.(?!well-known\/) { deny all; access_log off; log_not_found off; }


location ~ \.php$ {
    #NAXSI_INCLUDE_FILE;
    #NAXSI_DOMAIN_WHITELISTS;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
	try_files $uri /index.php =404;
    fastcgi_pass unix:SOCKETFILE;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
}

include /etc/nginx/conf.d/cpanel_services.conf;
````
