### ISSUE TITLE
KB : Error after adding some categories

### ISSUE THREAD

**Issue by acs-ferreira** [ladybirdweb/faveo-helpdesk#212]
After adding some categories, i have this error while trying to browse Category List (`/category-list`) on the Frontend:

`BadMethodCallException in Macroable.php line 74: Method orderBy does not exist.`

`ErrorException in Macroable.php line 74: Method orderBy does not exist. (View: /resources/views/themes/default1/client/kb/article-list/categoryList.blade.php)`

**Comment by vijaysebastian** [comment]
We have fixed this, In next release you will get fix
