### ISSUE TITLE
postconnection ajax post not working during install

### ISSUE THREAD

**Issue by StevenFlecha** [ladybirdweb/faveo-helpdesk#214]
I'm getting this error:

2016/09/12 10:45:35 [error] 6510#6510: *50 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught DaveJamesMiller\Breadcrumbs\Exception: Breadcrumb not found with name "postconnection" in /srv/faveohelpdesk/vendor/davejamesmiller/laravel-breadcrumbs/src/Generator.php:20
Stack trace:
#0 /srv/faveohelpdesk/vendor/davejamesmiller/laravel-breadcrumbs/src/Generator.php(13): DaveJamesMiller\Breadcrumbs\Generator->call('postconnection', Array)
#1 /srv/faveohelpdesk/vendor/davejamesmiller/laravel-breadcrumbs/src/Manager.php(90): DaveJamesMiller\Breadcrumbs\Generator->generate(Array, 'postconnection', Array)
#2 /srv/faveohelpdesk/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): DaveJamesMiller\Breadcrumbs\Manager->render()
#3 /srv/faveohelpdesk/storage/framework/views/6f9cff77afa4a2566be34ce25ee9ff1f46784ae4.php(203): Illuminate\Support\Facades\Facade::__callStatic('render', Array)
#4 /srv/faveohelpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/srv/faveohelpd...')
#5 /srv/faveohelpdesk/vendor/laravel/framewo...

**Comment by mverma16** [comment]
@StevenFlecha can I know the FAVEO version you are trying to install and the step in which you got the error.

**Comment by mverma16** [comment]
@StevenFlecha please try to install the latest version without dummy-data and open the issue if it is not solved.
