### ISSUE TITLE
Duplicate setting options for Auto response?

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#215]
There is an option to disable auto response when we configure a mail in the system (but it's particularly for that email) see the image
![1](https://cloud.githubusercontent.com/assets/10759797/18575646/c90adcc6-7bf7-11e6-84f1-d403863e3fe7.png)

Also in settings there is an option for Auto response settings
![2](https://cloud.githubusercontent.com/assets/10759797/18575657/ec3d8496-7bf7-11e6-8e1c-8b4eaecfc66d.png)

I am getting confused with the working of these two options. Please can you explain how they both are working and are they duplicate?

**Comment by sujitprasad12** [comment]
**The first option is for disabling auto response at particular email level.** 
            **Scenario**:- _There are some emails that are set for receiving server status via emails. But don't want to populate their server emails with new ticket created emails. And server email status are set every hour. This was a requirement too._
**The second option is for disabling at global level so that no emails send emails/ auto response.**
           **Scenario:-** _If some one wants to disable at global level._

**Comment by mverma16** [comment]
Sounds legit. Thanks.
