### ISSUE TITLE
Problem installing faveo helpdesk in windows server

### ISSUE THREAD

**Issue by ddneogy-webhawks** [ladybirdweb/faveo-helpdesk#216]
I am trying to install faveo helpdesk in the website 'mytraveldesk.in/holiday-uat' which is in a windows server. I have downloaded the faveo package from github and extracted the package in a folder 'mtdsupport' in our project 
root. Then I ran it and entered database connection details etc. successfully. But after completing 5 steps when I am in Step 6  (link 'http://www.mytraveldesk.in/holiday-uat/mtdsupport/public/index.php/step6post') , it is showing error that the www.mytraveldesk.in page isn’t working.

![faveo](https://cloud.githubusercontent.com/assets/22235732/18583714/d4a26c70-7c29-11e6-9a5d-40638e23230f.png)
Kindly help me to fix this.

**Comment by ddneogy-webhawks** [comment]
I have checked the version in release-notes.txt file . It is v1.0.7.9 R.C.

**Comment by ddneogy-webhawks** [comment]
I just have downloaded a new copy of faveo helpdesk from this link 'https://github.com/ladybirdweb/faveo-helpdesk/'. This this also showing  v1.0.7.9 R.C.

**Comment by bhanu2217** [comment]
Is there any error log on your server, can you check and see if any error was recorded in error log

**Comment by ddneogy-webhawks** [comment]
Where can I find the error log?

**Comment by bhanu2217** [comment]
Difficult to say exact location, as it differ from server to server. Probably in the root directory. @SarfrazS Can you also check once and see what is the issue

**Comment by mverma16** [comment]
@ddneogy-webhawks  can you tweak a code? You just need to make some change in one file and try the installation process again. It will show the error

**Comment by ddneogy-webhawks** [comment]
What is the name of the error log file?

**Comment by mverma16** [comment]
you can check logs in [your project folder]/storage/logs/*.log files. 

Also you can try this
Open [your project folder]/app/Exceptions/Handlers.php   add **dd($e);** on 154 before swtich() statement. Try to install the system again and you'll get the exact error which you can share.

**Comment by ddneogy-webhawks** [comment]
My Handlers.php looks like this:

`
namespace App\Exceptions;

use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that should not be reported.
     *
     * @var array
     */
    protected $dontReport = [
        \Symfony\Component\HttpKernel\Exception\HttpException::class,
    ];

    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Exception  $e
     * @return void
     */
    public function report(Exception $e)
    {
        return parent::report($e);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        return parent::render($request, $e);
    }
}
`
Where will I add dd($e) ?

**Comment by mverma16** [comment]
please update Your project directory/app/Exception/Handler.php file with this [file](https://github.com/ladybirdweb/faveo-helpdesk/blob/master/app/Exceptions/Handler.php).
add dd($e) on line number 154 in "common" function.

**Comment by ddneogy-webhawks** [comment]
I have updated the Handler.php file and added the dd($e) as you told. Then when I ran it, Yes, It is installed. But links are not working. These are redirecting to a 404 page. Probably due to .htaccess problem due to windows server. You can check it in 'http://www.mytraveldesk.in/holiday-uat/testfaveo/public/' Can you help me to solve this problem.
