### ISSUE TITLE
Swift_TransportException in GET /public/sendmails

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#2196]
## Error in Faveo Community

**Swift_TransportException** in **GET /public/sendmails**
Connection could not be established with host smtp.gmail.com [ #0]

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5d1224e3d35c910018cb8d38?event_id=5d1224e300461c5782f10000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Common/PhpMailController.php:302 - Illuminate\Support\Facades\Mail::send
    app/Http/Controllers/Common/PhpMailController.php:302 - App\Http\Controllers\Common\PhpMailController::laravelMail
    app/Http/Controllers/Common/PhpMailController.php:185 - App\Http\Controllers\Common\PhpMailController::sendEmail
    app/Http/Controllers/Common/PhpMailController.php:75 - App\Http\Controllers\Common\PhpMailController::sendmail
    app/Http/Controllers/Agent/helpdesk/MailController.php:510 - App\Http\Controllers\Agent\helpdesk\MailController::sendmails
    app/Http/Middleware/CheckBoard.php:27 - App\Http\Middleware\CheckBoard::handle
    app/Http/Middleware/LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5d1224e3d35c910018cb8d38?event_id=5d1224e300461c5782f10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 will not checked as chances of them being already fixed in the newer versions are most likely and users are encouraged to update their system.
