### ISSUE TITLE
ErrorException in GET /ticketing/public/ticket/open

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#2210]
## Error in Faveo Community

**ErrorException** in **GET /ticketing/public/ticket/open**
SQLSTATE[HY000] [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 (View: D:\xampp\htdocs\ticketing\resources\views\themes\default1\client\layout\client.blade.php) (View: D:\xampp\htdocs\ticketing\resources\views\themes\default1\client\layout\client.blade.php)

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/58de0e44d6dd78180041cc7d?event_id=5d133afb0045f64a84be0000&i=gh&m=ci)

## Stacktrace

    \app\Exceptions\Handler.php:97 - App\Exceptions\Handler::render500
    \app\Exceptions\Handler.php:175 - App\Exceptions\Handler::common
    \app\Exceptions\Handler.php:77 - App\Exceptions\Handler::render
    \app\Http\Middleware\LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/58de0e44d6dd78180041cc7d?event_id=5d133afb0045f64a84be0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 will not checked as chances of them being already fixed in the newer version are most likely and users are encouraged to update their system.
