### ISSUE TITLE
Illuminate\Database\QueryException in GET /public/tat

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#2214]
## Error in Faveo Community

**Illuminate\Database\QueryException** in **GET /public/tat**
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket_live.tat_definition' doesn't exist (SQL: select `tat`.`id`, `o`.`name` as `org_name`, `d`.`name` as `dept_name`, `h`.`topic` as `cat_name`, `tbo`.`name` as `base_on_name`, `tat`.`warning_per`, `tat`.`response_time_sec`, `tat`.`status` from `tat_definition` as `tat` inner join `organization` as `o` on `o`.`id` = `tat`.`org_id` left join `department` as `d` on `d`.`id` = `tat`.`dept_id` left join `help_topic` as `h` on `h`.`id` = `tat`.`help_topic_id` inner join `tat_based_on` as `tbo` on `tbo`.`id` = `tat`.`tat_based_id`)

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5d135d463bab480019549fd2?event_id=5d135d4600460895ef1b0000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Agent/helpdesk/TatController.php:26 - App\Http\Controllers\Agent\helpdesk\TatController::tatDefinition
    app/Http/Middleware/Authenticate.php:54 - App\Http\Middleware\Authenticate::handle
    app/Http/Middleware/CheckUpdate.php:35 - App\Http\Middleware\CheckUpdate::handle
    app/Http/Middleware/LanguageMiddleware.php:21 - App\Http\Middleware\LanguageMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5d135d463bab480019549fd2?event_id=5d135d4600460895ef1b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Issues reported in version older than v1.9.6 will not checked as chances of them being already fixed in the newer version are most likely and users are encouraged to update their system.
