### ISSUE TITLE
Leaving a reply error

### ISSUE THREAD

**Issue by ningmu** [ladybirdweb/faveo-helpdesk#223]
Hi there,

A client check the status of his ticket. He received a message on his inbox with a subject Ticket Link Request [ticket code]. And on the body of email, a URL but no hyperlink. So the client just copy paste the url on his browser. 

The series of conversation of the said ticket did show up, But when he attempted to reply on it, he always received this error: (see image)

![reply-error](https://cloud.githubusercontent.com/assets/22490393/18901995/0da15e76-8582-11e6-8939-8b20eef7d391.jpg)

Did you experience this guys? How do you fix this?

Thanks!

**Comment by ningmu** [comment]
Any updates? Can't still use them till now..

**Comment by mverma16** [comment]
@ningmu what's the status on this issue after system update, is it working now?
