### ISSUE TITLE
Email ticketing issue

### ISSUE THREAD

**Issue by veeraj-john** [ladybirdweb/faveo-helpdesk#2259]
- Faveo Version : 1.10.6
- PHP version : 7.2
- Database Driver & Version : mysql 5.6.43-cll-lve
- Server specification :
Godaddy Shared hosting (ultimate package)
cPanel Version | 78.0 (build 27)
Apache Version | 2.4.39
MySQL Version | 5.6.43-cll-lve
Architecture | x86_64
Operating System | linux
Perl Version | 5.10.1

#### Description:
I Dont know what am doing wrong. But any tickets created from gmail, yahoo, hotmail are not coming to the system. However, the email tickets created from the same domain emails are working fine. 

#### Steps To Reproduce:
I Havent done anything much.
1) Installed the application like said.
2) configured the email settings to domain email with incoming and out going info
3) added cron job.

I DOnt understand what am missing.

#### Downloaded from
- [yes ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@veeraj-john what was wrong, were you able to fix it?
