### ISSUE TITLE
Profile picture issue

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#241]
Even if user(client) uploads a profile picture, it is not showing in his profile when an agent or admin views his/her profile.
see this client has uploaded a profile picture for his account

![2](https://cloud.githubusercontent.com/assets/10759797/19379441/a4f66732-920f-11e6-9644-7a23a2c2d343.png)

but when any admin/agent user opens this user's profile it loads gravatar
![3](https://cloud.githubusercontent.com/assets/10759797/19379530/00fe43ce-9210-11e6-84a1-d3344daf3d74.PNG)

In notification it shows picture of the user's own profile picture.
![1](https://cloud.githubusercontent.com/assets/10759797/19379643/a36bf598-9210-11e6-8a4f-c2a2a945bce5.PNG)

 Need to enhance notifications along with [this issue](https://github.com/ladybirdweb/faveo-helpdesk/issues/237).

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC Client  profile picture showing fine.

**Comment by mathieu-aubin** [comment]
cache issues?
