### ISSUE TITLE
Faveo-Helpdesk Auto Install is not working. Ubuntu 16.04

### ISSUE THREAD

**Issue by derek68** [ladybirdweb/faveo-helpdesk#242]
Hi All

I have just installed Ubuntu 16.04.1 LTS Release 16.04 Codename xenial.
I in trying to install faveo using terminal and the following install script and its not working.

bash <(curl -s http://ladybirdweb.com/support/uploads/ubuntu16.04/autoinstall)

I am getting the following error.

/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1:`<!DOCTYPE html>'

Can anyone please let me know how to fix this error.

Regards

Derek

**Comment by bhanu2217** [comment]
@SarfrazS Please see that this file exists on the server

**Comment by derek68** [comment]
Hi SarfrazS,

Thank you for the response, but what file?

Regards


Derek

**Comment by SarfrazS** [comment]
Hi Derek68,

Please go through this link and follow the steps.
http://ladybirdweb.com/support/show/how-to-install-faveo-helpdesk-on-ubuntu-1604-xenial-lts

**Comment by alscheuring** [comment]
The autoinstall script is not available. The link is broken:
http://ladybirdweb.com/support/uploads/ubuntu16.04/autoinstall

**Comment by derek68** [comment]
Hi Alscheuring

It has been broklen for a long time, i reported it back in October of last year.   I wish it would be fixed, as FAVEO is a great programe and I would like to use it in ubuntu.  Im currently using it on a windows pc, but it will not fetch mail, as you need to make a cron job, and I have no way of doing this in windows.  So for the moment, im using osticket, it works, but its not nice like faveo.  Ive tried installing manually on ubuntu, but I cant get that to work, its a pitty as I would really would like to use FAVEO with UBUNTU.

**Comment by alscheuring** [comment]
Derek thanks for the note. I was just trying the docker container for this after failing to install it manually. That didn't work out either. Too bad. It looks nice and modern but if it's this hard to just try it out then I'll have to move on.

**Comment by derek68** [comment]
I hear you, can you please let me know what you end up with.  Faveo is great, but it will just, or I cant get it to install on ubuntu.

**Comment by mverma16** [comment]
@derek68 and @alscheuring sorry for the delay in the response, we've fixed the script's link now, please check.
I'd suggest you to check are you able to run laravel on your servers. Also you can try running [Faveo probe](https://github.com/ladybirdweb/faveo-probe) to check if your server has all the required extensions available.

**Comment by mathieu-aubin** [comment]
Hi, 
I believe i am the original creator of that script (and YES it's still working FINE)

**Comment by bhanu2217** [comment]
I have created a new repo for server images & scripts.

**Here are the details** 
https://github.com/ladybirdweb/faveo-server-images

It's not been tested for long and might have issues. It's open to public contribution & changes.
All the scripts on this page are written and contributed by @mathieu-aubin

**Comment by derek68** [comment]
Hi All

This is the error I get.

$ bash <(curl -s http://ladybirdweb.com/support/uploads/ubuntu16.04/autoinstall)
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'

So perhaps im doing something wrong.

One again, thank you for helping in advance.

**Comment by derek68** [comment]
Hi All

Can anyone please help with the install on a ubuntu 17.0, I have tried the install guide, and it simply does not work.

**Comment by nandagopalnandu** [comment]
https://github.com/ladybirdweb/faveo-helpdesk/wiki
