### ISSUE TITLE
Put the initial email text in the reply

### ISSUE THREAD

**Issue by tttp** [ladybirdweb/faveo-helpdesk#243]
Hi,

when an agent reply from faveo, the reply sent doesn't include the initial message.

We use faveo for internal help desk, ie. a single user might send quite a few requests. when she receives a reply "problem solved" without the initial request, it's hard to guess what is the reply referring to

Is there an option to add the initial request in the reply?

**Comment by mverma16** [comment]
@tttp No we don't have an option to send previous messages of thread along with reply. What I understood by your scenario is that a member of your team is addressing various problems in a single ticket and when you reply "Problem solved" it's ambiguous to know which problem you have solved.
A better solution for this would be creating different tickets for different problems as user/agent can create as many tickets as s/he wants. In this way your team will have clarity about all the pending and resolved problems(tickets).

**Comment by tttp** [comment]
No, I mean that each issue is filled as a separate ticket, but when an agent replies, the one that requested doesn't have the context of what the reply is referring too.

it's a bit like the issue tracker on github didn't give you an easy way to find the initial issue but only sent the latest comment

**Comment by mverma16** [comment]
But major mail services nest the mails with similar subject under one mail. Please see the image for better understanding
![1](https://cloud.githubusercontent.com/assets/10759797/19433129/1294125c-947d-11e6-9f2b-a07786510971.png)

So all comments on this issue created by you is coming under 

> _[ladybirdweb/faveo-helpdesk] Put the initial email text in the reply (#243)_

 when I open this I can see all comments made by you like wise when a new ticket gets created in Faveo, system sends an acknowledgement mail for ticket creation with ticket number and title as subject and ticket's initial message as its body. All the reply by agents will nest under this subject eg.

>  _Problem facing at my installation[#ADFQ-2174-0002174]_ 

Though it's not what you want but client/user will be able to read complete thread in his/her mail itself. For now I'll keep this issue open, so my team members and other Faveo users can suggest their views about it.
