### ISSUE TITLE
Full Application Link not coming in mail.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#244]
Agent or User are not getting full Link in mail.only getting domain name.Please solve this issue.

Thank You.

**Comment by bhanu2217** [comment]
@SarfrazS Can you please explain the issue more in detail and steps to recreate it?

**Comment by mverma16** [comment]
This issue has been solved and now the full URL of application is coming in the mails. Will be a part of next release.
