### ISSUE TITLE
In active Priority

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#246]
In active priority is showing in ticket edit page.
If the priority is inactive it should't show on other pages like Email setting, ticket edit page and so on
**Version:** 1.0.8.0 RC

**Comment by mverma16** [comment]
Fixed, @SarfrazS  please test and close the issue

**Comment by SarfrazS** [comment]
I have tested working fine on version 1.0.8.0 RC. only active priority showing on ticket edit page.
