### ISSUE TITLE
SLA bar background colour

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#247]
**Link:** http://ladybirdweb.com/support/thread/2215
The SLA bar had  a different background colour, which is not showing here
**Version:** 1.0.8.0 RC

**Comment by mverma16** [comment]
Issue has been solved in this [PR](https://github.com/ladybirdweb/faveo-helpdesk/pull/264/files/252c72cf2d5609265ef0547c84dbf55cafaf7ebe..296736f0923dd6bad2be81b5d0559a678aec0008) which has been merged in master.
