### ISSUE TITLE
iFrame auto height

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#248]
**Link:** http://ladybirdweb.com/support/thread/2215
The iframe height forevery reply is fixed, the auto height script doesn't seem to be working.

**Comment by mverma16** [comment]
Also if there is a hyperlink in ticket body or reply body, clicking on it in opens the link in the same iframe. Even if HTML target attribute is set to _blank it opens the link in the same iframe.

**Comment by vijaysebastian** [comment]
This problem is there, But not in "target _blank". But if it is not target _blank It is trying to open the hyper link in side iframe
