### ISSUE TITLE
Ticket source icon not showing

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#249]
Ticket source icon not showing in the inbox page.

**Link:**  http://ladybirdweb.com/support/ticket/inbox
**Version:** 1.0.8.0 RC

**Comment by mverma16** [comment]
Checked database, problem is because of incomplete database upgrade file, updating upgrade script.

**Comment by mverma16** [comment]
Check now http://ladybirdweb.com/supportlatest/ticket/inbox
