### ISSUE TITLE
Log paginaton

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#250]
The log seems very long, can we not put some pagination or something for very large log files? 

**Log Date:** 18 Oct 2016
**Version:** 1.0.8.0 RC

**Comment by vijaysebastian** [comment]
Actually we have put pagination, But i will check, what is the problem with the pagination

**Comment by mverma16** [comment]
Pagination works, first loads all logs and then render it in different pages of table. If number of logs are more than 100 then it takes time to render logs.

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC, Logs Pagination is working.
