### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#251]
**Issues:**
- The new buttons(change role, change password) UI is breaking kind in responsive, please discuss with Varsha how to improve it
- Long user name and email address is getting cut if long, atleast have like a title(tool tip) for it so someone can see full username, email
- In the delete user, there is no option to assign the user content to different user
- When changing role to admin why does it ask for group and department?
- How can the role be changed to client?
- Change password - The password generator works only one time, it should be able to work any number of times, whenever password generator is pressed new password should be generated and old in input box deleted

**Link:** http://ladybirdweb.com/support/user/223
**Version:** 1.0.8.0 RC

**Comment by arindam85** [comment]
change password,role cange to user,fixed,........
