### ISSUE TITLE
User edit profile

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#252]
- Currently saved organisation not getting selected on edit
- On edit if you choose different organisation and save it doesn't save
- Organisation list cannot be drop down but has to be auto fill search, as system can have way too many organisations
- Even the organisation assign button cannot be drop down, has to be auto fill search option.

**Link:** http://ladybirdweb.com/support/user/223/edit
**Version:** 1.0.8.0 RC

**Comment by arindam85** [comment]
Now organization edit option,auto search and select organization are working ........
