### ISSUE TITLE
Ticket Subject - Re: [your-subject]

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#253]
Ticket subject is showing as Re: [your-subject]
Have a look at original email once and see if any fix is required.

**Link:** http://ladybirdweb.com/supportlatest/thread/2219
Version: 1.0.8.0 RC

**Comment by mverma16** [comment]
Checked the mail, it has "Re: [your-subject]" as its subject.
![1](https://cloud.githubusercontent.com/assets/10759797/19517959/e73c1504-9621-11e6-9669-4cbae45575da.PNG)
