### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#256]
Click on generate pdf icon in the ticket thread, the pdf file generated has an unknown image on he pdf file on the top.

**Link:** http://ladybirdweb.com/supportlatest/genereate-pdf/8893 and http://ladybirdweb.com/supportlatest/thread/2219
**Version:** 1.0.8.0 RC

**Comment by SarfrazS** [comment]
I have checked from development branch no unknown image generated when we click on Generate PDF icon.
