### ISSUE TITLE
In User directory when we are click on delete button. After we getting wrong popup message.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#263]
Please see the following screen shot what we are getting wrong popup message. Version 1.0.8.0 RC
I want to delete user :- 

![capture](https://cloud.githubusercontent.com/assets/18435376/19635956/bb8f194a-99e3-11e6-9b00-4a92044c8dc4.PNG)

**Comment by SarfrazS** [comment]
I want to delete Agent but he has some tickets. so i again choose same agent and click on delete button
then getting this wrong popup message.
![capture1](https://cloud.githubusercontent.com/assets/18435376/19636056/610487a2-99e4-11e6-9431-00c7f4975ed5.PNG)

**Comment by SarfrazS** [comment]
I want to delete agent and what ever he has ticket, i want to assign another agent and click on delete button. After that i m getting wrong popup message.

![capture2](https://cloud.githubusercontent.com/assets/18435376/19636102/b9f6021e-99e4-11e6-804c-e18027ba1213.PNG)

**Comment by arindam85** [comment]
fixed all popup massage handover code @mverma16

**Comment by arindam85** [comment]
manish check this..
https://github.com/ladybirdweb/faveo-helpdesk/pull/264

**Comment by bhanu2217** [comment]
The English used in success messages are not proper.
@arindam85: Please check the logic, English(grammar) for everything
