### ISSUE TITLE
Tickets merge

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#27]
Ticket merging should be also done from the list, by selecting two or more tickets. A drop down menu with "Delete" "Clone" and "Merge" should be created

**Comment by bhanu2217** [comment]
Right now ticket merging is possible only for same owner tickets. If tickets needs to be merged for different owner first the ownership needs to be changed. Thank You for your feedback, we will implement it in future releases. We will simplify ticket merging in future releases 
Sent from Yahoo Mail on Android 
 
  On Sat, Mar 5, 2016 at 1:59 PM, GUEST.it<notifications@github.com> wrote:   
Ticket merging should be also done from the list, by selecting two or more tickets. A drop down menu with "Delete" "Clone" and "Merge" should be created

**Comment by guestisp** [comment]
I'm not asking for a merge between multiple owners, but in ticket list.

Here: http://www.faveohelpdesk.com/demo/ticket/inbox you should be able to merge 2 or more ticket by checking theirs checkboxes, like for deleting

**Comment by bhanu2217** [comment]
@mverma16 Please check once, i thought this was already implemented.

**Comment by sujit223** [comment]
We are looking into this issue
