### ISSUE TITLE
Qnap & Faveo-helpdesk - Imap fetching mail not working

### ISSUE THREAD

**Issue by derek68** [ladybirdweb/faveo-helpdesk#271]
Hi All

I bought myself a Qnap TS-431 nas.  I have installed Faveo and its up and working, have to say, im very impressed with the helpdesk software so far.  The only issue im having, is that faveo is not receiving mail and creating tickets.  I have configured mail and Faveo confirms that my mail settings are correct.  I can send mail, but just not receive mail.  Can anyone please help me out?  OSticket, is also installed on the same Qnap server and it is receiving and sending mail fine.  So im guessing that I might have a setting in Faveo that I have set correctly.  FAVO version is Version Community 1.0.7.9.1.

Regards

Derek

**Comment by mverma16** [comment]
Hi @derek68,
Seems like you have not set up the cron on your server to read mails from your configured mail. But to be sure please follow these steps:

1. Go to admin panel>settings>cron
2. There you'll find following links for cron job:
 - **Email fetching**: To receive tickets from your configured mail(s).
 - **Email notification**: To send daily reports to admin, team leaders and agents.
 - **Auto close workflow**: To close tickets automatically
3. Copy email fetching link and run it in your browser.

It will fetch all unread mails from your mail and create tickets for them in your Faveo System.

> Please note: Faveo will not fetch unread mails which are older than 24 hours

After these steps if your system fetches mails and creates tickets then you need to set these cron jobs on your server. You can follow the link provided in the same page to set up your cron jobs.

**Comment by derek68** [comment]
Hi Mverma16

Thank you for a quick reply, I copied and pasted the link as you suggested and it worked, thank you.

All I have to do is work out how to add a cron job on the nas.

Regards


Derek
