### ISSUE TITLE
Always in development?

### ISSUE THREAD

**Issue by Neustradamus** [ladybirdweb/faveo-helpdesk#2713]
It is always in development?

There are a lot of tickets and pull requests too...

**Comment by tcreek** [comment]
I don't know. I tried the latest version, but it fails. A posted the issue on here two months ago. Nothing back. I guess I will move on to another helpdesk

**Comment by Neustradamus** [comment]
@tcreek: Please inform what will be another helpdesk possibilities!

**Comment by tcreek** [comment]
https://en.wikipedia.org/wiki/Comparison_of_help_desk_issue_tracking_software

**Comment by mverma16** [comment]
@Neustradamus due to other tasks in our bucket we lost the track of this repo. But we have not deprecated the project and the repo will still be maintained and developed by us. We will soon start updating the codebase in this repo.

Meanwhile, if you are looking for ready to use solution you can try [Faveo Helpdesk Freelancer](https://www.faveohelpdesk.com/pricing/) or other plans with personalized support from the Faveo team.

**Comment by Neustradamus** [comment]
@mverma16: Thanks for your reply!
It is not possible to have a https://github.com/faveo... with all perfect repositories?

And remove the automatic issues or create a special repository for automatic issues.

**Comment by Neustradamus** [comment]
@mverma16: Any news?

**Comment by mverma16** [comment]
We are working on the next update and will release it soon.

**Comment by Neustradamus** [comment]
@mverma16: Nice!

Can you move all automatic tickets (closed and opened) in a new repository to do not mix with normal tickets?

Examples:
- https://github.com/ladybirdweb/faveo-helpdesk-issues/issues
- https://github.com/ladybirdweb/faveo-helpdesk-bugs/issues

I can help you if you want...

**Comment by Neustradamus** [comment]
@mverma16, @bhanu2217: Any news?

**Comment by Neustradamus** [comment]
@ladybirdweb, @pranavkumar389, @lwsalerts, @mverma16, @bhanu2217: Any news?

**Comment by Neustradamus** [comment]
@mverma16, @bhanu2217: There is a 1.11.0 : https://github.com/ladybirdweb/faveo-helpdesk/releases

But 4.5.0 : https://support.faveohelpdesk.com/category-list/releases

What is the difference between 4.5.0 and 1.11.0?

**Comment by Neustradamus** [comment]
Currently, latest version is 2.0.3 (2023-10-31):
- https://github.com/faveosuite/faveo-helpdesk/releases

At this time:

Faveo Helpdesk and Servicedesk Release Notes v9.4.2.2
- https://support.faveohelpdesk.com/category-list/official-releases

Faveo Helpdesk and Servicedesk Release Notes v9.4.3.RC.2
- https://support.faveohelpdesk.com/category-list/prereleases
