### ISSUE TITLE
The side bar in faveo is not scrolling 

### ISSUE THREAD

**Issue by gnvarsha1** [ladybirdweb/faveo-helpdesk#272]
The side bar in faveo is not scrolling when the tab is extended. only using mouse its scrolling. its not user friendly

**Comment by mverma16** [comment]
Team need to check this in various systems in different OS and browsers.

**Comment by bhanu2217** [comment]
@gnvarsha1 As per the UI chages/updation document created, make this change also as part of that and hand it over to Arindam. Please make sure no unwanted unnecessary files are added in HTML,CSS,JS. Remove any unwanted code or files which are not being used.
Comment the code where required

Code should be tested i multiple browsers & screen sizes before being handed over to Arindam
