### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#276]
On a brand new install:

```
PHP message: PHP Fatal error:  Class 'Unisharp\\Ckeditor\\ServiceProvider' not found in /var/www/web/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

PHP Fatal error:  Call to undefined method Bugsnag\\BugsnagLaravel\\BugsnagFacade::setAppVersion() in /var/www/web/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 217
```

**Comment by mverma16** [comment]
@vijaysebastian please check this log for our build on [Travis](https://travis-ci.org/ladybirdweb/faveo-helpdesk/jobs/171350601) 
I hope solving this will solve guestisp's porblem and pass our build.

**Comment by guestisp** [comment]
THe error on Travis looks the same to mine

**Comment by guestisp** [comment]
Any update?

**Comment by vijaysebastian** [comment]
May i know how did you try to install ?

**Comment by mverma16** [comment]
We've updated the code, please try. [Build](https://travis-ci.org/ladybirdweb/faveo-helpdesk/jobs/172847560) on Travis passing now.

**Comment by guestisp** [comment]
I don't have PHP 5.6
Is this mandatory?  Please don't break PHP version. Laravel 5.2 that you are using is supported on PHP 5.5, please stay with that version or you break multiple installatio

Update PHP on production servers is not trivial.

**Comment by mverma16** [comment]
We agree that Laravel 5.2 is supported on PHP 5.5. But in recent composer update many vendor packages got updated and few of them now requires PHP 5.6 to work flawlessly.  You can check this[ travis report for php 5.5](https://travis-ci.org/ladybirdweb/faveo-helpdesk/jobs/173847794).
![1](https://cloud.githubusercontent.com/assets/10759797/20089560/b785968c-a5ad-11e6-9204-9d17debb55ed.PNG)

We'll try to check what can be done for PHP 5.5 support.

**Comment by guestisp** [comment]
Now I was able to install properly
