### ISSUE TITLE
User Profile page - Last reply name issue

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#280]
**Link:** http://ladybirdweb.com/support/user/2109 

Issue1: Last reply it shows client email address where as it should show First Name and Last name
Issue2: The reply name of agent/client should be linked to their profile

**Screenshot:** 
![screen](https://cloud.githubusercontent.com/assets/240898/19845072/5a60c882-9f59-11e6-9c6d-275f6c88c59a.png)

**Comment by mverma16** [comment]
Solved this issue now showing Full name of a user if first name is there otherwise username will be shown.
