### ISSUE TITLE
Ticket Details page - Client first name

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#281]
**Link:** http://ladybirdweb.com/support/thread/2269

**Issue:** Instead of showing username. First Name + Last name should be displayed

**Screenshot:**
![screen1](https://cloud.githubusercontent.com/assets/240898/19845143/f0700dd8-9f59-11e6-864e-33074bc25a2c.png)

**Comment by mverma16** [comment]
Showing full name which is "first_name" + "last_name" if there is no first_name then it will be "user_name".
