### ISSUE TITLE
Use correct format for version tag

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#289]
As suggested by [Semantic Versioning](http://semver.org/) tags should be in **X.Y.Z** format where X indicates major changes in functionality and public APIs. Y indicates addition/update in existing functionality and Z indicates patches for bug fix.
I'd like to propose that the next version of FAVEO should be tagged as v1.9.0

**Comment by bhanu2217** [comment]
Sounds like a good plan
