### ISSUE TITLE
Faveo latest git version install

### ISSUE THREAD

**Issue by fabioandreteles** [ladybirdweb/faveo-helpdesk#291]
Hello. I wanted to try Faveo so I tried to install the comunity edition. Tried the autoinstall and didn't work. Then tried to install all dependecies, copy folder to Apache, etc. but couldn't get it to work. First is opening this page:

https://github.com/ladybirdweb/faveo-helpdesk/blob/master/public/index.php

After trying on a new VM, from scratch, with an older tutorial I found over Google, I tried to connect to my site (/var/www/html/support) and gives me error 500. Even after giving 777 to all folders, the error still appears.

If someone could help me with a tutorial or steps to install would be great. As for now, I inform this error, if someone else also has it.

Regards,
Fábio

**Comment by fabioandreteles** [comment]
Hello. Some more testing, and after using faveo-probe I had all the requirements on new install. After that I had error 500. So I run chown www-data:www-data on the faveo folder udner /var/www/html. On the KB also checked the 500 error article and 777 those 3 files. After restarting Apache2 I have the error:

Not Found
The requested URL /helpdesk/public/step1 was not found on this server.

Where the IP is:
http://192.168.0.113/helpdesk/public/step1

So something more than before. Now I downloaded from the site, didn't cloned from github. Hope some one can guide me! Thank you again!

**Comment by bhanu2217** [comment]
Can you enable debugging in Laravel and than post the exact error message. Check here how to enable debugging https://laravel.com/docs/5.3/errors

**Comment by vijaysebastian** [comment]
@fabioandreteles please explain the issue, if it is still existing. @SarfrazS is our tester; He can help you to find the issue. His skype id is sarfraz14370. If you share your skype id, he can contact you.

Thank you

**Comment by quyetpawz** [comment]
Same error, trying to setup logging but really finding it unclear.

**Comment by mverma16** [comment]
@fabioandreteles Which version did you try to install? Can you try with the latest release tag(note: install without dummy data). Please try and revert so we can rectify the issue.

**Comment by SarfrazS** [comment]
I have tested from development branch without dummy data installation successfully done.
