### ISSUE TITLE
Amazon SES for outgoing emails

### ISSUE THREAD

**Issue by supportreq** [ladybirdweb/faveo-helpdesk#299]
Is it possible to configure outgoing emails to go from a specific email id but use amazon ses / smtp...

in the current scenario, amazon ses uses a different username which I cannot enter in the outgoing email section... there is no place to enter the email id / password...

please advice..

**Comment by bhanu2217** [comment]
AWS SES is already enabled in the version 1.0.8.0, you need to configure it and enable it from the admin panel

**Comment by supportreq** [comment]
@bhanu2217 where is the option in the configuration, there is only 
SMTP
PHP Mail
Send Mail
Mail gun
Mandrill
Log File..

Using the release present in github..

**Comment by bhanu2217** [comment]
We are checking

**Comment by vijaysebastian** [comment]
Sorry, We have missed it from our seeding. For a direct fix inset a row in 'mail_services' table 

'name'=>'SES',
'short_name'=>'ses',

Please keep on posting your issues. Thank you.

**Comment by supportreq** [comment]
it displayed.. how do i configure though?

is the key -> username and secret key -> password??
what is the region field? is it the smtp server?

**Comment by supportreq** [comment]
@vijaysebastian the region gives:
https://email.email-smtp.us-west-2.amazonaws.com

please check...

**Comment by vijaysebastian** [comment]
you can check the documentation [here](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/setting-up-email.html)

No need to follow optional steps
