### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by vik0803** [ladybirdweb/faveo-helpdesk#3]
hello,

Looking at the installation guide and the directory structure on GitHub isn't matching so is that getting uploaded sometime later.

**Comment by bhanu2217** [comment]
We will be realising first fully working version before end of this month that will take care of all the issues.

Thank You.

**Comment by guestisp** [comment]
@vik0803 if you want to install, you have to put the whole `code` folder inside your document root.
I've installed successfully Faveo last night with no issue.

**Comment by guestisp** [comment]
@bhanu2217 no updates so far ?

**Comment by sujit223** [comment]
We will get you the updates as soon as possible. Probably this week max

**Comment by sujit223** [comment]
please have a look the codes have been updated
have a look at the installation guide
https://www.youtube.com/watch?v=8Uvxq4O0xO0&feature=youtu.be
