### ISSUE TITLE
Image Attachment Tickets are not open for User.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#301]
In Version 1.0.8.0 RC.
Image attachment tickets are not open in client panel. Admin Panel it's opening.
While user open ticket  getting below error. Please check it.

![capture](https://cloud.githubusercontent.com/assets/18435376/20099389/417beb7c-a5de-11e6-946d-48f4e2c3fb31.PNG)

**Comment by vijaysebastian** [comment]
We have fixed this; Next release will resolve the issue. @SarfrazS please check.

**Comment by mverma16** [comment]
@SarfrazS please check and close this issue
