### ISSUE TITLE
Decode attachments in ticket reply  

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#302]
When an agent replies on a ticket and attaches a file(image/pdf/any format) user gets a reply email which contains the attached file. But that file is wrongly decoded and when a user tries to open the attachment it fails to open the file. Even after downloading the does not open.

**Comment by vijaysebastian** [comment]
Next release will update; Already implemented. @SarfrazS please check this.

**Comment by mverma16** [comment]
this issue has been fixed and will be a part of next bug-pix patch release
