### ISSUE TITLE
Email from address for daily reports

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#305]
Seems that daily report email doesn't have a properly configured From address and our server is rejecting the email for a not verifiable sender address.

**Comment by mverma16** [comment]
Daily reports and system notifications are sent using system's default configured email(s). Can you share more details about your configured email and problem?

**Comment by guestisp** [comment]
By using the "php mail" option daily reports are not sent, probably because the "From" address is not properly set (and our server is checking for a valid sender)

By using "send mail", emails are sent properly, but only after restoring the default configuration for `sendmail` in `config/mail.php` to `/usr/sbin/sendmail -bs`

Without that, sendmail is complaning about the missing "-bs" flag. Why did you totally remove the default laravel configuration ?

**Comment by vijaysebastian** [comment]
Thanks for the suggestion. We removed default, to avoid ambiguity in system. But this issue we noted, and will fix

**Comment by vijaysebastian** [comment]
@SarfrazS please check this configuration
