### ISSUE TITLE
No Notification on the Dashboard

### ISSUE THREAD

**Issue by jgrabitzky** [ladybirdweb/faveo-helpdesk#308]
Hi all,

With me no benachrichigungen appear, although it is supposed to be some.
because someone has an idea?

![notify](https://cloud.githubusercontent.com/assets/9860555/20208988/f7fb19e4-a7f1-11e6-8bc6-5ea3addf4fef.JPG)

**Comment by vijaysebastian** [comment]
Thanks for your feedback.Y ou will get a fix on next release, probably next week

**Comment by SarfrazS** [comment]
I have tested in development branch of faveo community, notification are coming on dashboard.
