### ISSUE TITLE
Non-english user name and surname = User directory broken

### ISSUE THREAD

**Issue by j0hnny-d0e** [ladybirdweb/faveo-helpdesk#309]
User directory does not open if there is a user or agent with non-english(russian tested) name AND surname(if either one is english - works fine). 
[faveo_error_log.txt](https://github.com/ladybirdweb/faveo-helpdesk/files/589065/faveo_error_log.txt)

**Comment by mverma16** [comment]
Hello @j0hnny-d0e ,
 Is this error only occurring in user directory? Are you able to open different ticket table pages and ticket timeline page?

**Comment by j0hnny-d0e** [comment]
Hi.
Ticket lists, ticket page, user profile page - everything works, looks like it's only user directory.
Name, for example, "тестимя тестфамилия"

**Comment by mverma16** [comment]
I am sorry I am unable to replicate the error. I tried to create the user with the name you suggested.
![1](https://cloud.githubusercontent.com/assets/10759797/20303821/3c795f9a-ab53-11e6-81c3-7c34c2796d1e.png)

Can you help us and replicate the issue in this demo we've created for testing.
link: http://www.faveohelpdesk.com/sarfraz/user
username: demo
password: demopass

**Comment by j0hnny-d0e** [comment]
Replicated by adding an agent with login "login" from admin panel. Strange, but your user worked. We found this problem for the first time by creating normal user from directory.

**Comment by mverma16** [comment]
What is the version of Faveo you are using? 

> You can check the version in the bottom right corner after login as an agent/admin in your Faveo system

If you are using an older version of Faveo please download the latest code from master and update your system. 
You can follow this [wiki article](https://github.com/ladybirdweb/faveo-helpdesk/wiki/How-to-update-v1.0.7.9-to-v1.0.8.0) to update.

If possible please share your issue and system's details on support@ladybirdweb.com so that we can rectify the problem in your system.

**Comment by j0hnny-d0e** [comment]
Installed yesterday following [this guide](http://ladybirdweb.com/support/show/how-to-install-faveo-helpdesk-on-ubuntu-1604-xenial-lts)
According to git, everything is up-to-date

**Comment by mverma16** [comment]
seems like the error is persists in the system, I am working on that.

**Comment by mverma16** [comment]
@j0hnny-d0e  please try this [patch](https://github.com/ladybirdweb/faveo-helpdesk/commit/92622101cfeb3ca749c08d511a71f43fa6daef7a). This will solve the problem.

**Comment by j0hnny-d0e** [comment]
I confirm, it's solved.
