### ISSUE TITLE
"Enter" twice won't create blank new line

### ISSUE THREAD

**Issue by ningmu** [ladybirdweb/faveo-helpdesk#312]
hi there,

On the message body, both on Submit a Ticket and inside the Agent's dashboard during reply, everytime I press "Enter" twice to create a blank new line for my message, the cursor would just go back-up.

Thanks!

**Comment by ningmu** [comment]
this is quite important. users/clients/agens got confused and have no idea why the cursor bounces back upward when pressing "Enter". thanks!

**Comment by vijaysebastian** [comment]
Thanks for the feedback, We will include a better WYSIWYG editor in upcoming releases

**Comment by ningmu** [comment]
Thanks! But for the mean time, is there a way to temporary disable the rich text editor and just use a pure text box so that users won't get confuse when attempting to make a blank line space?

Thanks!

**Comment by mverma16** [comment]
Changed the editor from WYSIWYG to CKEditor 4.5.6,  will be releasing in next bug fix patch.

**Comment by mverma16** [comment]
Currently only agent reply has new editor,  need to update all other pages where 'textarea' is being used for user input for description eg: ticket creation page, ticket reply page in client panel etc.
