### ISSUE TITLE
  × Alert ! stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by derek68** [ladybirdweb/faveo-helpdesk#313]
Hi All

I have install FAVEO on my Windows 10PC and im using wamp - apache web server.  Faveo has installed and is almost working. I can receive tickets but I cant sent tickets.  I get the following error.
  × Alert !
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Im not sure if it has something to do with our outgoing smpt server.  Our Server does not require a username or password to send mail.   But in Faveo, I have the feeling it is sending my username and password for my incoming server setting.  If so How do I get around this as I cant make out server use a username and password to send mail.

Once again thank you in advance for helping.

**Comment by derek68** [comment]
Hi mverma16 and vijaysebastian

So this is a bug and not anything I have done wrong?  Do anyone have an idear on when it will be fixed, or does anyone have a workaround?


Regards

Derek

**Comment by vijaysebastian** [comment]
Thanks for trying faveo. Can you please explain you issue detail, or if you can provide your skype id our support team help you to fix the issue. @SarfrazS  please look this issue.

**Comment by vijaysebastian** [comment]
Sarfraz is our tester, his skype username sarfraz14370 , please ping him

**Comment by derek68** [comment]
Hi All

Thank you for your help, but with the time difference, I have not been able to skype sarferz.  But I have upgraded my version to the latest one on here v1.0.8.0 and im now able to send a test email. 

So now I can received and email and send an email.  But when FAVEO receives an email, it apears in the que, but the sender does not get an email, and the agent does not get an email.  So what have I done wrong.

**Comment by derek68** [comment]
Thank you Sarfaz for you help yesterday, Faveo is working well. It would be nice for furture buils, the ability to build in the cron job. As when you install Faveo on a Windows PC, they do not have cron jobs.
