### ISSUE TITLE
Upgraded from 1.0.7.1 to 1.0.8.0, this message appears on logs. 

### ISSUE THREAD

**Issue by ningmu** [ladybirdweb/faveo-helpdesk#314]
Error	Production	11/18/2016 16:40:04	exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'There are no commands defined 
in the "message" namespace.' in /home/usercute/public_html/support/vendor/symfony/console/Application.php:469
Stack trace:
#0 /home/usercute/public_html/support/vendor/symfony/console/Application.php(501): Symfony\Component\Console\Application->findNamespace('message')
#1 /home/usercute/public_html/support/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('message:send')
#2 /home/usercute/public_html/support/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/usercute/public_html/support/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/usercute/public_html/support/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}

**Comment by vijaysebastian** [comment]
Can you please provide the context ?
You can see context in log itself !

**Comment by ningmu** [comment]
Just concerned with this log message after upgrading. Never seen this log messages before upgrading.
That's all. Thanks!
