### ISSUE TITLE
After upgrading, all replied messages in inbox, still marked as unread

### ISSUE THREAD

**Issue by ningmu** [ladybirdweb/faveo-helpdesk#315]
After upgrading to 1.0.8.0 RC, it's hard to identify real unread messages because all replied messages still marked or looked like unread. (Agent Panel) Please see attached. Thanks!

![unread](https://cloud.githubusercontent.com/assets/22490393/20511809/2a4bf5c2-b0b6-11e6-9796-77ec957e7850.png)

**Comment by ningmu** [comment]
Also ticket numbers suddenly changes to #AAA-0000-(_random-3-number_). Unlike before upgrading, ticket numbers pattern look like this, #AXCS(_random-4-letter_)-1715(_random-number_)-0001715(_random_)

**Comment by mverma16** [comment]
Thanks for notifying the issue, I'll have a look on it.

**Comment by vijaysebastian** [comment]
In 1.0.8.0 RC, ticket settings you have option to choose your own ticket number format. By default it is $$$$-####-#### ($ for alphabets and # for numbers). If you choose sequence it will increment sequence manner like AAAA-0000-0000,AAAA-0000-0001,AAAA-0000-0002 .... If you choose random random alphabets and number will generate. 

Why it has changed ?

If previous format is not matching current format ticket number will reset, like

Previous format = $$$$-####-####
Previous generated last ticket number = AASQ-0000-0001
changed to  = $$-$$-##-##
Changed ticket number = AA-AA-00-00

**Comment by ningmu** [comment]
I just followed religiously this instruction https://github.com/ladybirdweb/faveo-helpdesk/wiki/How-to-update-v1.0.7.9-to-v1.0.8.0 for upgrading process and only touched the settings indicated on that wiki. 

All my tickets before look like this: #AXCS-1715-0001715
but after upgrading they changed to #AAAA-000-001 without touching the Ticket settings.

Thanks!

**Comment by mverma16** [comment]
@ningmu Sorry, I forgot to update about change in ticket number format setting, will update it for the same so the other users don't face the problem.

**Comment by ningmu** [comment]
It's okay @mverma16, I was just being cautious not to touch any setting unless stated in the instruction/wiki. 

The only thing giving me a headache right now is the Unread mark on all messages in the inbox even you already replied. When you login at the Agen Panel, you have to open every messages just to check if they already replied or not. Thanks!

**Comment by mverma16** [comment]
@ningmu, can you please share the screen shots of timeline of the ticekts #AAAA-0000-011/9/10 in above pictures (whichever is a replied ticket). 
We also upgraded our system and we've not face this problem.

Sorry for the late response.

**Comment by ningmu** [comment]
Please see attached. On Inbox, that ticket still looks like marked/unread. Thanks!

![thread1](https://cloud.githubusercontent.com/assets/22490393/20551378/9b41708a-b17a-11e6-805e-23fbf75802c4.jpg)

**Comment by mverma16** [comment]
@ningmu can you try downloading latest code from [master](https://github.com/ladybirdweb/faveo-helpdesk/) and replace the files in your system. (Same as you did for upgrading except database updation step as database has been updated already).
> Take and keep a backup of your system.

**Comment by ningmu** [comment]
I'll try to update tonight. Will give you an update once finished upgrading the helpdesk. 
Thank you very much for that quick fix/update.

**Comment by ningmu** [comment]
@mverma16 The inbox now looks great after updating the files.
Thank you very much!
