### ISSUE TITLE
Forgot Password Email Not Sent

### ISSUE THREAD

**Issue by isaibn** [ladybirdweb/faveo-helpdesk#318]
When I request a reset link through the "forgot password" tool, I never receive an email. Other email functions work. This one doesn't. IMAP and STMP are configured correctly. Please help!!!

**Comment by SarfrazS** [comment]
Hello Isaibn,

Please can you tell me, which version you are using and from where download it.

**Comment by quyetpawz** [comment]
Having a similar issue. Email settings test says everything is fine. E-mails are coming in but e-mails don't seem to be sending out.

Running the master branch downloaded from github.

SMTP settings are the following:
server: smtp.gmail.com
port: 587
encryption: tls

When running a diagnostic it claims it sends to me with a successful message however I never receive the message.

**Comment by vijaysebastian** [comment]
Please change you queue to Sync

**Comment by SarfrazS** [comment]
I have tested in version 1.0.8.0 RC. it's working.
