### ISSUE TITLE
1.0.8 Error 500 when trying to login after installing (missing social media table)

### ISSUE THREAD

**Issue by quyetpawz** [ladybirdweb/faveo-helpdesk#319]
I'm getting an error 500 right after installing. I get through the steps, get to the end where the big login button is. Get the error upon clicking login.

I've managed to turn on logging and this is the log generated when attempting to load: http://www.canfurence.ca/faveo/public/auth/login

http://www.canfurence.ca/faveo/storage/logs/laravel-2016-11-28.log

I have confirmed that the table **social_media** is missing from the database. I checked the **included dummy databases** and there is **no table social_media** in them.

I cannot confirm if the install configured the database connection properly as I cannot find where those variables are set. 

What can I do to get the error 500 resolved.

**Comment by mverma16** [comment]
Hi @quyetpawz ,
I assume you've downloaded the code from [release tag v.1.0.8.0](https://github.com/ladybirdweb/faveo-helpdesk/releases/tag/v1.0.8.0). And you are trying to install dummy data while installing Faveo. 
I confirm that 'social media' table is not there in dummy database. I'd suggest you to try installing without dummy data or download the latest code from [master](https://github.com/ladybirdweb/faveo-helpdesk).

We've committed many bug fixes in the master branch after our last release. I'll be releasing v1.0.8.1 with all the bug fixes we've done to avoid this inconvenience.

**Comment by quyetpawz** [comment]
I downloaded it from the 1.0 8 release and not from the master. I wasn't sure if master was stable.

I had checked off the dummy data option when I ran the install. 

When will 1.0.8.1 be released? I will just do a fresh install with 1.0.8.1 once it is. Is there a way to be notified of new releases?

**Comment by quyetpawz** [comment]
Using the 1.0.8.0 RC from git hub. Problem solved. Did not select dummy data this time.
