### ISSUE TITLE
Filesize of attachments

### ISSUE THREAD

**Issue by lommes** [ladybirdweb/faveo-helpdesk#32]
Due to the migration in 2016_02_16_140450_create_ticket_attachment_table.php adding files (I only tested by mail attachment) larger than 65KB results in errors in the timeline view because imagecreatefromstring and imagejpeg fails.

**Comment by mverma16** [comment]
Thanks for updating us about the issue. We are working on it and we'll update the code in next release.

**Comment by sujit223** [comment]
We have fixed this issue
