### ISSUE TITLE
1.0.8.0 RC - Outgoing E-mail Error

### ISSUE THREAD

**Issue by quyetpawz** [ladybirdweb/faveo-helpdesk#323]
Using 1.0.8.0 RC master branch downloaded from github.

Settings:
Transfer Protocol: smtp
Host name: smtp.gmail.com
Port number: 465
Encryption: SSL
Authentication: Normal Password
Validate Certificates from TLS/SSL server checkbox: Whether checked or not, I receive the error below

Error received: Connection could not be established with host smtp.gmail.com [Connection timed out #110]

I am talking to my hosting to verify whether or not something is blocking sending mails. I have tested with the PHP MAIL transfer protocol and it claims to send but no mails are received.

I have tried turning on logging as per the laravel instructions but it does not appear to be creating logs.

**Comment by quyetpawz** [comment]
Update: It seems the phpmail setup is sending out however it seems to be delayed and come in later.

However people still do not receive most e-mails such as responses to tickets, password notifications or even test e-mails run via the diagnostic tool.

**Comment by VaporFan** [comment]
I got same problems, I config Emails and Email diagnostic works well. But Email function is not working when user registration, no activation link. I'm using smtp.gmail.com:465 SSL.

As well as in system configs/mail.php I configured to gmail smtp too

This is so sad. Please help.

**Comment by vijaysebastian** [comment]
Please change your queue option from database to Sync; Database is for queuing purpose; We haven't completed the documentation. You can find that option Admin>queue.

**Comment by quyetpawz** [comment]
My queue has already been turned to sync and I am still experiencing this problem.

My hosting admin suspects it is an ipv6 issue where faveo is trying to speak to ipv6 and our email server is only ipv4. Is this possible?

**Comment by equa24** [comment]
I had the same problem. But it worked on my personal server email WITHOUT the SSL settings. I'm using IMAP.
