### ISSUE TITLE
Some ticket replies appears in huge boxes and with or without text

### ISSUE THREAD

**Issue by neven-vujasinovic** [ladybirdweb/faveo-helpdesk#324]
In version 1.0.8.0 RC some ticket replies appears in huge boxes, with text sometimes visible but sometimes not. Also, when text is visible it is in different font than other replies. 

The images with text and without text is below:
![image](https://cloud.githubusercontent.com/assets/24271440/20755130/2183b6e2-b70e-11e6-8540-54317e26d177.png)

![image](https://cloud.githubusercontent.com/assets/24271440/20755208/6b10f9dc-b70e-11e6-87b7-112ee1f5a5f7.png)

**Comment by mverma16** [comment]
Yes there is a problem in iframe script which we are using to rendering ticket body/replies made by clients.
