### ISSUE TITLE
When ticket is assigned to a team it is still listed as "unassigned"

### ISSUE THREAD

**Issue by quyetpawz** [ladybirdweb/faveo-helpdesk#326]
When a ticket is assigned to a team the ticket remains being listed as unassigned when viewing tickets in a list type format. It would be more practical to see which team the ticket is assigned to.

Using the 1.0.8.0 RC version downloaded from git hubs main branch.

**Comment by mverma16** [comment]
Removing assignment as Arindam is working in team module.
