### ISSUE TITLE
Stop Daily Reports

### ISSUE THREAD

**Issue by FuXXz** [ladybirdweb/faveo-helpdesk#3260]
- Faveo Version : v1.10.7
- PHP version : 7.2.28
- Database Driver & Version : MySQL 5.7.29

Hello,

maybe anybody can help me to get rid of the daily report. I am flooded with reports every 5 Minutes. I think on every Cron run because i set it on every 5 Minutes.

Thank you very much for your time.

**Comment by mverma16** [comment]
You can update this setting by opening `your-faveo-url/job-scheduler` and set daily summary options as per your preference.

**Comment by FuXXz** [comment]
Ok, thank you very much
