### ISSUE TITLE
Getting DataTable errors

### ISSUE THREAD

**Issue by wowthemes** [ladybirdweb/faveo-helpdesk#335]
Hi,

I am getting Console errors while looking at "Unassigned", "Overdue", "Unanswered" etc tabs. 

http://nimb.ws/YGjso8

**Comment by mverma16** [comment]
Can you share the error message? 
Enable debug mode in the app and try to see the response of ajax call.

**Comment by mverma16** [comment]
New version has changed the ajax call url, please update the system and check.

**Comment by SarfrazS** [comment]
I have tested development branch of community, no console error coming while click or open unassigned and overdue tickets.

**Comment by wowthemes** [comment]
Yes, I pulled the recent updates and the issues are fixed now 👍 Ajax calls now getting response without any console error.
