### ISSUE TITLE
Admin LTE theme update 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#3418]
- Agent/Admin panel theme

All need to be updated to the latest version

**Comment by bhanu2217** [comment]
Update all CSS, JS etc

**Comment by Noor-mommadhi** [comment]
development time: 2 days
 
 **Task breakdown**
 1) download the admin LTE (latest version)
 2)creating the CSS-1 and js-1 file for upgrading
 3)developing the new theme version

**Comment by bhanu2217** [comment]
Client Panel template is available here https://github.com/ladybirdweb/faveo-helpdesk/issues/3418
Our client panel template now also has support for Bootstrap 5. 

For now use Bootstrap 4 template for client panel as Admin LTE currently doesn't support Bootstrap 5.
