### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by win189** [ladybirdweb/faveo-helpdesk#342]
Hello can i get some documentation on all the allowed Codelines in the templates

like (:$Picture_) as there isnt any 

and i would like to be able to use the templates to form a All account type signature instead of doing it per person

**Comment by mverma16** [comment]
@win189  we'll create a wiki article for editing email templates with available variables.

**Comment by win189** [comment]
Thanks cause were thinking of useing the templates to make a sort of Forced signature but couldn't find all the Code sections it allows
to see if thats a viable way of doing it

**Comment by win189** [comment]
any eta on this??

**Comment by mverma16** [comment]
Sorry for the delay in response. We are working on template modules to show the list of available variables that can be used in a particular template. We already have these templates in for text messages send by Faveo's SMS plugin 
See the reference image of a template of an SMS 
![capture](https://cloud.githubusercontent.com/assets/10759797/22476771/9944355e-e809-11e6-80d2-e03bca3542bb.PNG)

This will be a part of our next release.

**Comment by win189** [comment]
Can you link it forbme please

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
