### ISSUE TITLE
Can't Log In After Changing Logo

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#348]
Here's what I did...
I change the default Faveo's URL and logo at public_html\resources\views\themes\default1\agent\layout\agent.blade.php on line 60.

The original code was:

`<a href="http://www.faveohelpdesk.com" class="logo"><img src="{{ asset('lb-faveo/media/images/logo.png')}}" width="100px;"></a>`

after I changed the URL and the logo path I can't even login to my admin page. It say's Sorry Something Went Wrong. Really? Just changing the logo would impact my whole site?

**Comment by mverma16** [comment]
Please enable app debug mode and share the exact error message so we can check what went wrong in your system. To enable debug mode

- Open .env file in your root directory of Faveo.
- If you can't see .env you can try showing hidden files.
- Edit you .env file
replace 
`APP_DEBUG=false`
with
`APP_DEBUG=true`

Now when you'll open dashboard it will show the exact error message, just share the error message with us.

**Comment by equa24** [comment]
@mverma16 my mistake... it seems I'm uploading a different file. I'm editing Faveo 1.0.8 while my installation use the newest 1.9.  Downloaded the wrong version on my localhost. Oh god, how could this happened?
