### ISSUE TITLE
Clicking Labels on Admin Page Result in Error

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#350]
I notice there's a menu 'Lables' on Admin Panel. It's located under Tickets setting:

![labels](https://cloud.githubusercontent.com/assets/15904940/21337308/ca54b5c4-c69e-11e6-8622-21caced86449.png)

When I tried to click it, it shows a page that says "Sorry, Something Went Wrong" which of course it means an error. I activated app debug mode, and when click the Lables menu again it shows these errors like below pictures:

![112](https://cloud.githubusercontent.com/assets/15904940/21337295/bc95a984-c69e-11e6-8daf-b69b800d067e.png)

It says LabelController doesn't exist. Well, I installed the app through Softaculous, so I'm pretty sure Faveo should include that file at the beginning. Maybe it's a bug? Or just an error, I guess. I don't know. Does anyone had the same problem like me?

**Comment by bhanu2217** [comment]
Labels feature is avilable only in Pro edition, we will remove this menu option from the Admin panel

**Comment by equa24** [comment]
I would like to add some more.... This time it's Approval menu:

![424](https://cloud.githubusercontent.com/assets/15904940/21375584/252e4a9c-c761-11e6-99b0-49e439ec4324.PNG)

Does this also supposed not to exist in the community edition? Because it's also not exist in the app debug mode:

![5353](https://cloud.githubusercontent.com/assets/15904940/21375600/39a62378-c761-11e6-9d57-4d99e27ccaff.png)

**Comment by mverma16** [comment]
Sorry my bad, this is also a part of Faveo pro version.

**Comment by SarfrazS** [comment]
I have tested in faveo community of development branch these option are not in community. so it's fine.
