### ISSUE TITLE
Security: Update jQuery to latest version

### ISSUE THREAD

**Issue by PeopleInside** [ladybirdweb/faveo-helpdesk#3572]
- Faveo Version : all version
- PHP version : 7.3

You need update jQuery to the latest version, currently 3.5.1 that fix important security issues

#### Downloaded from
- [ x] master-branch

- [ x] development-branch

- [ x] release-tag

**Comment by Noor-mommadhi** [comment]
The jquery updated in these two PR:
https://github.com/ladybirdweb/faveo-helpdesk/pull/8148
https://github.com/ladybirdweb/faveo-helpdesk/pull/8081
