### ISSUE TITLE
Incoming email connection failed

### ISSUE THREAD

**Issue by dazzcreations** [ladybirdweb/faveo-helpdesk#36]
I am not able to connect to gmail using IMAP on XAMPP.
Error: Incoming email connection failed

**Comment by SarfrazS** [comment]
Dear Dazzcreations,
I have gone over the issue you have mentioned. It looks like you have probably not enabled IMAP PHP Extension, If PHP IMAP extension is already enabled then check your email server setting & credentials that you entered.
Thank You.

**Comment by dazzcreations** [comment]
Hi just got it working by enabling access to less secure apps on my google account.
