### ISSUE TITLE
Default department without linked help topic prevents ticket submission from client panel[v.1.9.1]

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#361]
I have three department, one of them is default. (See the image below)
![1](https://cloud.githubusercontent.com/assets/10759797/21563775/74dee604-ceab-11e6-9d78-067beeb8e990.png)

I've created three help topics each of them is linked with a department. (As while creating help topic user is asked to select department and links selected department with the help topic).

![1](https://cloud.githubusercontent.com/assets/10759797/21563834/1bb3eaba-ceac-11e6-8763-ab657e1a3a4e.png)

But here's the catch, none of my created help topic is linked with my default department( see the images for better understanding).

Now if a user/client tries to create ticket from client panel it throws the error.
![1](https://cloud.githubusercontent.com/assets/10759797/21563883/9ed1a266-ceac-11e6-9da0-37854e282de6.png)

**Comment by SarfrazS** [comment]
I have tested development branch of community working.
