### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [ladybirdweb/faveo-helpdesk#3619]
It is possible to have a new version?

**Comment by Neustradamus** [comment]
I do not see the last current version.

Where is it?

**Comment by Neustradamus** [comment]
@mverma16, @bhanu2217: There is a 1.11.0 : https://github.com/ladybirdweb/faveo-helpdesk/releases

But 4.5.0 : https://support.faveohelpdesk.com/category-list/releases

What is the difference between 4.5.0 and 1.11.0?

**Comment by mverma16** [comment]
@Neustradamus Currently Faveo has two editions Faveo community and Faveo paid products.
The latest release for the Faveo community is **v1.11.0** while for the paid version of Faveo **v4.5.0**.

In the Faveo community, we have all the basic functionalities of ticketing solutions required for helping small business owners, freelancers provide organized support to their customers.

In the paid version, we have various advanced features such as Dynamic Form builder to customize the ticket, user forms, Workflow-listeners to automate the flow of your support process, SLA with reminders to send alerts on violation or approaching of resolution time of the ticket, and many more.

Under Faveo paid products we have **[Faveo Freelancer](https://www.faveohelpdesk.com/pricing-india/)** which is free of cost and has all the features of the paid products with a limitation of the number of agents to only two.

Though we will continue to improve and provide bug fixes in the Community edition along with adding support for PHP 8. But we are not planning to add any new feature in the Community edition on priority.
