### ISSUE TITLE
New Agents are showing second page.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#363]
New Users and agents are showing in last page of user directory. It should be showing in top of the first
Page. Please sorting and correct it.
![caure](https://cloud.githubusercontent.com/assets/18435376/21588473/03ccdf34-d10d-11e6-8f48-b13cac595925.PNG)

Development branch of Faveo-helpdesk.

**Comment by mverma16** [comment]
will be resolved by 15th
