### ISSUE TITLE
ErrorException in artisan package:discover

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#3652]
## Error in Faveo Community

**ErrorException** in **artisan package:discover**
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5f43cd62db267f0018718514?event_id=5f43cd62005e0b2735820000&i=gh&m=ci)

## Stacktrace

    \app\Console\Commands\SetupTestEnv.php:45 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5f43cd62db267f0018718514?event_id=5f43cd62005e0b2735820000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by richardfeliciano** [comment]
Same error here

**Comment by richardfeliciano** [comment]
go to SetupTestEnv.php:45

Change this:
```
  $dbUsername = $this->option('username') ? $this->option('username') : env('DB_USERNAME');
  $dbPassword = $this->option('password') ? $this->option('password') : (env('DB_PASSWORD')) ? env('DB_PASSWORD') : '';
```
to this:
```
        $dbUsername = env('DB_USERNAME');
        $dbPassword = env('DB_PASSWORD');
```
And run the command, dont forget to config your .env file
