### ISSUE TITLE
 Faveo Cron Command is not working for both pro and community.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#366]
This  command **(/usr/bin/php-cli -q  /home/princ7t7/public_html/support/code/artisan schedule:run >> /dev/null 2>&1 )** is not working for Faveo-pro and Community. Right now we are set simple command
curl -q http://ladybirdweb.com/support/readmails > /dev/null 2>&1. Please check why new cron is not running.

**Comment by superkekko** [comment]
Is the issue resolved? I run the 1.9.6 version and I can't tech the emails.
