### ISSUE TITLE
Email function is not working

### ISSUE THREAD

**Issue by chi07** [ladybirdweb/faveo-helpdesk#37]
Thanks Ladaybirdweb Team for giving very helpful this modules

I installed and it worked fine. But, email function is not working.
I use VPS that supplied by Vultr INC

VPS: CENTOS 7 64bit. 
All requirements of system are OK. All functions work fine except Send email function. There is no email can be send ( register, reset password, reply ticket...).

I debuged: 

IN Http/Comment/PhpMailController has function: fetch_smtp_details() always return null in all cases. So, there is no email can be send.

**Comment by SarfrazS** [comment]
Dear Shinichi2510,

I have gone over the issue you have mentioned. It looks like you have probably not configured your email setting, Please go over this article http://ladybirdweb.com/support/show/incomingoutcoming-email-setting to understand how email setting works.

Thank You.

**Comment by shinichi2510** [comment]
Thanks yo SafazS.
When I configure: I enabled IMAP, SMTP. When I entered the information, **Outgoing Mail is OK**, but when I enable Incoming Email Information is always show: Unable to process the details 
This is Incoming Email Info

IMAP protocol: IMAP
imap.gmail.com
port number: 993
Encryption: SSL

Thank You.

**Comment by SarfrazS** [comment]
Try this solution  https://github.com/ladybirdweb/faveo-helpdesk/issues/36

**Comment by shinichi2510** [comment]
Thanks SarfrazS 
 Email server setting & credentials are correctly. But it's working.

I debug and i see: 
FatalErrorException in EmailsController.php line 453: Call to undefined function App\Http\Controllers\Admin\helpdesk\imap_open()

    in EmailsController.php line 453

I dont know why: imap_open() is a native function of PHP. So why we has this bug?

**Comment by SarfrazS** [comment]
Can you check and see if PHP IMAP extension is enabled

**Comment by shinichi2510** [comment]
Thanks. It worked. I want to ask 1 question.
When I reply a ticket via email. It's not updating the ticket. Because, I have not set up cron job?
When i send new email to system email that configured, there is no ticket will be created.

**Comment by SarfrazS** [comment]
You are welcome Shinichi.

You need to configure the Cron job to fetch emails into the system.

**Comment by shinichi2510** [comment]
Thanks SarfazS so much, you always reply so quickly.
This is my demo. I configured and save successfully. But, can not create and update ticket via email. Please help me check

http://104.238.148.32/shopping_cart/ticketsystem/public.

Admin account: sunshine25105@gmail.com / letmein

**Comment by SarfrazS** [comment]
Sorry the previous link was different purpose.
try this to set cron job
http://ladybirdweb.com/support/show/cron-job-scheduling

**Comment by shinichi2510** [comment]
Great, It works fine now. Many thanks to Sarfazs.
There is a small issue: Can not delete tickets from the trash. Hope you and Ladybirdweb will fix it soon. Maybe need to have a button "Empty trash" also.
 It's great help desk system. Thanks again.

**Comment by SarfrazS** [comment]
We will release at soon.

**Comment by fajarwahyu99** [comment]
https://www.ladybirdweb.com/support/show/incomingoutcoming-email-setting this link is 404

**Comment by viitoradmin** [comment]
Can you please help as I am facing the issue like this..
"You have not configured system mail. Faveo can't fetch tickets from mail or send mail to users without it. Click here to configure the mail." However I have added the email.

Moreover https://www.ladybirdweb.com/support/show/incomingoutcoming-email-setting this link is 404. 

![faveo](https://user-images.githubusercontent.com/27955915/49225511-463c3000-f40a-11e8-9dff-1deeeb8bf7a3.png)
Please help..!!!

**Comment by mverma16** [comment]
@viitoradmin make sure you have set up email for both fetching and sending emails by enabling incoming and outgoing in the configured email.

**Comment by mverma16** [comment]
We have moved articles for the community on our wiki page of this repository. Check https://github.com/ladybirdweb/faveo-helpdesk/wiki/Email-Configuration for more information about email setup.

**Comment by aloopkin** [comment]
> @viitoradmin make sure you have set up email for both fetching and sending emails by enabling incoming and outgoing in the configured email.

it means email fetching is mandatory? what if we want people to be able to open tickets only from the web?

**Comment by lwsalerts** [comment]
@aloopkin No email fetching is not mandatory, system can be used without setting up incoming settings. The system shows this warning alert so that users will be aware why system is not fetching mails or sending emails to users.

You can configure emails settings without incoming settings so that system will not fetch and create tickets for the mails from mailbox but outgoing should be set so that system can send notification emails to users and admin/agents for ticket activities.
