### ISSUE TITLE
Buttons do not work in other language 

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#377]
In ticket listing pages there are different buttons to perform different operation on multiple selected tickets, however these buttons only works when the system language is English otherwise they don't perform desired operations.
![1](https://cloud.githubusercontent.com/assets/10759797/21977919/5ad57614-dbfe-11e6-934a-8a0604d525c3.PNG)

**Comment by chesslip** [comment]
It seems that the problem is solved. This buttons now work in Russian. Also tested it on French and German

**Comment by ricardoalvim-edu** [comment]
In portuguese I had this problem. It solved in Portuguese in last update?

**Comment by mverma16** [comment]
It should work for all translations now, but I'll check and confirm.

**Comment by mverma16** [comment]
Checked in recent releases it's not working again.

**Comment by leandromendonca** [comment]
I have the version 1.9.6 in Portuguese with the same issue.
I've tried this [quick fix](https://github.com/ladybirdweb/faveo-helpdesk/pull/493/files) and works!
