### ISSUE TITLE
Error When Changing User Password

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#384]
Just tried to change client's password...
And caught this error:

× Alert ! Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /home/site/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and defined

**Comment by mverma16** [comment]
It looks like the your outgoing email configuration has some problem. Can you try sending test emails from the system using email diagnostics. 
Go to admin panel>Email diagnostic
choose system mail to send email from. Enter reciepint's email address and message to send email.

**Comment by equa24** [comment]
You're right... it was my SMTP problem... I fixed it. Thank you for your help.
