### ISSUE TITLE
Notification ErrorException

### ISSUE THREAD

**Issue by jeckill** [ladybirdweb/faveo-helpdesk#397]
> Trying to get property of non-object (View: /var/www/resources/views/themes/default1/agent/layout/agent.blade.php) (View: /var/www/resources/views/themes/default1/agent/layout/agent.blade.php)

> Trying to get property of non-object (View: /var/www/resources/views/themes/default1/agent/layout/agent.blade.php) (View: /var/www/resources/views/themes/default1/agent/layout/agent.blade.php)

ErrorException
```
<?php if($notification->is_read == 1): ?>
                                        <li  class="task" style="list-style: none;margin-left: -30px"><span>&nbsp<img src="<?php echo e($notification -> users -> profile_pic); ?>" class="img-circle"  style="width:6%;height: 5%" alt="User Image" />
                                                <a href="<?php echo route('ticket.thread', $notification->notification->model_id); ?>" id='<?php echo e($notification -> notification_id); ?>' class='noti_User'>
                                                    <?php echo $notification->notification->type->message; ?> with id "<?php echo $notification->notification->model->ticket_number; ?>"
                                                </a></span>
                                        </li>
                                        <?php elseif($notification->notification->model): ?>
```

**Comment by mverma16** [comment]
can you tell the version you are using.

**Comment by jeckill** [comment]
@mverma16 
v1.9.3

**Comment by mverma16** [comment]
Please share the URL where you getting this error and steps to replicate it (if specific steps are required). 
To solve it please clear data from the following tables in your database
>user_notification
>notifications

**Comment by jeckill** [comment]
Deleting data helped, thank you. I will try to repeat this error
