### ISSUE TITLE
Standard directory structure

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#4]
A standard Laravel directory structure should be used.
For example:

`app`
`public`
and so on.

Actually, the whole faveo application is stored inside the public folder, in a `code` directory (that also contains `public` folder)

Everything should be moved one level up.

**Comment by bhanu2217** [comment]
We haven't changed the Laravel default structure here but while installing we usually move it out of public. We will implement this change in new installer and not use public folder as default

**Comment by guestisp** [comment]
Well, actually you have to publish the content of `code` folder in document root: https://github.com/ladybirdweb/faveo-helpdesk/tree/master/code

index.php loads file inside another `code` folder under document root. 
https://github.com/ladybirdweb/faveo-helpdesk/blob/master/code/index.php#L21

Default laravel installation load file from parent directory:
https://github.com/bestmomo/laravel5-example/blob/master/public/index.php#L21

This:
https://github.com/ladybirdweb/faveo-helpdesk/tree/master/code
should be inside `public` folder (or any other document root)

This:
https://github.com/ladybirdweb/faveo-helpdesk/tree/master/code/code
should be moved up, outside the document root and not inside

**Comment by vik0803** [comment]
@guestisp can you please upload the repo from your end

**Comment by guestisp** [comment]
I'll try to fix next week

**Comment by guestisp** [comment]
PR made and available for testing

**Comment by ayurmedia** [comment]
i agree, code should not be in htdocs / public, but hidden outside !

**Comment by bhanu2217** [comment]
Directory structure has been changed to Laravel default
