### ISSUE TITLE
User Locked Out Just After 1 Attempt of Fail Login

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#400]
This is happened when I change a client's password. After I changed it, I logout my admin account and try to login using client's account. Faveo says it's fail because wrong username or password. How come? I just changed it's password! And then I got locked out due to excessive login attempt. This is weird because I put 5 attempts before locked out, while Faveo locked me out just after 1 attempt.

And then I try to login using my admin account, well, I got locked out too of course. The only way is I opened Internet Explorer, login to my admin account, and then reset the fail login attempt to 0 (to disabled it).

After that I clear all my browser history and login with my admin account again. This time it worked. I logged out again and then try to login with previous user account, fail 1 time, and I got locked out, again.

This is sooo weird, it always happened when I change user's password, and even though I disabled the locked out system, it still working.

**Comment by equa24** [comment]
I don't think this is a bug. I think there's a weird mechanism of the cookies and cache. I'm still checking it. I'll report again if I ever encounter this problem again.

**Comment by mverma16** [comment]
I'd still consider it a bug. #355 has been raised but I was not able to recreate this issue on other servers. I'll try to recreate your scenario in my local app.
