### ISSUE TITLE
Private Help Topic Kept Showing on Client Side

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#401]
I just made a few help topics and set them as PRIVATE.

I thought PRIVATE means it can only be access by agents. It turns out, the PRIVATE Help Topics still visible on client side.

**Comment by mverma16** [comment]
I faced the same problem few days back, but forgot to raise an issue. Thanks for reminding me and raising the issue.  👍

**Comment by kustav123** [comment]
Am facing the same problem how to solve
