### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by win189** [ladybirdweb/faveo-helpdesk#402]
Hello i was wondering as to a eta on when the documentation from
https://github.com/ladybirdweb/faveo-helpdesk/issues/342

Will be made or linked

**Comment by mverma16** [comment]
Sorry for the delay in response. We are working on template modules to show the list of available variables that can be used in a particular template. We already have these templates in for text messages send by Faveo's SMS plugin 
See the reference image of a template of an SMS 
![capture](https://cloud.githubusercontent.com/assets/10759797/22476771/9944355e-e809-11e6-80d2-e03bca3542bb.PNG)

This will be a part of our next release.

**Comment by equa24** [comment]
You know, so far I just made this based on what appears on the default template:

Agent name			: {!!$ticket_agent_name!!}
Ticket number			: {!!$ticket_number!!}
Ticket assigner		: {!!$ticket_assigner!!}
Ticket's URL+			: {!!$ticket_link!!}
Name of your company	: {!!$system_from!!}
Client's name			: {!!$user!!}
Ticket link with number	: {!!$ticket_link_with_number!!}
Department Signature	: {!!$department_sign!!}

Full name of client		: {!!$ticket_client_name!!}
Client email			: {!!$ticket_client_email!!}
Content of the ticket	: {!!$content!!}

Agent's signature		: {!!$agent_sign!!}
Merged ticket number    : {!!$merged_ticket_numbers!!}
Email of the user		: {!!$email_address!!}
User's Password 		: {!!$user_password!!}
URL to reset password	: {!!$password_reset_link!!}

Team's name			: {!!$team!!}

Are there more than any of these code?

**Comment by win189** [comment]
Ok with all that i just need one for a image and im done

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
