### ISSUE TITLE
No Plugin Development Documentation

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#405]
When I translated Faveo, there's a string saying there's a possibility for the community to create their own plugin and share it with others. However I didn't see any documentation about how to develop plugin.

So far I only saw plugin developed by Ladybird only. Where's the documentation?

**Comment by vijaysebastian** [comment]
@equa24  please look this [document](https://docs.google.com/document/d/1spyLbXIiUdqPubeKbbBqirZq0IbqtSYQ9KVhFpeg5gA/edit)
