### ISSUE TITLE
Notifications Won't Disappear Even Though I Clicked "Mark All Read"

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#407]
It supposed to be like Facebook. When we clicked the notifications number above the bell, and clicked "Mark All Read" all the notifications was supposed to be disappear.

But instead the message was only faded out and the number kept showing the total number of notifications like this:

![2214124](https://cloud.githubusercontent.com/assets/15904940/22650276/138022dc-ecb1-11e6-93bf-6ab9415bf898.png)

**Comment by equa24** [comment]
I have 5 notifications now... but the it still appear even though I clicked "Mark All Read"

![ffff](https://cloud.githubusercontent.com/assets/15904940/22684388/b7809220-ed4e-11e6-9aeb-a9070c65325e.png)

**Comment by mverma16** [comment]
We are currently reworking on notification module. Notifications should work like Facebook and notifications body should be more interesting with more useful details.
