### ISSUE TITLE
Installer entry logic and `.env` file

### ISSUE THREAD

**Issue by adam-dej** [ladybirdweb/faveo-helpdesk#411]
We would like to host this application in a Docker container. However currently available Docker images are  unsatisfactory for us, so we are writting our own (and once it's finished we would like to share it!).

The problem is persistence of `.env` file. **Expected behaviour:**

  - After the container is started for the first time the application should redirect to an installer.
  - The `.env` file should then persist between container restarts / recreations from images.
  - After the installer finishes the user should have access to the `.env` file to edit it (optional, since this can be solved using environment variables)

**Problems and proposed solutions:**

Problem is that after the installer runs, initializes the database and stores data in the `.env` file, when the container is restarted, this `.env` file is lost, and the installer runs again.

On the other hand if the Docker image contains the `.env` file (even empty) the installer does not run on the first start and the database is not initialized for the user.

Proper solution is to somehow persist this file, if it exists. Docker supports persisting directories using "Data volumes". However, the `.env` file is in the roof folder of the web app, and persisting the whole web app would miss one of the points of running it in a Docker container.

One possible solution is to move the `.env` file to a dedicated folder, say, `/config` and to modify this app to look for it there. This folder can then be persisted using a data volume.

Another possible solution is to modify the app to run the installer if the `.env` file does not exists **or is empty**. This file could then be persisted by [mounting  a host file as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume).
This, however, presents yet another problem: after the installer finishes it writes results to `example.env` and then renames this file to `.env` (why? Is it due to atomic updates?). This causes an inode change and triggers an error in Docker (>=v1.1.0) such as “Device or resource busy”. It would be necessary to modify the application to write changes directly to the `.env` file.

Yet another option is to use a symlink in place of the `.env` file pointing to a non-existing file in some persisted volume. The installer uses `file_exists` function which returns false for symlinks pointing to non-existing files, so the installer would run. However, after it finishes it will use `rename`, which would overwrite the symlink. Solution would be to, before the rename runs, check whether the `.env` file is a symlink, and if it is, run `rename` with `readlink` as a target, storing the `.env` file in the location pointed to by this symlink.

Solution requiring the least amount of modification of the web app would consist of a change to the installer. Just after `rename`-ing `example.env` to `.env` it would check whether environment variable `INSTALLER_ENV_DESTINATION` is set, and if it is, it would also `copy` `.env` to that destination.
Our docker startup script will take care of the rest.

We would be happy to implement one of these solutions for you and send you a pull request. Which solution is most likely to be accepted by you?

**Comment by mverma16** [comment]
@adam-dej  Thanks for informing about this problem along with the solution. We'll check with our Docker Image builder and try to replicate the problems and implement suggested fixes.

**Comment by mathieu-aubin** [comment]
Isn't it just a simple toggle switch -v /HOST_PATH/to/.env:/CONTAINER_PATH/to/.env ?
The -v switch works as good for a rep than a file... i provision my aliases that way.

**Comment by adam-dej** [comment]
That is, of course, the first thing I've tried. But then, as I've mentioned previously, the inode of that file can't change. When the installer runs it writes not directly to the `.env` file, but to `example.env` which it then `rename`s (effectively moving it) to `.env`, resulting in an inode change and "Device or resource busy" error.

**Comment by mathieu-aubin** [comment]
Can you please tell me what Kernel you are using? An unsopported kernel would definately give you such message. devicemapper would also give you headaches of this type if the container/process is mounted on a different namespace. I suggest you look into that on popular search channels, they must have some relevant infos that you could read and pick up -- i'm zero for explaining and not having any hands or eyes-on config/logs/env takes away a shitpile of my potential helping abilities. If i find time i will see to fetch or piece together some infos for you (throw me more infos regarding your host/os/env/virt)

As far as solutions, my opinion is if you have one that works, or a dozen, take your own easiest path. Modifying the source code doesn't have to be a permanent thing on here, rather use a script to proceed to making your intended modifications right after a pull. Write a shell/cli installer instead of a web interface if it makes your life easier, the whole '3 minutes' of web installation isn't something anyone will miss once you get a Faveo Admin panel up and running to your standards.

Then, you share. Let the community examine your moves, correct fishy attempts or just plain tell you they couldn't have done any better. So again, if you have a solution that works, no matter what which how, do it ! 🥇

If you need any sort of help regarding scripting,mods automation..  feel frre to ask --- let me know about your progress!

**Comment by mathieu-aubin** [comment]
@adam-dej i took some time and... installing without the example.env or a .env file works like a charm assuming server has write access on filesystem. No, it's not a docker container rather a virtual machine running off a centos7 host, qemu/kvm (libvirt 2.0.0), ipv4 only with locally spoofed dns from my /etc/hosts. 

I installed on 14.04 to start, using an automatic install script i made a while back. All dist-upgraded and rebooted after initial install, php56 (latest, ondrej), nginx (latest stable, official), current git pull (deleted the env's files before accessing the webui). So far so good.

There's way to provision the env variables without an actual .env file, too.....

**Comment by adam-dej** [comment]
Hi. First of all, I really appreciate your advice. However, I must have failed to explain my issue.
The "Device or resource busy" error message: I'm using CoreOS stable, it runs on 4.7.3. But the exact problem is described in the Docker documentation [I've linked to](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume).
"Note: Many tools used to edit files including vi and sed --in-place may result in an inode change. Since Docker v1.1.0, this will produce an error such as “sed: cannot rename ./sedKdJ9Dy: Device or resource busy”. In the case where you want to edit the mounted file, it is often easiest to instead mount the parent directory." (As I've mentioned, mounting a parent directory would mean mounting the root of the web app.) So it's a known limitation of Docker, not a problem in a way or machine I'm deploying my container on.

As for asking which solution to implement, I was just trying to save time for me and for the community reviewing my work, but I hear you, I'll take my own easiest path. (Also I wanted to avoid non-upstream patches in my container, since I could introduce bugs, and if users experienced those they would probably report them here and waste your time.)

I'm aware that installing using my own script would work, and would be independent of existence of `.env` file. However, If I were to write such script I would be duplicating application logic, which I think is a terrible practice. The code should exist only in a single place.

My goal was to build a container which would be completely hassle-free for the user. An web installer would run on the first start, mainly to initialize the database and create an admin account, and then the app would work like intended. And that effort brought me to the problem of existence / nonexistence / persistence of the `.env` file, which is the trigger for entering the web installer.

Anyway, I really appreciate your advice and since my original question is answered I'm closing this issue.
