### ISSUE TITLE
Potentially misleading README

### ISSUE THREAD

**Issue by adam-dej** [ladybirdweb/faveo-helpdesk#412]
"[Requirements](https://github.com/ladybirdweb/faveo-helpdesk#requirements)" in your README file mentions you support MySQL, Postgres, sqlite or SQL Server. However, when trying to install this application on Protgres:

  - the Postgres is not offered in the automated installer script
  - `artisan migrate` fails on a Postgres database
  - `DB/demodatabase.sql` contains MySQL-specific statements and importing it fails on Postgres.

Since the issue #62 is still open, is Postgres really supported? If it is not supported, the readme should not mentioned that it is.

The Readme also mentions that PHP 5.5+ is supported. That is somewhat ambiguous, does that mean that 5.5.x and 5.6.x is supported, or any version newer that 5.5 is supported? We haven't been able to use this application on PHP 7. If PHP 7.x.x is not yet supported, clarification of supported versions in the README would help.

**Comment by mverma16** [comment]
We've not tested the app with Postgress and it might not support Postgress DB. The readme file was prepared on Laravel requirements  and specifications. We'll update the readme file as it is currently not have been tested for other databases except MySQL.

Current version of Laravel used in application is 5.2 which requires `PHP >= 5.5.9`. However the application is using some packages which only works on PHP 5.6 and later versions, so we've mentioned 
* PHP Version: 5.5+ (5.6 recommended) 

Also the application does support PHP 7.*.*, I am using it with PHP 7 in my local system on windows as well as on Ubuntu 14.04 LTS.

**Comment by mverma16** [comment]
Readme file has been updated.

**Comment by adam-dej** [comment]
Thank you, and good to hear about PHP 7 :).
The problems I've encountered with PHP 7 must have been an error on my part then.
