### ISSUE TITLE
Can't Install it, Broken at step 6

### ISSUE THREAD

**Issue by wowthemes** [ladybirdweb/faveo-helpdesk#415]
Tried thrice to install it. It creates tables and seeds but on step 6 show an empty page. Refreshing the step 6 page redirects to step 3. Don't know what's the issue.

**Comment by wowthemes** [comment]
Can someone please reply

**Comment by mverma16** [comment]
Hi sorry for the late reply.

Follow these steps to debug and get the error message.

- Edit your root/app/Exceptions/Handler.php file.
- Add `dd($)` before switch statement in the last function. [line no 157]
- Try fresh installation.
- It will show the exact error message

Once you get the error message share it with us.

**Comment by mverma16** [comment]
@wowthemes did you figure out the error?

**Comment by wowthemes** [comment]
Figured out the issue. It was maximum execution time error. Printing the error in Exception resolves the issue. Thanks for your help
