### ISSUE TITLE
Created Custom Form But Not Showing on Ticket Details

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#416]
I created any custom form with any values, but nothing shows up on ticket details. So, what is the purpose of Custom Form if nothing shows on ticket details or on database?

So I check TicketController.php and look at these lines:

```
if ($form_data != null) {
            $help_topic = Help_topic::where('id', '=', $helptopic)->first();
            //$forms = Fields::where('forms_id', '=', $help_topic->custom_form)->get();
            $form = \App\Model\helpdesk\Form\Forms::find($help_topic->custom_form);
            $form_name = '';
            if ($form) {
                $form_name = $form->formname;
            }
            foreach ($form_data as $key => $form_details) {
                if (!is_array($form_details)) {
                    $form_value = new Ticket_Form_Data();
                    $form_value->ticket_id = $id;
                    $form_value->title = $key;
                    $form_value->content = $form_details;
                    $form_value->save();
                }
            }
        }
```

The controller only fetch the value of the created custom form, but not storing any of the information inside it into the ticket details.

It would also be nice if the created custom form value could also be included in the Report. So, when I click report menu, I could choose not only how many tickets from specific Help Topics, but also from Custom Form values and Organizations.

**Comment by sxmarsha** [comment]
I have exactly the same issue. I have created custom forms. The details the the client fills out in the custom forms shows up within the client end of the ticket details but when an agent reviews the ticket they cannot view any of this information.

We could really do with this fixed or advice as this renders the software useless.

**Comment by gurubydesign** [comment]
Duplicate. see my suggested [solution](https://github.com/ladybirdweb/faveo-helpdesk/issues/462#issuecomment-337455905)
