### ISSUE TITLE
Ticket pagination permission denied error

### ISSUE THREAD

**Issue by aelbuni** [ladybirdweb/faveo-helpdesk#424]
Hello There,

In community edition.

When a customer access tickets from front-end and uses pagination; the system reply with Permission Denied ERROR 403.

In my case:

> Forbidden

> You don't have permission to access /support/public/check_ticket/{eyJpdiI6InJcL2N2dzVObFVYaURTQTNPY3pmSjd3PT0iLCJ2YWx1ZSI6IjlaMEd4cFdsYURPMlwvMjdcL04rS1Z2UT09IiwibWFjIjoiZmM5YTJkMGM0YTE3ODY5M2QwYzlkZTMzOGQwYTNjNGMyMTRmMDkzMzhlZWY4YTViYzFiN2FjMDUxZjRjZTU3NCJ9} on this server.

> Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Any solution for this error will be highly appreciated.

**Comment by mverma16** [comment]
@aelbuni Thanks for notifying the issue, I'll update the code soon for the fix.

**Comment by aelbuni** [comment]
Is this bug fixed or not yet ?

**Comment by mverma16** [comment]
@aelbuni, we are trying to check it but could not able to replicate.

**Comment by aelbuni** [comment]
Hello Mverma16,

Simple steps to reproduce the error.

1- Open a customer account
2- Create a ticket
3- Fill this tickets with replies from both the support agent and customer until you git pagination limit and pagination shows for Page 2.
4- Try to go to page 2 and you will see the error

Thanks

**Comment by mverma16** [comment]
@aelbuni,  sorry for delayed response, we are checking the issue (most probably it's been solved). But we have updated the version of Laravel in our project, we are running some final tests and we'll be releasing the next version soon.
