### ISSUE TITLE
Customer Groups

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#43]
Hey Faveo Team,

This is a great open source project. I downloaded the software and am poking at the code to see what kind of customization I can do on my own.

A feature I would love to see is Customer Groups. Basically I would like the ability to group customer users into a company. That way for a multi customer setup, such as a managed service provider, can break up tickets based on the company it is for even if it is from multiple users.

This isn't something I need right away, so I don't need to buy the customization. But it is something for you guys to consider in future releases.

Thanks!

**Comment by bhanu2217** [comment]
**We already have**

- Users
- Organisations

In the top menu click on Users.
User can be linked to organisation and you can view all the tickets & users of organisation on the Organisation profile

In the next release you will see much more advance User & Organisation relationship, which we are right now working on and will be released soon. This release will also have charts/graphs on both users & Organisation page showing the ticket flow.

**Comment by ajanes3** [comment]
I'm dumb. I didn't see that at all.

Thank you!
