### ISSUE TITLE
Class 'AlterAttachmentTable' not found

### ISSUE THREAD

**Issue by JayTeli** [ladybirdweb/faveo-helpdesk#439]
Command :php artisan migrate:refresh --seed
Laravel Framework version 5.2.45
Favio  Version : Community version
PHP Version 5.6.30

Error :
[Symfony\Component\Debug\Exception\FatalErrorException]  
Class 'AlterAttachmentTable' not found   

Stack trace :
PHP Stack trace:
PHP   1. {main}() /var/www/html/crm/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/html/crm/artisan:36
PHP   3. Symfony\Component\Console\Application->run() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/html/crm/vendor/symfony/console/Application.php:117
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/html/crm/vendor/symfony/console/Application.php:186
PHP   6. Illuminate\Console\Command->run() /var/www/html/crm/vendor/symfony/console/Application.php:794
PHP   7. Symfony\Component\Console\Command\Command->run() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
PHP   8. Illuminate\Console\Command->execute() /var/www/html/crm/vendor/symfony/console/Command/Command.php:256
PHP   9. Illuminate\Container\Container->call() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
PHP  10. call_user_func_array:{/var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  11. Illuminate\Database\Console\Migrations\RefreshCommand->fire() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  12. Illuminate\Console\Command->call() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:46
PHP  13. Illuminate\Console\Command->run() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Console/Command.php:185
PHP  14. Symfony\Component\Console\Command\Command->run() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
PHP  15. Illuminate\Console\Command->execute() /var/www/html/crm/vendor/symfony/console/Command/Command.php:256
PHP  16. Illuminate\Container\Container->call() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
PHP  17. call_user_func_array:{/var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  18. Illuminate\Database\Console\Migrations\ResetCommand->fire() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  19. Illuminate\Database\Migrations\Migrator->reset() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:69
PHP  20. Illuminate\Database\Migrations\Migrator->runDown() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:206
PHP  21. Illuminate\Database\Migrations\Migrator->resolve() /var/www/html/crm/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:227

**Comment by JayTeli** [comment]
@Faveo team : Please respond!!

**Comment by mverma16** [comment]
@JayTeli Thanks, we have not tried rollback and re-run migrations. 
Can you explain your situation for running this command?

**Comment by JayTeli** [comment]
@mverma16 : Re-running migrations should not throw exceptions for any situation. Please try running the migrations  re-run and you will get this error.
Mostly problem is with one of the drop() in migration files.
Kindly check.Thanks.

**Comment by mverma16** [comment]
Thanks for notifying this, I'll ckeck it and update. Thanks
