### ISSUE TITLE
Upgrade to Laravel 5.1

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#44]
From what I can tell in Laravel's [documentation](https://laravel.com/docs/5.1/upgrade), it won't be terribly difficult. I started to do it myself, but realized then I wouldn't be able to download future releases.

As well, Laravel will be providing long term support for 5.1. They will not be providing this for 5.0.

**Comment by bhanu2217** [comment]
This is definitely on our list. Just that we have been way to occupied with adding new features to Faveo. Probably in May end, Maximum June we will upgrade to Laravel 5.2

**Comment by bhanu2217** [comment]
We have upgraded to Laravel 5.2, haven't released the update yet as we are still testing. 
Next update/release of Faveo will be with Laravel 5.2

**Comment by guestisp** [comment]
if not explicit needed by some module, faveo should be based on laravel 5.1 that is LTS for 3 years. Standard laravel like 5.2 are supported only for 6 month.

Using LTS code in production is better.

**Comment by ajanes3** [comment]
@guestisp If they intend to continue updating it consistently, it should be ok going to Laravel 5.2. However, I do share your sentiment on going for stability.

**Comment by bhanu2217** [comment]
We plan to keep it updated to latest version of Laravel from here on. Our new release is almost ready, Just working on auto update module, to upgrade from existing version to new version.
