### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by raisiqueira** [ladybirdweb/faveo-helpdesk#441]
I am doing an installation, and when I open the browser, it is returning the image message.
![captura de tela de 2017-03-22 09-49-15](https://cloud.githubusercontent.com/assets/2914170/24201978/7513b232-0ef0-11e7-9eaf-333d971f26c8.png)

**Comment by hachemsoft** [comment]
Hello

go to /app/config/mail.php
line number 18 
replace 
`    'driver' => '',
`
by

`    'driver' => 'smtp',
`

**Comment by raisiqueira** [comment]
@hachemsoft I installed PHP version 7.1, the version of Laravel that is in the project is 5.2.x, the lib mcrypt is deprecated in version 7.1.x

**Comment by hachemsoft** [comment]
mcrypt is deprecated in php 7.1 but not in laravel 5.2 :) 
so if you are using homestead box, you have to downgrade to 0.6.0 to get php 7.0 to get faveo working

**Comment by SharkWipf** [comment]
FYI, if you want to get Faveo running on 7.1, you can get it working by setting `error_reporting(0);` in `vendor/laravel/framework/src/Illuminate/Encryption/McryptEncrypter.php`. Not the cleanest solution, but it works.
