### ISSUE TITLE
Installation issues -development branch

### ISSUE THREAD

**Issue by andrew-za** [ladybirdweb/faveo-helpdesk#442]
PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\BugsnagFacade::setAppVersion() in vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:217: /usr/local/cpanel/cgi-sys/ea-php70

I presume a composer update is going to break everything right?

**Comment by andrew-za** [comment]
Confirmed this seems to be a issue with the master branch as well. Wow - installing is a nightmare

**Comment by andrew-za** [comment]
Downloaded the master source from github - then tried to access /public
Are there better installation instructions? the link to User manual in readme only goes to homepage.

**Comment by nandagopalnandu** [comment]
https://github.com/ladybirdweb/faveo-helpdesk/wiki
