### ISSUE TITLE
Error accessing user directory

### ISSUE THREAD

**Issue by raisiqueira** [ladybirdweb/faveo-helpdesk#445]
depois de logar como um administrador, e ir para a página de usuários (/user), é redirecionado para a página inicial com erro.

![captura de tela de 2017-04-04 09-31-18](https://cloud.githubusercontent.com/assets/2914170/24656587/87155a3e-1919-11e7-8a29-2a7c618e4b9c.png)

**Comment by raisiqueira** [comment]
This is the error that returns when the debug is active

![captura de tela de 2017-04-04 09-45-28](https://cloud.githubusercontent.com/assets/2914170/24657131/83aa1176-191b-11e7-915d-0f5855abb3a8.png)

**Comment by MikeNGarrett** [comment]
Experiencing the same issue. The farthest I've gotten is to find the index function in the user controller isn't being called. 

Still digging into it. I'll update this ticket as I learn more.

**Comment by mverma16** [comment]
@MikeNGarrett @raisiqueira can you specify the version of the application.

**Comment by MikeNGarrett** [comment]
v1.9.6 for me.

**Comment by mverma16** [comment]
Ok I'll try to replicate the issue and get back to you ASAP.

**Comment by MikeNGarrett** [comment]
Why was this closed? The original issue was never addressed.

**Comment by raisiqueira** [comment]
I'm not using _Faveo_ anymore 😃
