### ISSUE TITLE
Sorry, something went wrong

### ISSUE THREAD

**Issue by irocksoft** [ladybirdweb/faveo-helpdesk#451]
- Faveo Version :1.9.2
- PHP version : 5.6
- Database Driver & Version :
- Server specification :

#### Description:
i can not login in the admin area, only says.

Sorry, something went wrong
We're working on it and we'll get it fixed as soon as we can.

#### Steps To Reproduce:
i dont know, i have delete all laravel-2017-04-13.log, Deletet any tickets

'debug' => env('APP_DEBUG', true) but dont give a error

#### Downloaded from

- [ ] development-branch

- [x] release-tag
- [ ] master-branch

**Comment by mverma16** [comment]
System is taking dubug mode status from environment configuration. Edit your `.env` file and set 
APP_DEBUG=true
It will show you the error.

Your problem looks familiar to me.
Our current notification module is buggy sometime it throws the error if you delete tickets from db.
Please clear data from the following tables to solve your problem.
* notifications
* user_notification

PS: make sure to check the error before clearing above mentioned tables.
