### ISSUE TITLE
app mobile

### ISSUE THREAD

**Issue by rlesouef** [ladybirdweb/faveo-helpdesk#455]
Does the Faveo mobile application version 1.8.1 work with Faveo Helpdesk Version Community 1.9.3.
I installed the Community Version 1.9.3 and I can not connect with the mobile application. I still have the error "**Error verifying URL**".
Regards

**Comment by CokkocZateki** [comment]
yeah me too. is it something that we can use or is this for a paid server ?

**Comment by baratam-narendra** [comment]
Hi there, this is narendra from ladybird team. Give me your Faveo installed server URL, and let me check the issue.

**Comment by CokkocZateki** [comment]
mine is http://supportticket.online-eve.com

**Comment by baratam-narendra** [comment]
Community or Pro?
Android App or IOS App?

**Comment by CokkocZateki** [comment]
um i think Community and Android App

**Comment by baratam-narendra** [comment]
http://supportticket.online-eve.com/public try with this URL

**Comment by CokkocZateki** [comment]
only get verifying URL. been doing that for 5 min now

**Comment by baratam-narendra** [comment]
Im sorry for the inconvenience, we are planning to release the next version in soon and just close the app and try to use it again. Thank you!

**Comment by CokkocZateki** [comment]
i finally connect to the app. but 30 min waiting time to connect to it?
