### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ricardoalvim-edu** [ladybirdweb/faveo-helpdesk#456]
- Faveo Version : v1.9.3
- PHP version: 5.6
- Database Driver & Version: MySQL
- Server specification: CentOS 6 at AWS

#### Description:

After clone repository and install composer and all tools required by Faveo, when I enter on web page (/public), and I can't obtain errors, but the Laravel Debug Def (APP_DEBUG in config/app.php) is set to 'true'. How I can install Faveo?

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
Were you able to install Faveo or is it not even showing 1st step for installation?

In second case I'd suggest you to run [Faveo Probe](https://github.com/ladybirdweb/faveo-probe) and test all the requirements are met on your server. 
Also make sure user friendly URL and URL redirect module is enable on your server.

**Comment by ricardoalvim-edu** [comment]
It's not showing 1st step. And, how you can see in this print, I run Faveo Probe and the server can run Faveo.
![probe](https://cloud.githubusercontent.com/assets/13853627/25179735/8524fd8c-24e1-11e7-8113-cd3561c1c7e4.PNG)

**Comment by mverma16** [comment]
Can you try to echo out the exception, follow the steps below
> Go to root directory>app>Exceptions>Handler.php
add `dd($e);` on line number 69 or 157

It will show the error, please share it here.

**Comment by ricardoalvim-edu** [comment]
Well... after that I decided reinstall Faveo and now I got 502 Bad Gateway on Nginx and there's no errors on logs

**Comment by ricardoalvim-edu** [comment]
But now I found that in  /opt/faveo/log/faveo_error_log:

2017/04/20 13:37:38 [crit] 2744#0: *13 connect() to unix://opt/faveo/run/faveo_php.socket failed (2: No such file or directory) while connecting to upstream, client: 152.250.254.163, server: 54.175.159.161, request: "GET / HTTP/1.1", upstream: "fastcgi://unix://opt/faveo/run/faveo_php.socket:", host: "54.175.159.161"
