### ISSUE TITLE
504 Gateway Time - Uploads

### ISSUE THREAD

**Issue by ricardoalvim-edu** [ladybirdweb/faveo-helpdesk#458]
- Faveo Version :  v1.9.3
- PHP version : 5.6
- Database Driver & Version : MySQL
- Server specification : CentOS 6 at AWS

#### Description:
When I try upload a file, I got 504 Gateway Time. This is a bug or a configuration fail? I tried open a ticket with uploads and change picture image user, but Faveo returns 504 erros

#### Steps To Reproduce:
Try upload a file on new ticket, change profile pic or try change organization pic.

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag
![504 error](https://cloud.githubusercontent.com/assets/13853627/25357587/be9a669c-2914-11e7-8276-869cae15b23b.PNG)

**Comment by pleekit** [comment]
**FIXED:** The profile pic issue for Agents.
edit ./resources/views/themes/default1/agent/helpdesk/user/profile-edit.blade.php
Change line 127 to this {!! Form::file('profile_pic')

This mimics the code for Admin profile pictures.
