### ISSUE TITLE
Token value is made public when a ticket is created by the api v1 

### ISSUE THREAD

**Issue by ricardotormo** [ladybirdweb/faveo-helpdesk#4584]
- Faveo Version : Community 1.10.7
- PHP version : 7.2.24
- Database Driver & Version : MySQL 5.7.33
- Server specification : ubuntu0.18.04.7

#### Description:
When I create a ticket using t using the API v1 (api/v1/helpdesk/create), 
this token appear published in the ticket thread instead of the body.

#### Steps To Reproduce:

1. Create a user using faveo helpdesk.
2. Use the api (API v1 : api/v1/helpdesk/create) and create a new ticket.
3. Go to faveo dashboard, click tickets and look for the ticket you've created. 
4. Scroll down and read the content of that ticket.
5. You'll find a small table containing: user_id and the token value.

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by Noor-mommadhi** [comment]
R&D TIME: half day
development time: 1 day
