### ISSUE TITLE
Custom form data not showing in ticket

### ISSUE THREAD

**Issue by sxmarsha** [ladybirdweb/faveo-helpdesk#462]
I created any custom form with any values, but nothing shows up on ticket details. So, what is the purpose of Custom Form if nothing shows on ticket details or on database?

**Comment by mverma16** [comment]
You must link the custom form with a help topic. While creating a ticket from agent panel/client panel when a user selects help topic, the custom form linked with that help topic will be rendered in the form. 

After ticket creation this custom field values will be rendered in a tabular format.

**Comment by sxmarsha** [comment]
I have done that, that is not the issue I am having. I have spoken to Faveo direct and they think it may be a bug and are looking for it now.

**Comment by leandromendonca** [comment]
I have the same issue. My version is 1.9.6 in Portuguese.

**Comment by gurubydesign** [comment]
same here...my version is 1.9.7

**Comment by gurubydesign** [comment]
@sxmarsha, it's in the database within the 'ticket_form_data' table. but you're right, the details are not being rendered in the ticket view. it's strange however that you may see it rendered on the PDF version of the ticket

**Comment by sxmarsha** [comment]
@gurubydesign I'd give up with this one mate, I did. Turns out it will only render where we want it to if we have the paid version. I'm gutted its like this and I think is out of order but hey ho. I'm using my own developed one now for the Company I work at. Its a shame as this is a good helpdesk, but not so open source after all. Just thought I'd let you know rather than waist your time looking for a solution.

**Comment by gurubydesign** [comment]
i kinda suspected that, but hey thanks for the heads up. I'll probably be spending a few hours trying to figure how to hack my way to rendering the custom form on the ticket view, because you're right, it IS a good helpdesk, and restricting our use of a basic feature like this to a paid version is a turn off. 

Thanks again mate.

**Comment by gurubydesign** [comment]
@sxmarsha 
Here's an update: 
Apparently, ticket custom form data is being rendered as a table under the message body of the ticket view for the client, but not for agents and administrators. Strange enough, the same code that renders the table for the client ticket view blade can still be seen in the default timeline blade for tickets. 

Now I'm not sure if it is a legit bug or disabled on purpose, but I think I'm getting close.

**Comment by gurubydesign** [comment]
@sxmarsha, I finally got it to render. I now know that it's a legitimate bug. 

To fix it, simply copy lines 740 to 756 of: resources/views/themes/default1/agent/helpdesk/ticket/timeline.blade.php

and with it, replace lines 267 to 283 of:
resources/views/themes/default1/client/helpdesk/ckeckticket.blade.php

I didn't bother to check the original code that breaks the render, but it's probably a syntax error.
I hope it helps you, mate.  -Bryan

**Comment by sxmarsha** [comment]
@gurubydesign 
Ideal! Thanks for this Bryan, I will test this in the dev environment next week! Thanks for all your help. Will let you know how it works!

**Comment by mrkenng** [comment]
the agent template is blank. I can see the table rendered however it is not displaying the information on agent side. replacing those rendered blank information as well. Hopefully this will be fixed soon.
