### ISSUE TITLE
Agent's can't add/edit articles and categories in KB

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#465]
- Faveo Version : 1.9.3
- PHP version : 5.6.25
- Database Driver & Version : MySql
- Server specification : Apache web server running on windows 10

#### Description:
When an agent clicks on knowledge base from agent dashboard he sees 404 page and unauthorized access error.
![2](https://cloud.githubusercontent.com/assets/10759797/25657932/ea23d162-301d-11e7-8945-b6210062736a.gif)

#### Steps To Reproduce:
Login as an agent>click on tools>knowledge base

It's better to give an option for KB access permission for agents. Admin can choose if agents can access KB or not.
 
#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [x] release-tag

**Comment by sillyonthestreet** [comment]
I'm having the same issue. Did you fix it?
