### ISSUE TITLE
ErrorException in GET /faveo-helpdesk/public/category-list

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#4686]
## Error in Faveo Community

**ErrorException** in **GET /faveo-helpdesk/public/category-list**
compact(): Undefined variable: article_id

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/604f4752a7c8b700082ecc8c?event_id=604f47520073aa5b6c700000&i=gh&m=ci)

## Stacktrace

    \app\Http\Controllers\Client\kb\UserController.php:295 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    \app\Http\Controllers\Client\kb\UserController.php:295 - App\Http\Controllers\Client\kb\UserController::getCategoryList
    \app\Http\Middleware\CheckBoard.php:27 - App\Http\Middleware\CheckBoard::handle
    \app\Http\Middleware\LanguageMiddleware.php:33 - App\Http\Middleware\LanguageMiddleware::handle
    \app\Http\Middleware\VerifyCsrfToken.php:33 - App\Http\Middleware\VerifyCsrfToken::handle

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/604f4752a7c8b700082ecc8c?event_id=604f47520073aa5b6c700000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by mverma16** [comment]
Closing as reported during testing with PHP 7.3 in the local system. Added the label to it so it can be tracked while working  on PHP compatibility issues.
