### ISSUE TITLE
Call to undefined method  BugsnagFacade::setAppVersion()

### ISSUE THREAD

**Issue by Chronos-92** [ladybirdweb/faveo-helpdesk#469]
- Faveo Version : 1.9.4
- PHP version : 5.6 & 7.0

#### Description:
Trying to load the frontpage before installing gives me a completely blank screen with an HTTP Code of 500. Looking at the Apache log files I get te following error:

`PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\BugsnagFacade::setAppVersion() in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:217\nStack trace:\n#0 /var/www/html/app/Exceptions/Handler.php(53): Illuminate\\Support\\Facades\\Facade::__callStatic('setAppVersion', Array)\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 217`

Trying to enable debugging in the env file or config does not change the result, I get this error on both PHP5.6 and PHP7.

#### Steps To Reproduce:
Just downloaded a copy of the application and placed it in the default virtual host, installed all the required plugins and get this. The probe application runs fine and says faveo should work.

#### Downloaded from
- [x] master-branch
- [ ] development-branch
- [ ] release-tag

**Comment by mverma16** [comment]
Try running [Faveo probe](https://github.com/ladybirdweb/faveo-probe) to see your server satisfies the requirements to install Faveo.

**Comment by Chronos-92** [comment]
To quote the original post: 

> The probe application runs fine and says faveo should work.

**Comment by mverma16** [comment]
enable debug mode by changing
`'debug' => env('APP_DEBUG', false),`
to
`'debug' => env('APP_DEBUG', true),`

It will show the exact error.

**Comment by Chronos-92** [comment]
Changing those settings does not change a thing, it still gives me an HTTP code of 500 and the exact same error in the apache log file.

**Comment by Chronos-92** [comment]
I've just attempted to use PHP7.1.5, however this does not appear to offer a solution either. Once again, the Probe shows no errors yet the actual application doesn't load.

**Comment by mverma16** [comment]
Sorry for the delay in the response, we can catch exception and print it on the screen from exception handler.
Edit `faveo_root/app/Exceptions/Handler.php`

add `dd($e);` in function called common before switch statement possibly at line 157.
This will show the exact exception, so we can rectify the problem.

**Comment by Chronos-92** [comment]
I think the error is preventing it from even getting this far into the application. But, I've done as you said and got the same result as before:

![image](https://cloud.githubusercontent.com/assets/10164439/26000539/a680a760-3729-11e7-8993-965f16665778.png)
![image](https://cloud.githubusercontent.com/assets/10164439/26000549/b028bd3e-3729-11e7-9930-8bffffb860ef.png)
![image](https://cloud.githubusercontent.com/assets/10164439/26000573/c10a47a8-3729-11e7-8ec8-0b555710cd42.png)

**Comment by mverma16** [comment]
This is strange. Please try the following solutions
* Delete environment file (.env) if present in you Faveo's root directory
* Check the permission of storage directory and give proper permissions required for running Laravel. 
Additionally you can try and check if [Laravel](https://laravel.com/docs/5.2/installation) runs on your server

If it does not help
Please write us a mail at support@ladybirdweb.com with your server details, our team will check and recitfy the issue.

**Comment by Chronos-92** [comment]
> Check the permission of storage directory and give proper permissions required for running Laravel.
Additionally you can try and check if Laravel runs on your server

This ended up being the primary issue, after careful examination certain files did not receive the appropriate permissions. Changing the owner to the user under which Apache was run resolved the issue and it would finaly throw proper errors at me. I've managed to resolve everything else it threw at me from there without a hitch.

I thank you for your help and time, and am closing this ticket as I am now able to load the page and log in with the demo user.
