### ISSUE TITLE
Reload the page to get source for :http://00.00.00.000/public/laravel-filemanager?type=Images&CKEditor=reply_content&CKEditorFuncNum=0&langCode=en 

### ISSUE THREAD

**Issue by pratik007kumar** [ladybirdweb/faveo-helpdesk#472]
when i click on ckeditor image option  it display blank page 
 and when firebug it display following error with 500 `
http://62.212.95.193/public/laravel-filemanager?type=Images&CKEditor=reply_content&CKEditorFuncNum=0&langCode=en`

**any body can help me**

**Comment by mverma16** [comment]
@pratik007kumar can you be more specific, and share the route where you are getting this error.

**Comment by mverma16** [comment]
@pratik007kumar it'd be great if you can describe your issue and the solution(if it is solved now), so that other users having the same issue can refer the solution provided.
