### ISSUE TITLE
How to change the mail id notification

### ISSUE THREAD

**Issue by arpitset** [ladybirdweb/faveo-helpdesk#473]
I am looking for setting where agent can send changes without notification to the customer, only in faveo system.

How do we off the mail notification to the customers.

**Comment by mverma16** [comment]
@arpitset 
* If you want to leave a reply or comment on a ticket which only your internal members can see, you can add internal notes. Clients are not able to see internal notes added by agents on tickets and no notification is sent to them for internal notes.
* Editing or updating ticket details is considered as internal notes and client does not get notified for chnages like changing ticket title, helptopic, priority, ticket assignment etc.
* Changing status of ticket may notify the clients that the status of their ticket has been changed. Mostly it goes out for closed and resolved status. But you set your preference whether you want to notify client or not about status change. You can edit this vai admin panel>manage>status>edit

I hope this clears your doubts. Still if you have any doubt let me know.

**Comment by arpitset** [comment]
@mverma16 

Hi manish, 

Thanks for reply, Is this option "admin panel>manage>status>edit" is available in community edition?
I am unable to find this in admin panel.

**Comment by mverma16** [comment]
Sorry my bad, you can find the option in
`Admin panel> ticket > statuses > edit`
