### ISSUE TITLE
no check for imap extension

### ISSUE THREAD

**Issue by JelleDijkhuizen** [ladybirdweb/faveo-helpdesk#477]
- Faveo Version : all
- PHP version : all
- Database Driver & Version : mysql
- Server specification : not necessary

#### Description:
no check for imap extension

#### Steps To Reproduce:
istall without imap extension

#### Downloaded from
- [ ] release-tag

**Comment by mverma16** [comment]
@JelleDijkhuizen  Thanks for notifying us about the check for extension.
Faveo uses php `imap` extension to connect with mail servers using IMAP settings to fetch and create tickets from mailbox.
Although it is not required to run Faveo but it is recommended to install imap for making email fetching functionality work.
I've added the extension in recommended extension check list in [master branch](https://github.com/ladybirdweb/faveo-helpdesk/commit/3f1a0eb475d776490985c63772ca1862dbbd9a2c).
