### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by alko79** [ladybirdweb/faveo-helpdesk#48]
hello,
i'm translating the package into my language, italian, I'm using "en" folder as base and it contains the lang files that i translated, but i noticed there are not the ones about the datables and other parts maybe because those belongs to other packages , how to procede ?
what is your suggestion?
thanks

**Comment by SarfrazS** [comment]
The current language module is a bit complex. We will try to simplify things by the end of may.

**Comment by alko79** [comment]
ah ok, in the meantime I finished the italian translation from the current "en" folder.
I found also others minor mispelling in english one, but at this point I will wait until june to have the new translation files and pull them once completed for italian lang.
I will wait.
thanks

**Comment by SarfrazS** [comment]
Can you please share your language file with us at our support address "support@ladybirdweb.com"

**Comment by alko79** [comment]
ok, I will send there.

**Comment by sebastienserre** [comment]
Hello, 
Why not using a po/mo system or a Saas platform as Transifex, or GlotPress (https://wordpress.org/plugins/glotpress/ )

**Comment by bhanu2217** [comment]
Currently we are using Laravel default localization support https://laravel.com/docs/5.2/localization which is not based on po/mo, we will discuss among our team benefits of moving to mo/po and decide and see if we want to change, though it might takes us time.
