### ISSUE TITLE
Undefined variable: status (View: /home/support/public_html/resources/views/themes/default1/agent/helpdesk/dept-ticket/tickets.blade.php)

### ISSUE THREAD

**Issue by JelleDijkhuizen** [ladybirdweb/faveo-helpdesk#485]
- Faveo Version : 1.9.6
- PHP version : 7.0.1
- Database Driver & Version : MariaDB
- Server specification :
Centos 7

#### Description:
There is an undifined var in a blade template.

#### Downloaded from
- [x ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by AndersonDan** [comment]
Up
