### ISSUE TITLE
user dashboard is not working

### ISSUE THREAD

**Issue by pratik007kumar** [ladybirdweb/faveo-helpdesk#486]
when i login as user.
 **dashboard page is displaying 
 The page isn’t redirecting properly**

and as admin role it is working fine

**Comment by HsnMustafa** [comment]
Yes , Just set up this project , for agent and admin it works fine, but for user when logged in and click on submit ticket or click on profile dashboard doesnt show, it shows same error as described above.

**Comment by HsnMustafa** [comment]
Plus there is no screen to set roles for newly created users, like to assign them agent/user and assign them category, department etc.

**Comment by nandagopalnandu** [comment]
Hi Pratikkumar,
How do you access the dashboard?Manually or by clicking?
For user, many features are restricted.

**Comment by nandagopalnandu** [comment]
Hi HsnMustafa,
Ofcourse we can set roles for newly created/present user by clicking -
![4](https://cloud.githubusercontent.com/assets/28657992/26570237/05f1bade-452d-11e7-9b85-6c2728a42c7f.gif)
users>>view>>Change the role to admin/agent.

**Comment by HsnMustafa** [comment]
Ok. Good thanks for that. I figured that one out. But my problem and the other guy is we are not been able to go to dashboard or submit a ticket using user role which is client. Others which are agent and admin are working fine.
I am running this on localhost, I have set up email using gmail.
Tell me what else I need to do in order to submit a ticket for client.

**Comment by nandagopalnandu** [comment]
Hi,
As i already said, there are some restrictions for the normal users. Can you please tell me how you accessed the dashboard? By typing the path in url or clicking??

**Comment by HsnMustafa** [comment]
Dear,

These are steps to reproduce.

I am running on localhost
Configured gmail in email settings
Logged in as client 
Now click on submit a ticket 

After that it keeps on searching and gives a error page saying too many redirects. And the link on the URL at that time is .../public/dashboard.

This is for user logged in account.

I hope I have explained the scenario well.

**Comment by nandagopalnandu** [comment]
Hi,
Sorry,we were unable to find the issue. Please attach the screenshot/gif of the issue occured.
Thank you

**Comment by HsnMustafa** [comment]
Okay. Let me do that. As I mentioned earlier it is happening on localhost. So I am not sure if you reproducing it on localhost.

**Comment by nandagopalnandu** [comment]
Can you provide your Skype id, can we share the screen?

**Comment by HsnMustafa** [comment]
Okay I will do that. My Skype ID is hassan.mustafa123.

I cannot share screen at the moment but I can explain you the issue if you call me.

**Comment by HsnMustafa** [comment]
That issue is solved when I moved the app to hosting. Now problem is when an email is being sent to an email which is set as default in faveo. It doesn't open a ticket even though cron job is set up.

**Comment by pratik007kumar** [comment]
sorry for late replay.
i find this error when i login as user
it redirect me to helpdesk/public/dashboard
when i  checked code i find in 
`/app/Http/Controllers/Agent/helpdesk/DashboardController.php`
**in line 45 to 55**
 ```
public function index()
    {
        // if(Auth::user()->role == "user"){
        // return \Redirect::route('home');
        // }
        try {
            return View::make('themes.default1.agent.helpdesk.dashboard.dashboard');
        } catch (Exception $e) {
            return View::make('themes.default1.agent.helpdesk.dashboard.dashboard');
        }
    }
```
**i make a change just uncomment this to**

 ```
public function index()
    {
         if(Auth::user()->role == "user"){
         return \Redirect::route('home');
         }
        try {
            return View::make('themes.default1.agent.helpdesk.dashboard.dashboard');
        } catch (Exception $e) {
            return View::make('themes.default1.agent.helpdesk.dashboard.dashboard');
        }
    }
```

`And now it working `
thanks to you all
