### ISSUE TITLE
Faveo - Windows 10 Cron Job for email

### ISSUE THREAD

**Issue by derek68** [ladybirdweb/faveo-helpdesk#489]
- Faveo Version : Service Desk Community 17cf90b
- PHP version : 7.0.12
- Database Driver & Version :MYsql 5.7.16 Community Server (GPL)
- Server specification :

#### Description:  Hi All 

Im running on a windows 10 pc, and the web-server is Apache Web Server.  Ive install Faveo and its up and running, ive put in my Mail settings and run the test, it passes and saves.  The issue is it is not receiving mail from my imap mail server.  I know there is reference to a cron jop, but in window there is no cron, only Task Scheduler but I cant work out how to get Faveo  to work with mail.

Can anyone help me.

I did want Faveo running on Ubuntu, but i simply do not have enough experience to get it working.

#### Downloaded from
- [ ] master-branch - Fabio Website

- [ ] development-branch??

- [ ] release-tag??

Thank you for helping in advance.

**Comment by vijaysebastian** [comment]
Cron is nothing but Task Scheduler. So please schedule the task there with command. You can see the command in http://yourFaveoAppDomain.com/job-scheduler. 

the command looks like 
`/usr/bin/php-cli -q  /path/to/artisan schedule:run > /dev/null 2>&1`

For you 
`php  /path/to/artisan schedule:run > /dev/null 2>&1`
this may help

You can set interval on the same page and command should run at least in every 5 minutes.

**Comment by derek68** [comment]
Hi Vijaysebastin

Thank you for your reply, I have tried to create a task, but it is not working.  I know it is a big ask, but are you able to help me further. 

![image](https://user-images.githubusercontent.com/22875102/26955433-0674d0fc-4cfa-11e7-887a-600c453e8c8d.png)

Im really not sure how to setup the task in Task Scheduler.  Would you be able to to provide me with print screens showing me how to set up the job in tash scheduler

The full path on the faveo con is.

/usr/bin/php-cli -q  C:\Bitnami\wampstack-7.0.12-0\apache2\htdocs\faveo\artisan schedule:run >> /dev/null 2>&1


Regards

Derek

**Comment by mverma16** [comment]
Hello @derek68 try to follow the steps mention in [this document](https://docs.google.com/document/d/1bn8F1ijW1EsHgrWLhYKdO7t89WZ4uv0rKWPfNURm57U/edit?usp=sharing) and update if it works for you or not.

**Comment by derek68** [comment]
Hi Mverma

Thank you for a great document, the only issue I have is, im using the community version and I dont have the section to select the available cron job commands as in you document, I only have this:

![image](https://user-images.githubusercontent.com/22875102/27018899-53e4abda-4f77-11e7-85a6-566717ea6010.png)

I have made the batch file.

![image](https://user-images.githubusercontent.com/22875102/27018921-82b25b7e-4f77-11e7-955e-787a75277c79.png)

But it does not work.  So im not sure what I have done wrong.

Regards

Derek

**Comment by mverma16** [comment]
@derek I've used Faveo Pro edition while writing the document. In community as the above screen shot shows only command is available, URL section is missing which we'll add soon. You can use this single command for Faveo job scheduling.

I believe the reason why your batch file does not work directory navigation. In the doc I first navigated to my E drive using 
> E:

Then I navigated to my faveo directory using `cd` command.

As your batch file suggests your Faveo directory is in C drive. You can try to navigate to your Faveo directory from `cmd`. 
* Press window+r.
* Enter cmd in the dialog box and press enter
* Try `cd` command to navigate to your Faveo directory and run `php artisan schedule:run`.

Create/update the batch file accordingly.

**Comment by derek68** [comment]
Hi Mverma

I cant thank you enough, what I have done is made a batch file and following your instructions with the task scheduling and its working.

My batch file is, just in case it helps anyone else is.
-------------------------------------
@echo off
cls
echo.
echo read faveo mail
start cmd /c "C:\Program Files\Internet Explorer\iexplore.exe" localhost/faveo/public/readmails
ping 127.0.0.1 -n 8 -l 0
taskkill /f /im iexplore.exe /t
------------------------------------------------------

Im not sure if it is the best way of grabbing mail, but it is working.  I have not fully tested and have only sent a few emails, but so far it is working.

Thank you,



Regards
