### ISSUE TITLE
Group Edit is broken

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#49]
But the good news is I already have a fix!

How to recreate:
1. Login with admin rights
2. Open Admin Panel
3. Open Groups Menu
4. Edit any group
5. Submit
Error: Can't find column 'can_trasfer_ticket'

There is a typo in app\Http\Controllers\Admin\helpdesk\GroupController.php at approximately line 142

```
//Updating can_trasfer_ticket field
$trasferTicket = $request->Input('can_trasfer_ticket');
$var->can_trasfer_ticket = $trasferTicket;
```

Change to the following to fix:

```
//Updating can_transfer_ticket field
$transferTicket = $request->Input('can_transfer_ticket');
$var->can_transfer_ticket = $transferTicket;
```

Additionally, this led me to notice that editing transfer rights is not present in the view located at resources\views\themes\default1\admin\helpdesk\agent\groups\edit.blade.php

I added the following to correct the view:

```
<!-- can transfer ticket -->
	<div class="row">
		{!! Form::label('can_transfer_ticket',Lang::get('lang.can_transfer_ticket')) !!}
		<div class="col-xs-1">
			{!! Form::checkbox('can_transfer_ticket',1,null,['class' => 'checkbox']) !!}
		</div>
	</div>

```

Please put this in the next release. :)

Also, thanks so much for this open source product. It has saved me time when I can fix things myself. :D

**Comment by SarfrazS** [comment]
Thanks for notifying us.

We will fix the issue in next release.
