### ISSUE TITLE
Email/IMAP Error

### ISSUE THREAD

**Issue by pgilgunn** [ladybirdweb/faveo-helpdesk#494]
- Faveo Version : 1.9.6
- PHP version : 7.0.18
- Database Driver & Version : MariaDB 10.1
- Server specification : Ubuntu 16.04 LTS, Apache 2.4

#### Description:
On a Clean install of Faveo on the server above, When I configure the Email setup and save. When I try to go back into the configured email I get the error message “Sorry, Something went wrong” Also in the Logs I get the following 
Illuminate\Contracts\Encryption\DecryptException: The payload is invalid. 
In /var/www/helpdesk.xxxxxx.com/public_html/vendor/laravel/framework/src/Illuminate/Encryption/BaseEncrypter.php:44

#### Steps To Reproduce:

- Install Clean install Faveo
- Configure Email setting for an IMAP Gmail account
- Attempt to edit the email settings

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mathieu-aubin** [comment]
Hi, i would suggest you try and switch the cache driver from database to files if possible. 

Also, this could potentially work, too... in database.php, add a setting for PDO::MYSQL_ATTR_MAX_BUFFER_SIZE like such...

```
'mysql' => [
data... data...
something something...
'options' => [ PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216 ]
]
```
OR...

[**patch the file with _this_ patch**](https://github.com/ladybirdweb/faveo-helpdesk/files/1100539/confpatch-001.txt)

**Comment by pgilgunn** [comment]
Mathieu-aubin

Thanks for your help on this,

I have looked at the cache settings and it is configured to use file not db as far as I can see. I have also looked at making the MAX_BUFFER_SIZE change, when I have the following in the /config/database.php the application completely stops working and I don't have any working interface

        ],
        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'port'      => env('DB_PORT', ''),
            'prefix'    => '',
            'strict'    => false,
			'options'	=> [ PDO::MYSQL_ATTR_MAX_BUFFER_SIZE => 16777216 ]
        ],
        'pgsql' => [

My Mariadb server is on a separate server if this has any impact.

Thanks
Phil

**Comment by pgilgunn** [comment]
Hi 

I have now also tried using PHP 5.6 on my PC using WAMP,  This has been setup clean from the source and also has the same problem. any help would be appreciated.

Thanks
Philip

**Comment by mathieu-aubin** [comment]
Okay.. check the file permssions on the cache folder... theres a whole ton of infos missing to give you a definitive command to run but a thing that wouldn't hurt is to set the permissions to the webroot to the webserver user..
something like (on unix)
```
chown nginx:nginx WEBROOT_FOLDER -R
```

**Comment by pgilgunn** [comment]
Hi Mathieu

Thanks for this, Unfortunately, it has not changed the situation. I have been working on my local WAMP version not to try to see what the issue is. I have enabled debugging and have attached the output into paste bin below.
https://pastebin.com/dV588j15

The research I have done it appears that this is repated to Cached data being stored in the database, from my .env file in both setups it looks like im storing in file not DB.

Here is my .env

APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:6DDo6fQVW+ruMmVu5ctpncB4IkBhBa4XSGA0TfJgM98=
APP_BUGSNAG=true
APP_URL=http://helpdesk.xxxxx.com/public/
DB_INSTALL=1
DB_TYPE=mysql
DB_HOST=127.0.0.1
DB_PORT=
DB_DATABASE=helpdesk
DB_USERNAME=root
DB_PASSWORD=
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

This also appears to be a very similar issue but in my case changing to  $table->longText('value'); did not resolve the issue
https://laracasts.com/discuss/channels/general-discussion/daeling-with-decryptexceptioninvalid-data

**Comment by mathieu-aubin** [comment]
From what i see, i suggest you try and set good values in your .env file
like DB_HOST per example, you said it was a remote DB - unless you did some clever port forwarding, you shouldn't have 127.0.0.1 in there, right? Same goes for the MAIL_HOST, port...

If you wanted, i could ssh into your server and debug it but this would mean granting me with complete access...

**Comment by pgilgunn** [comment]
Hi Mathieu

Thanks for your offer of help on this, I will PM you the access details. On the 127.0.0.1 DB connection this log was taken from a local copy that is also presenting the same issue, this is not from the Linux server.

**Comment by mathieu-aubin** [comment]
Oh, you can reach me at mathieu at zeroserieux.com

**Comment by pgilgunn** [comment]
Hi Mathieu
You appear to be having some problems getting an email to this address, have you got an alternative address?

**Comment by pgilgunn** [comment]
Hi anyone got any ideas on this one? I have reinstalled many times on both Linux and windows and seams the same problem on both.

Thanks

**Comment by mathieu-aubin** [comment]
hey man, try this mail contact@speedinternet.ca
