### ISSUE TITLE
Problem installing Faveo helpdesk on windows 10

### ISSUE THREAD

**Issue by awbruce** [ladybirdweb/faveo-helpdesk#495]
- Faveo Version : 1.0.1
- PHP version : 5.6.25
- Database Driver & Version : 5.7.14
- Server specification : Windows 10/Apache 2.4.23

#### Description:
I followed all steps but got this error
_**FatalErrorException {▼
  #message: "Maximum execution time of 120 seconds exceeded"
  #code: 1
  #file: "E:\wamp\www\faveo\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php"
  #line: 56
  #severity: 0
  -trace: {▶}
}**_

**Comment by mverma16** [comment]
Was it showing low execution time `warning` while installation in step 2?

Please increase `max_execution_time` in your php.ini file and restart the server then try to install.
