### ISSUE TITLE
Mobile application URL verification failure

### ISSUE THREAD

**Issue by zoliben** [ladybirdweb/faveo-helpdesk#496]
- Faveo Version : 1.9.6 (Community edition)
- PHP version : 5.6.30
- Database Driver & Version :
- Server specification : CentOS 7
- Webserver: Apache 2.4.6

#### Description:

I cannot connect to the site from the Android application. I'm using the community edition version.
After a while of waiting for the URL verification, I get the "Error verifying URL" error message.
I'm trying to access the public folder inside the installation.

Could you please help me with this issue?

**Comment by SarfrazS** [comment]
Hi Zoltán Bence,

Please can you send me the app url which you are using so that i can check
and help you.

**Comment by zoliben** [comment]
http://budapest.intercontinental.com/itsupport/public/

**Comment by SarfrazS** [comment]
Go to this path directory/itsupport/config/app.php and add this api over
there. i hope it will work.

\App\Api\ApiServiceProvider::class, this is the api which you have to paste
under Application Service Providers

**Comment by zoliben** [comment]
After doing that, I get http 500 error.
Here are the error messages generated by apache:

PHP Fatal error:  Class '\\App\\Api\\ApiServiceProvider::class,' not found in <dir>itsupport/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

PHP Fatal error:  Call to undefined method Bugsnag\\BugsnagLaravel\\BugsnagFacade::setAppVersion() in <dir>/itsupport/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 217

**Comment by SarfrazS** [comment]
Please remove API Url from config/app.php.  V1.9.6  API is not working we
will release ASAP.

**Comment by zoliben** [comment]
Already done that, thanks for the info!

**Comment by gitjmrubio** [comment]
Anyone already fix this issue for release v1.9.6-7 ??  Many thanks

**Comment by darkswar** [comment]
Have fix this issue ?
