### ISSUE TITLE
Cronjobs

### ISSUE THREAD

**Issue by mathieu-aubin** [ladybirdweb/faveo-helpdesk#497]
- Faveo Version : 1.9.6
- PHP version : PHP 5.6.30
- Database Driver & Version : php-pdo 5.6.30, 5.5.56-MariaDB
- Server specification : CentOS Linux release 7.3.1611

#### Description:

The cronjob simply assumes that php-cli is located at /usr/bin/php-cli.

![screenshot_2017-06-29_18-33-16](https://user-images.githubusercontent.com/15820228/27713496-ff049e32-5cf9-11e7-98e9-0e8dc083a40e.png)

And since the output (even the errors) are sent to /dev/null, there is no indication that the cron is not working as it should.

Running
```
[root@c7 ~]# /usr/bin/php-cli -q  /opt/faveo/faveo-helpdesk/artisan schedule:run >> /dev/null 2>&1
[root@c7 ~]# 
```
Outputs nothing, which would be fine in general but since php-cli doesn,t exist there... 
Removing the stderr redirection results in this:
```
[root@c7 ~]# /usr/bin/php-cli -q  /opt/faveo/faveo-helpdesk/artisan schedule:run >> /dev/null
-bash: /usr/bin/php-cli: No such file or directory
```

So the cron is never executed if someone uses that line.

my suggestion would be to change the line to:
```
`which php` -q  LOCATION_OF_FAVEO/artisan schedule:run 2>&1 >/dev/null
```
The command `which php` returns the location of php on the system.

Here's an output screenshot (with the quiet flag and extra redirection removed):
![screenshot_2017-06-29_18-48-42](https://user-images.githubusercontent.com/15820228/27713885-c09772bc-5cfb-11e7-94ba-730c61e05673.png)

#### Downloaded from
- [x] master-branch

**Comment by mverma16** [comment]
@mathieu-aubin does this work on windows server as well?

**Comment by vijaysebastian** [comment]
`PHP_BINARY (string)`
Specifies the PHP binary path during script execution. Available since PHP 5.4.

**Comment by bhanu2217** [comment]
@mathieu-aubin 

- In upcoming version we will add log for cron job and if logs are not being updated we will display error/warning message in Faveo that cron is not working
- Regarding default cron path show in Faveo, this works on assumption, do you know how we can get the exact/actual path?

**Comment by mathieu-aubin** [comment]
@mverma16 i do not use windows, but i would think its safe to say that no, its not.
@bhanu2217 overall, you would get a ton more luck using '/usr/bin/php' for the php executable as its probably the case in 95% of installations, at least in default installs. Cloudlinux and familly are most likely in the missing 5% here
@vijaysebastian PHP_BINARY, a constant i had no clue about, hhee. I ran some tests on standard and non-staandard locations and (under linux at least) it seems to hold up to its name... it correctly returned what we wanted. I've only tested inline with `php -r 'echo PHP_BINARY.PHP_EOL;'` and var_dump....Potentially a good fix.

Also, when running your cron without any output whatsoever, you can still easily get the exit code and use it to determine if it ran into a problem or if it was a good run. there are few different ways of doing it..

Some example commands be something like trying to ping a server...

```
ping -c1 google.com &>/dev/null || echo 'there was an error'
ping -c1 google.com &>/dev/null && echo 'command success'
ping -c1 google.com &>/dev/null; [[ $? -ne 0 ]] && echo 'there was an error'
```
Substitute the ping command by your cron call...

here's an asciicast showing some return 

[![asciicast](https://asciinema.org/a/128597.png)](https://asciinema.org/a/128597)
