### ISSUE TITLE
Layout/style issue for user ticket in agent section

### ISSUE THREAD

**Issue by lolofromuk** [ladybirdweb/faveo-helpdesk#499]
- Faveo Version : 1.9.6
- PHP version : 7
- Database Driver & Version :
- Server specification : centos 7

#### Description:
This is just a simple layout or css issue in the Agent -> ticket section
Where you handle a ticket and see the user tickets and you can reply.
I wrote to Faveo and they told me that it comes mainly from tickets created via outlook but i tried many other services and it has been the same.

While the reply for the agent is correctly formated into its "box" enlarge as the content is big or not for the user message there is no scroll bar, the text is in basic times new roman and we can just barely see one line at a time.

Not sure that it males sense so a screenshot is the simpliest thing:

https://prnt.sc/fu421x

Other than that i must say i dont have much issue with that system :)

#### Steps To Reproduce:

Simply create a ticket directly sending a mail to the main e-mail handling your support system.
Log in the agent panel and open the ticket 
![userticket-agent-view](https://user-images.githubusercontent.com/30246078/28292009-8a5ddf00-6b4d-11e7-9ae0-79f0d13b5cdd.png)
to read the ticket.

#### Downloaded from
- [ X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by edwinphillips** [comment]
can see the issue in firefox developer edition 55.0b10 but can't see the issue - ie. it appears ok - in chrome 59.0.3071.115
