### ISSUE TITLE
/public/step1 404

### ISSUE THREAD

**Issue by dabaptist24** [ladybirdweb/faveo-helpdesk#50]
Hi,
If I clone the repo and setup apache2 to point to it, the webpage replies: "The requested URL /public/step1 was not found on this server." 

Permissions are 755 for www-data. I tried both your debian 7 vps guide and the simpler Ubuntu guide.

Please halp and update your wiki! 
Thanks

**Comment by bhanu2217** [comment]
Is the mod rewrite Apache module enabled ?
If you are using any other web server need to enable pretty url or search engine friendly url

**Comment by dabaptist24** [comment]
Yes, rewrite is enabled. 

What are all the requirements to run Faveo? (packages, mods, configurations, etc)

**Comment by bhanu2217** [comment]
If the basic requirement to run Laravel are meet Faveo should run.
Here is the list
https://laravel.com/docs/5.2
You can also try Faveo probe https://github.com/ladybirdweb/faveo-probe

**Comment by dabaptist24** [comment]
I meet all the requirements.

![capture](https://cloud.githubusercontent.com/assets/7072122/15054839/6d2e9c1e-12d7-11e6-9b5c-659ae76ba06d.PNG)

**Comment by bhanu2217** [comment]
Only thing is this probe cannot check if mod rewrite module is enabled on your server.

Can you try and install Laravel https://github.com/laravel/laravel on your server and see if it works.

**Comment by dabaptist24** [comment]
While the mod was enabled, the parameters were not specified in the webserver config. Adding:
<Directory /var/www/yoursite/public>
          <IfModule mod_rewrite.c>
          Options -MultiViews
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
         RewriteRule ^ index.php [L]
       </IfModule>
</Directory>

to the conf made everything work. You should specify that the mod needs configured for the host in the webserver conf. Thanks.

**Comment by dabaptist24** [comment]
Also, I got to step 6 of the setup and hit this error:
<img width="907" alt="capture" src="https://cloud.githubusercontent.com/assets/7072122/15078891/76b891d4-1383-11e6-80b1-7d9aeb2de31f.PNG">

**Comment by ajanes3** [comment]
I have run into that 500 error as well at step6. I have not found a fix yet. However, refreshing the page seems to take care of the error.

**Comment by bhanu2217** [comment]
Enable debugging = true on line no 16 here
https://github.com/ladybirdweb/faveo-helpdesk/blob/master/config/app.php

ASP Tag in PHP should be off in PHP.ini

**Comment by bhanu2217** [comment]
Please enable debugging and send us the exact error message that you see.

**Comment by dabaptist24** [comment]
It appears to be a misconfiguration where it is trying to log in as root and not the designated DB user I setup.

PDOException in Connector.php line 47: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

[error.txt](https://github.com/ladybirdweb/faveo-helpdesk/files/255580/error.txt)

**Comment by bhanu2217** [comment]
Is it possible for you to share your server details with us on support@ladybirdweb.com so we can run few more test and see what is the issue.

**Comment by dabaptist24** [comment]
Access? I'd rather not, but I'm willing to test out any advice you have myself.

**Comment by bhanu2217** [comment]
The issue you are having is server dependent, we are not able to replicate in our environment. There was similar issue sometime back, solution is here https://github.com/ladybirdweb/faveo-helpdesk/issues/38 Unless we can replicate the issue and look at it difficult to provide solution

**Comment by dabaptist24** [comment]
Figured it out, it was a permissions issue. Only some of the files were 755 and owned by www-data. How complete and stable would you currently say Faveo is?

**Comment by bhanu2217** [comment]
Faveo is being used by many people in production already. As and when we come across bugs we provide a fix. All the issues you have listed above are server environment related and not really problem with Faveo code. We are maintaining a separate private repository where we record all the issue/bugs and enhancement that we want to add to Faveo. We are right now working on new version of Faveo which will be on Laravel 5.2 and issues that people come across during email integration setting and installation, we will address them in this new version, simplifying and new version will have an auto update module also, that will update the Faveo to latest version with click of button

**Comment by bhanu2217** [comment]
Do use Faveo in production, initially it might take you while to setup special on bare metal server environment and understand how Faveo works, once setup is done, it works flawlessly. As more and more people use Faveo more stable & robust it will get and more features we will add to it, as we will get more feedback from users. Most of the changes we do to Faveo and new features that we add to our roadmap are all based on user feedback and how to improve user experience and simplifying things. Our goal is to be World's favourite open source help desk application.

**Comment by dabaptist24** [comment]
I got it up and running and it is beautiful. Much more advanced and flawless than osTicket.

**Comment by bhanu2217** [comment]
Thank You.
We are already working on next release which we are planning to release next week.
It will have lot more new features, below is what you can look for in the next release

- More advance email panel to support all kind of SMTP, IMAP and POP settings
- Upgrade to Laravel 5.2
- Advance client and agent profile with graphics/charts
- New design charts/graphs on dashboard
- Workflow for auto close ticket
- Auto upgrade module, now Faveo will be able to update easily with click of button from within Faveo whenever new updates are available
- Different block inside Faveo for email display to separate email window from Faveo design
- XSS vulnerability check
- Decoding(HTML Parsing) of all kind of emails, current certain emails decoding is not working very well
- Upgraded email template module, now not only change every email content that goes from Faveo but also the subject. Currently email template module works from file system, it's being changed to work from db now and also option for subject is set
- Breadcrumbs
- Bug fixes in KB
- Bug fixes and enhancement in Rating module
- Bugs fix throughout the project
- Login module, enhanced security to prevent brute force attacks
