### ISSUE TITLE
Security issue for ticket threads (all version)

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#502]
- Faveo Version : All
- PHP version : 7.1
- Database Driver & Version : MySql 
- Server specification : Apache web server on windows 10

#### Description: 
There is a major security flaw in the system which allows anybody to see the conversation threads of any ticket. Which may be a great security disaster and may provide some important information to an unauthorized person.

#### Steps To Reproduce: 
* Create one ticket in the system to get ticket number format or sequence of the system.
* In client panel there is a small form "Have a ticket" which asks for user's email address and ticket number. When user provides these details s/he gets a unique link which allows user to see the complete thread of ticket and status of the ticket without login to system.
* Enter unauthorized person's email address and various ticket numbers in ticket number format. User will get links to check all tickets and can see all tickets conversation without login to the system.

#### Downloaded from
- [ x ] master-branch

- [ x ] development-branch

- [ x ] release-tag

**Comment by mathieu-aubin** [comment]
Adding an epoch timestamp somewhere in there usually takes care of things as far as making a link very very hard to reproduce without knowing it fully

php date getTimestamp could be used, maybe...
