### ISSUE TITLE
faveo-helpdesk vs Faveo Servicedesk Community

### ISSUE THREAD

**Issue by smallfish01** [ladybirdweb/faveo-helpdesk#504]
Hi,
I'd like to know faveo-helpdesk and Faveo Servicedesk Community is the same product? I installed faveo-helpdesk continer and " Faveo Servicedesk Community" as official document, but when I login to the servicedesk community I found it's same.

Is this correct? But I saw servicedesk community has assist management function.

**Comment by nandagopalnandu** [comment]
No. It is different.Service desk has different features like asset management,creating problems etc.. In Faveo help desk we can activate the service desk pluggin to use those features.

**Comment by smallfish01** [comment]
So you means the service desk pluggin is not free?

**Comment by bhanu2217** [comment]
**We have two types of editions**

- Community - Free
- Pro - Paid

Community edition has lesser features compared to paid and comes with support & updates

**Service desk**

- It's just a plugin that runs on top of Faveo Helpdesk
- It ad's the feature of asset management
- Tickets can be linked to assets
- Pro edition of Service Desk comes with reports
