### ISSUE TITLE
ErrorException in Ticket_Thread.php line 136

### ISSUE THREAD

**Issue by vahidrezazadeh** [ladybirdweb/faveo-helpdesk#505]
- Faveo Version : Community 1.9.6
- PHP version : 7
- Database Driver & Version :
- Server specification :

#### Description:
hi , we have error in this page : http://hub.safirsystem.ir/public/thread/5
error body : 
Call to undefined function App\Model\helpdesk\Ticket\imap_mime_header_decode() (View: /home/safirsyst/domains/safirsystem.ir/public_html/hub/resources/views/themes/default1/agent/helpdesk/ticket/timeline.blade.php)

thanks
<img width="1160" alt="screen shot 1396-06-10 at 10 36 05" src="https://user-images.githubusercontent.com/12491459/29957263-cbaed8c4-8f01-11e7-8edb-4d6ac89c801c.png">

**Comment by EriSL** [comment]
This error happens because php-imap is not installed on your server.
