### ISSUE TITLE
Email not being collectted from server - cron error [ErrorException]  Invalid argument supplied for foreach()  

### ISSUE THREAD

**Issue by poncho1234** [ladybirdweb/faveo-helpdesk#509]
- Faveo Version : 1.9.6
- PHP version :5.6.31
- Database Driver & Version :10.0.31-MariaDB-cll-lve
- Server specification : centos7

#### Description:
Hi, problem with email collection from server, when I run http://mysite/readmail it works so email is setup correctly.
I then enabled cron jobs in settings, copied cron job command which was: 
/usr/bin/php-cli -q  /home/mysite/artisan schedule:run

modified for my server to:-
php  /home/mysite/artisan schedule:run

The cron job is sending me the following error:-

[ErrorException]                         
  Invalid argument supplied for foreach()  

What is the problem?

I've also run:-

curl -q https://mysite/readmails 

Which works, but keeps receiving another copy of the same ticket?

Please provide a solution for this problem and let me know if you require further info

#### Steps To Reproduce:
Installed another version at a different URL - same problem

#### Downloaded from
- [x] master-branch

**Comment by cafuller** [comment]
Additional info

I was originally using pop3 & curl -q https://mysite/readmails, but as said above this kept creating multiple tickets from the same email.
I changed to imap & curl -q https://mysite/readmails and this seems to be functioning as expected.
