### ISSUE TITLE
Returning to step3 "Fails! The data in database already exist. Please provide fresh database"

### ISSUE THREAD

**Issue by felipe-balloni** [ladybirdweb/faveo-helpdesk#513]
- Faveo Version : #.#.#
- PHP version : 5.6
- Database Driver & Version : mysql
- Server specification : Unbuntu Server 16.04

#### Description:
After install method Locale Information and press install, its return to step3 with error: "Fails! The data in database already exist. Please provide fresh database

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mathieu-aubin** [comment]
You probably attem'ted to install once with the same database name and it somehow failed, right? if thats the case try changing the db name it should work just fine. 

if not then please provide more infos as this isnt atypical situation
