### ISSUE TITLE
Issue synchronizing incoming mails

### ISSUE THREAD

**Issue by NickNck** [ladybirdweb/faveo-helpdesk#5315]
Hi I am having issues with this helpdesk in receiving incoming mails. My email configurations are correct and the outgoing mail server works well since when i reply submitted tickets the recipient receives them quickly. But receiving emails from the recipient in the helpdesk inbox is an issue since it does not enter the inbox unless i re-register the email in the mail configurations which then synchronizes. It is only then i receive mails from recipients

**Comment by bhanu2217** [comment]
Are you still facing this issue in v2.0.1?
