### ISSUE TITLE
Trying to edit a helptopic missing table error

### ISSUE THREAD

**Issue by mahomedalid** [ladybirdweb/faveo-helpdesk#540]
- Faveo Version : 1.9.7-BETA
- PHP version : 7.0.22
- Database Driver & Version : PDO MySQL
- Server specification : Ubuntu

#### Description:

Trying to edit a helptopic show following:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.custom_forms' doesn't exist (SQL: select * from `custom_forms`)

#### Steps To Reproduce:

Edit any helptopic. Creating manually the tables from a previous faveo install fixed the error.

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [X ] release-tag

**Comment by mverma16** [comment]
V1.9.7-Beta database structure was breaking the functionality of the custom forms, we discarded the changes and used old structure in v1.10 which is soon to be released.

Please note: There will we no support provided for v1.9.7-Beta
