### ISSUE TITLE
We are Unable to create Agent.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/faveo-helpdesk#544]
- Faveo Version : 1.9.7-BETA
- PHP version : 7.0
- Database Driver & Version : MySql 5.7
- Server specification :  Wamp

#### Description:
While selecting **Agent time zone** showing black screen so we can't create Agent. Please check and fix it and let me know. 

#### Downloaded from
- [ ] master-branch

- [- ] development-branch

- [ ] release-tag

**Comment by mahomedalid** [comment]
I've a fix:

resources/views/themes/default1/admin/helpdesk/agent/agents/create.blade.php


```
- {!! Form::select('agent_time_zone', [''=>Lang::get('lang.select_a_time_zone'),Lang::get('lang.time_zones')=>$timezones],null,['class' => 'form-control select']) !!}
+                {!!Form::select('agent_time_zone', [''=>Lang::get('lang.select_a_time_zone'), Lang::get('lang.time_zones')=>$timezones->pluck('name','id')->toArray()],null,['class' => 'form-control select']) !!}

```
