### ISSUE TITLE
Private Articles still visible

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#55]
I created a private article in the knowledge base. I am not entirely clear of what it is supposed to do, but my interpretation is that they are only visible to agents.

Anyone who accesses the knowledge base can still see the private article listed as well as the quick quote from it. If I click it, I get an error message.

Below is an image after I attempted to click the private article.

![privarticle](https://cloud.githubusercontent.com/assets/4474921/15192698/552bda54-1788-11e6-9dfe-f21b39b0b2d5.png)

**Comment by vijaysebastian** [comment]
We will fix this on next release

**Comment by ajanes3** [comment]
I want to make sure I understand the functionality that is supposed to be here. Are private articles only supposed to be visible by staff agents only? Or should they be accessible by logged in, non agent users? Obviously, if you are not logged in, it DEFINITELY shouldn't be there.

**Comment by bhanu2217** [comment]
Ideal working: Private article will be visible only to agents & admins

**Comment by ajanes3** [comment]
I have tested this. It is still broken. The article no longer displays on the main knowledgebase view:

![](https://i.gyazo.com/0894ef2f260e59c6dcd7b5e591423b9d.png)

However, the staff category still shows (I don't know if there is a way to hide that), and the article that is hidden still shows in the list of articles in the category:

![](https://i.gyazo.com/55ba123151fdc022f43615f6daf21dc0.png)

**Comment by sujit223** [comment]
We will make a release by next week. Please check on that update

**Comment by ajanes3** [comment]
Awesome. Thank you!

**Comment by sujit223** [comment]
Anytime

**Comment by vijaysebastian** [comment]
If an article is private, then admin and agent can only view the article. If client or unauthorised user  try to access the view link system return response of 404.
