### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by ki4yvc** [ladybirdweb/faveo-helpdesk#551]
- Faveo Version : 1.9.6
- PHP version : 7.1.11
- Database Driver & Version :
- Server specification : Heroku Deplyment

#### Description:

On step two of the setup procedure, I get `A non well formed numeric value encountered` at `resources/views/themes/default1/installer/helpdesk/view2.blade.php` line 80.

#### Steps To Reproduce:

Run setup, proceed to step 2

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
Yes there is a issue in type casting of variable in step 2 which is being caught in PHP7.1 You can either try to downgrade your PHP version to 7.0 or edit the code in `InstallerController.php` to cast string to numeric.

**Comment by pleekit** [comment]
Was also experiencing similar issue, modified view2.blade.php function php_config_value_to_bytes

function php_config_value_to_bytes($val) {
    $val = trim($val);
    if ($val <> "-1") {
       $last = strtolower(substr($val, -1));
       $val = (integer) substr($val,0,strlen($val)-1); // converted $val to integer
       switch ($last) {
           // The 'G' modifier is available since PHP 5.1.0
          case 'g':
              $val *= 1024;
          case 'm':
              $val *= 1024;
          case 'k':
              $val *= 1024;
       } // switch
    } // if
    return (integer) $val;
} // php_config_value_to_bytes
