### ISSUE TITLE
Uncaught Error: Class 'Config' on install

### ISSUE THREAD

**Issue by DanBennettUK** [ladybirdweb/faveo-helpdesk#552]
- Faveo Version : 1.9.6 (and latest BETA)
- PHP version : 7.0.25
- Database Driver & Version : MariaDB 5.5.56
- Server specification : CentOS 7, Apache

#### Description:
Cannot install Faveo - page appears blank, trying CLI install also fails.

Error in log;

`PHP Fatal error:  Uncaught Error: Class 'Config' not found in /var/www/temp.url/faveo/app/Exceptions/Handler.php:46\nStack trace:\n#0 /var/www/temp.url/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/temp.url/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/temp.url/faveo/app/Exceptions/Handler.php on line 46
`

#### Steps To Reproduce:

Attempt to install

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [x] release-tag

**Comment by chadsterBAM** [comment]
Damn, thought I WAS ALONE.
[Tue Jan 16 12:37:25.521191 2018] [php7:error] [pid 12069] [client 128.100.184.196:58816] PHP Fatal error:  Uncaught Error: Class 'Config' not found in /var/www/html/faveo-helpdesk-1.9.7-BETA/app/Exceptions/Handler.php:46\nStack trace:\n#0 /var/www/html/faveo-helpdesk-1.9.7-BETA/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/faveo-helpdesk-1.9.7-BETA/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/faveo-helpdesk-1.9.7-BETA/app/Exceptions/Handler.php on line 46
