### ISSUE TITLE
Required custom form fields not being validated

### ISSUE THREAD

**Issue by gurubydesign** [ladybirdweb/faveo-helpdesk#553]
- Faveo Version : **1.9.6**
- PHP version : 7.0
- Database Driver & Version :  MySQL 5.7
- Server specification :  Ubuntu Server 16.04 LTS

#### Description:
Custom form fields related to help topics are not validated when the ticket is submitted, despite being configured as required. I've checked the **custom_form_fields** table and the required tags are set to 1 on the fields I expect to be validated. There seems to be code supporting the validation on the **Fields** model, but they don't seem to work. Only the generic _Subject_ and _Message_ fields are being validated as required...the rest of the custom fields could be left blank.

#### Steps To Reproduce:

1. Create a custom form.
2. Set a field or two as **Required** and save the form.
3. Configure a help topic to use the custom form you created.
4. Log in as a user.
5. Create a new ticket and choose the help topic with the custom form.
6. Try submitting the ticket without filling-up anything.
      _Notice that an alert would appear, but only to tell you that the Subject and Message fields are 
      required. Any other required fields on the custom form that appears are not validated._
7. Now try indicating a Subject and some Message, then submit the form.
     _The ticket will continue just fine and will be submitted even with unfilled, required custom fields. In 
       effect, the **ticket_form_data** table will be saving a record for the custom field/s but the _content_ 
       column of the concerned custom field record will be **blank**._

#### Downloaded from 
- [x] master-branch
- [ ] development-branch
- [ ] release-tag

#### P.S.
Help anyone?

**Comment by gurubydesign** [comment]
*bump*

**Comment by gurubydesign** [comment]
For those who may need the help I never got, I managed to have my app validate the custom form fields by commenting out Line 34 of **app/Http/Requests/helpdesk/ClientRequest.php**:
`public function rules()
    {
        $check = $this->check(new CommonSettings());
        if ($check != 0) {
            //  return $check;   _<-- this line breaks the validation_
            $custom_rule = $this->getCustomRule();
            $rules = array_merge($check, $custom_rule);
            return $rules;
        }`

The remaining challenges now are:

1. Fixing the redirect on ticket submit since for some freaking reason it's resetting the entire client ticket form on submit instead of keep all the filled-out fields in tact, and
2. Highlighting the form-groups encapsulating the custom fields in red like the normal required fields.

Any help this time?

**Comment by mverma16** [comment]
Thanks @gurubydesign for the quick fix, we will fix the remaining challenges in upcoming updates.
