### ISSUE TITLE
URL https wont save

### ISSUE THREAD

**Issue by bafplus** [ladybirdweb/faveo-helpdesk#555]
- Faveo Version : Community 1.9.6
- PHP version : 5.3
- Database Driver & Version : Mysql 10.1.29
- Server specification : Ubuntu 16.10

#### Description:
http/https selection wont safe in settings. Reverts back to http after save.
Any workaround or manual setting in database?

#### Steps To Reproduce:
Install using the bash autoinstaller

#### Downloaded from
- [ x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by dav12evg** [comment]
Hi bafplus!
By using an FTP client or any other method, go to **[INSTALLATION DIR]/public/** find and edit the **.htaccess** file. Open it with a text editor, go to the last part of the file and delete the following entry:
**#custom
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]**
