### ISSUE TITLE
Tickets not showing in Dashboard

### ISSUE THREAD

**Issue by GH0STL1N3R** [ladybirdweb/faveo-helpdesk#556]
- Faveo Version : 1.9.6
- PHP version :5.6
- Database Driver & Version : mysql 5.6
- Server specification : Shared host

#### Downloaded from
- [*] master-branch

- [ ] development-branch

- [ ] release-tag

![tickets](https://user-images.githubusercontent.com/26091736/33323100-11231716-d454-11e7-9604-19d2ca581837.JPG)

**Comment by gurubydesign** [comment]
Just fishing here...did you try deleting tickets from the database manually? I went through this exactly similar case you have and I realized that I messed up the data (on tables that are tied up with keys and constraints) by deleting the tickets manually in mysql...my bad. 

If you didn't make the same mistake, then I wish you luck figuring this one out. But if you did, you'd have to check all tables related to the ticket table and delete the marooned rows. Perhaps resetting the auto_increment of each one would also help. Then the next time you'd need to delete tickets, it's safer to do it in the admin part of the application.

But as I said, you may not have had the same mistake I had, so wouldn't know if this would help. 
Cheers!

**Comment by GH0STL1N3R** [comment]
No, I didn't try to do it manually. 

I just installed the script and entered the admin. All required modules are enabled with the proper permissions. I am going to try it anyway with checking the tables and the auto_increment.

Thanks for your reply!

**Comment by mverma16** [comment]
@GH0STL1N3R you can get more details about the error by checking ajax response and browser console for JavaScript errors.
Presk `ctrl`+`shift`+`i` in chrome browser and check console and network tabs for the errors. Share the screen shots of the errors so we can troubleshoot further.
