### ISSUE TITLE
Missing attachments + attachment ownership as root

### ISSUE THREAD

**Issue by khuzaini** [ladybirdweb/faveo-helpdesk#557]
- Faveo Version : 1.9.6
- PHP version : 5.6.32
- Database Driver & Version : MySQL 5.6.38
- Server specification : VPS (Centos 7.x with cpanel v68.x)

#### Description:
Users send in a ticket to faveo system with attachment. But attachment is missing when view from the system. 

#### Steps To Reproduce:
Users send in a ticket to faveo system with attachment. But attachment is missing when view from the system. 

When I look into the local folders, the attachment ownership is set as root instead of the cpanel username. 

[provisionmsc@vps attachments]$ ls -al
-rw-r--r-- 1 root         root          70810 Dec  8 17:14 2317_equipment_check_in_or_removal.jpg
-rw-r--r-- 1 root         root          70810 Dec  8 16:51 6845_equipment_check_in_or_removal.jpg

#### Downloaded from
- [ X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@khuzaini have you found the fix for this issue?
