### ISSUE TITLE
Change Role Agents from role agent to admin from .php

### ISSUE THREAD

**Issue by syaifulrangga** [ladybirdweb/faveo-helpdesk#559]
- Faveo Version : 1.9.6
- PHP version : 5.5
- Database Driver & Version : MariaDB
- Server specification : Ubuntu 16.04 LTS

![role agents](https://user-images.githubusercontent.com/19748489/34592135-942f1002-f1f4-11e7-9d35-64c89167b0e9.PNG)
###Description:
I want to ask, how to change the role agents to admin? but from. php/mysql, because yesterday I accidentally changed the role all agents to agents of all, there is nothing to be admin

Steps To Reproduce:

###Downloaded from
- [Yes ] master-branch

- [ No] development-branch

- [ No] release-tag

**Comment by mverma16** [comment]
Hi @syaifulrangga, sorry for the delayed response. If you are able to access database then you can simply change the role of desired agents to admin. Please check the table called <b>users</b> in database and change the value of <b>role</b>column  to `admin`.
It can be easily done if you can access database using `phpmyadmin`.
Please revert if you need help with database query to execute.
