### ISSUE TITLE
Error on Create Email page

### ISSUE THREAD

**Issue by jjplaying** [ladybirdweb/faveo-helpdesk#56]
Hi,

There's an error on the Create Email page in the admin panel (Admin -> Emails -> Create Email).

```
[Fri May 13 15:31:29.333650 2016] [proxy_fcgi:error] [pid 27807] [client ***:65482] AH01071: Got error 'PHP message: PHP Fatal error:  Call to a member function toArray() on array in /var/www/vhosts/river.ml/devriver.ml/sp/storage/framework/views/3656c801f8bbce8bc4e269de10017128 on line 84\n', referer: http://devriver.ml/sp/public/emails
```

![bildschirmfoto 2016-05-13 um 15 35 11](https://cloud.githubusercontent.com/assets/15860314/15249537/54254c00-1920-11e6-84d6-a3044877a3c6.png)

**Comment by bhanu2217** [comment]
Hi,

Can you email us on support@ladybirdweb.com
And provide us following access so we can look into it

- Domain and user id & password to login to Faveo installation
- Dummy/test email account and setting details that you want to configure with Faveo
- FTP details of the test server where you can trying to install the app

Thank You.

**Comment by jjplaying** [comment]
Sorry, my fault.
While setting up a test environment for you, I've noticed that I've used an old PHP version.
You can close this issue.

**Comment by sujit223** [comment]
Can you tell us what version of PHP you were using and how the issue occured. Just for information.

**Comment by ned-ster** [comment]
Having the same issue. 
- php5-fpm 5.6.20
- nginx version: nginx/1.9.10
- Faveo Version Community 1.0.7.4


2016/06/09 20:40:48 [error] 726#726: *4631 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function toArray() on array in /var/www/domain.com/web/storage/framework/views/037e5d28c0ac53914c3e7ca57c57d42d on line 84" while reading response header from upstream, client: 77.238.xx.xx, server: domain.domain.com, request: "GET /public/emails/create HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php/web2.sock:", host: "domain.domain.com", referrer: "http://domain.comain.com/public/emails"

**Comment by mathieu-aubin** [comment]
hi ned.
can you show me surrounding lines of 84 in
/var/www/domain.com/web/storage/framework/views/037e5d28c0ac53914c3e7ca57c57d42d

**Comment by ned-ster** [comment]
from line 80 to line 88

                
                <div class="col-xs-4 form-group <?php echo $errors->has('department') ? 'has-error' : ''; ?>" id="department_error">
                    <?php echo Form::label('department',Lang::get('lang.department')); ?>

                    <?php echo $errors->first('department', '<spam class="help-block">:message</spam>'); ?>

                    <?php echo Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')->toArray()],null,['class' => 'form-control select', 'id' => 'department' ]); ?>

                </div>

**Comment by mathieu-aubin** [comment]
If you are under linux please post the output of:
```bash
grep -r "\$departments->lists" /var/www/domain.com/web/ | sed 's/\:/\n/'
```
The output should be similar to this:
```bash
mathieu@qwerty /storage2/development/github/faveo-helpdesk $ grep -r "\$departments->lists" /storage2/development/github/faveo-helpdesk/ | sed 's/\:/\n/' | sed 's/\s\s*/ /g'
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/agent/agents/create.blade.php
 {!! Form::select('primary_dpt', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],null,['class' => 'form-control select']) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/agent/agents/edit.blade.php
 {!!Form::select('primary_dpt', $departments->lists('name','id'),null,['class' => 'form-control select']) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/settings/system.blade.php
 {!!Form::select('department', [''=>'Select a Department','Department'=>$departments->lists('name','id')],null,['class'=>'form-control']) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/emails/emails/create.blade.php
 {!!Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')],null,['class' => 'form-control select', 'id' => 'department' ]) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/emails/emails/edit.blade.php
 {!!Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')],null,['class' => 'form-control select']) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/manage/helptopic/create.blade.php
 {!!Form::select('department', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],1,['class' => 'form-control']) !!}
/storage2/development/github/faveo-helpdesk/resources/views/themes/default1/admin/helpdesk/manage/helptopic/edit.blade.php
 {!!Form::select('department', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],null,['class' => 'form-control']) !!}
```

**Comment by ned-ster** [comment]
Here you go.


`/web# grep -r "\$departments->lists" . | sed 's/\:/\n/' | sed 's/\s\s*/ /g'



./storage/framework/views/5aa597e2ca5f5a7494b7efa219167790
 <?php echo Form::select('primary_dpt', $departments->lists('name','id'),null,['class' => 'form-control select']); ?>
./storage/framework/views/037e5d28c0ac53914c3e7ca57c57d42d
 <?php echo Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')->toArray()],null,['class' => 'form-control select', 'id' => 'department' ]); ?>
./storage/framework/views/dbf350a2c1b7f4da24fbe5aec5097d1a
 <?php echo Form::select('primary_dpt', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],null,['class' => 'form-control select']); ?>
./resources/views/themes/default1/admin/helpdesk/settings/system.blade.php
 {!!Form::select('department', [''=>'Select a Department','Department'=>$departments->lists('name','id')],null,['class'=>'form-control']) !!}
./resources/views/themes/default1/admin/helpdesk/manage/helptopic/create.blade.php
 {!!Form::select('department', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],1,['class' => 'form-control']) !!}
./resources/views/themes/default1/admin/helpdesk/manage/helptopic/edit.blade.php
 {!!Form::select('department', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],null,['class' => 'form-control']) !!}
./resources/views/themes/default1/admin/helpdesk/agent/agents/create.blade.php
 {!! Form::select('primary_dpt', [''=>'Select a Department','Departments'=>$departments->lists('name','id')],null,['class' => 'form-control select']) !!}
./resources/views/themes/default1/admin/helpdesk/agent/agents/edit.blade.php
 {!!Form::select('primary_dpt', $departments->lists('name','id'),null,['class' => 'form-control select']) !!}
./resources/views/themes/default1/admin/helpdesk/emails/emails/create.blade.php
 {!!Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')->toArray()],null,['class' => 'form-control select', 'id' => 'department' ]) !!}
./resources/views/themes/default1/admin/helpdesk/emails/emails/edit.blade.php
 {!!Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')->toArray()],null,['class' => 'form-control select']) !!}`

**Comment by mathieu-aubin** [comment]
hey, just a trick, for clarity...
when you post code and you know the source type is obvious, to this:
![screenshot_2016-06-09_15-37-31](https://cloud.githubusercontent.com/assets/15820228/15943693/3c9be84e-2e58-11e6-8aa9-4b6fc5ef661b.png)

**Comment by mathieu-aubin** [comment]
try this
```bash
mv ./resources/views/themes/default1/admin/helpdesk/emails/emails/create.blade.php .
mv ./resources/views/themes/default1/admin/helpdesk/emails/emails/edit.blade.php .
wget -O ./resources/views/themes/default1/admin/helpdesk/emails/emails/create.blade.php \
https://raw.githubusercontent.com/ladybirdweb/faveo-helpdesk/master/resources/views/themes/default1/admin/helpdesk/emails/emails/create.blade.php
wget -O ./resources/views/themes/default1/admin/helpdesk/emails/emails/edit.blade.php \
https://raw.githubusercontent.com/ladybirdweb/faveo-helpdesk/master/resources/views/themes/default1/admin/helpdesk/emails/emails/edit.blade.php
```

**Comment by ned-ster** [comment]
Thanks for the tip. I edited my previous post. Will try your patch in a minute.

**Comment by mathieu-aubin** [comment]
What version do you have installed? becuause your files don't have the same code as the one on the git -- that's why i'm asking you to wget the files from here.

**Comment by ned-ster** [comment]
Version Community 1.0.7.4 That is what I have in the footer.

Wgeting create.blade.php and edit.blade.php solved my issue. Will add an email address and test.

**Comment by ned-ster** [comment]
Thanks, it works now.

**Comment by mathieu-aubin** [comment]
No problems.

**Comment by mathieu-aubin** [comment]
@ned-ster 
Essentially, you should pull to get the new updates on the files.

**Comment by supportreq** [comment]
@mathieu-aubin this doesnt seem to work for my installation.. downloaded the two files and replaced it.. though gives 500 error.. please advice..

**Comment by bhanu2217** [comment]
Can you enable debugging and send us the exact error message

**Comment by supportreq** [comment]
@mathieu-aubin 
`
FatalErrorException in 4b4a70edc6f4e80b1a00709805e21c15 line 81: Call to a member function toArray() on a non-object
`
```php

                    <?php echo $errors->first('department', '<spam class="help-block">:message</spam>'); ?>

                    <?php echo Form::select('department', [''=>'--System Default--','departments'=>$departments->lists('name','id')->toArray()],null,['class' => 'form-control select', 'id' => 'department' ]); ?>

                </div>
              
```php

please advice

**Comment by bhanu2217** [comment]
What is the version of Faveo you are using?

**Comment by sujit223** [comment]
Can you download the latest version and try to do the same. Or you can give us your FTP details and we will try to fix the issue of your current version here at support@ladybirdweb.com

**Comment by supportreq** [comment]
@bhanu2217 i m using 1.0.7.4.. how do i download 1.0.7.5? the master branch is the release?

**Comment by sujit223** [comment]
you can try this [Link](https://github.com/ladybirdweb/faveo-helpdesk/wiki/Faveo-Release-notes-&-upgrade-guide-for-V1.0.7.5)

**Comment by supportreq** [comment]
@sujit223 where do i download the 1.0.7.5 release from?

**Comment by bhanu2217** [comment]
You can download the master branch, that the latest code for 1.0.7.5. Release is not yet done as we are still testing the project in detail and release will be done probably by today evening or tomorrow after testing and bug fixing.

**Comment by supportreq** [comment]
@bhanu2217 works with the master branch..
