### ISSUE TITLE
Problem with Greek characters in Subject

### ISSUE THREAD

**Issue by precached** [ladybirdweb/faveo-helpdesk#560]
- Faveo Version : 1.9.6
- PHP version : 7
- Database Driver & Version : Mysql
- Server specification : Ubuntu

#### Description:
Hi 

I have problem with the Greek characters in subject (Agent->Tickets).

The tickets are created via imap fetching. 

#### Steps To Reproduce:
Check the attached image.
![image](https://user-images.githubusercontent.com/35277385/34746709-b8cf6df6-f59d-11e7-9a54-a72fc3cf5744.png)

#### Downloaded from
- [x] master-branch

**Comment by mverma16** [comment]
It's the issue with UTF-encoding. We'll check and update you soon.
