### ISSUE TITLE
Your application has been blocked due to too many failed attempts

### ISSUE THREAD

**Issue by ssancheza227** [ladybirdweb/faveo-helpdesk#561]
- Faveo Version : 1.9.6
- PHP version : 5.6
- Database Driver & Version : MYSQL
- Server specification : Hosting with CPanel

#### Description:
Hi! friends,
I installed Faveo Helpdesk in my hosting  with softwaculous, all working very fine, and then i started created users for testing of tickets and login with these users and passwords but i recived a message "Your application has been blocked due to too many failed attempts faveo". I testing after of 30 minutes but not working, what should i do?. 

#### Downloaded from
- [x] softaculous

- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@ssancheza227 Hi it could be because of security settings of the system. Clearing files in below mentioned locations will solve the issue
* root/storage/framework/sessions
* storage/framework/cache

Please try and revert

**Comment by ssancheza227** [comment]
Thank u for response, i wait 1 day for this deactivate, now work perfect :)
