### ISSUE TITLE
{!!$system_link!!} not using full URL

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#566]
- Faveo Version : 1.9.6
- PHP version : 5.6
- Database Driver & Version : MySQL
- Server specification : Linux Apache server 

#### Description:
The system link tag is giving the wrong URL for checking ticket status.

Here is the link sent:

http://positill.ie/check_ticket/eyJpdiI6IlhvWlwvaHR4a0lEdm1MN25TUHRtYVJ3PT0iLCJ2YWx1ZSI6IkxNS0JQb01UU1JialVyUnd4SUJKemc9PSIsIm1hYyI6IjhmMDc2YjVhYmNmYzcwYzRlM2UyNDM2MzQ2MjdmYjk2ZTU0NDhmNTZiYmQ0ZDUyMzZkZGNjZmRiMGViOGFhOTYifQ==

It should be: the link is missing the httpS and the /tickets/public/

https://positill.ie/tickets/public/check_ticket/eyJpdiI6IlhvWlwvaHR4a0lEdm1MN25TUHRtYVJ3PT0iLCJ2YWx1ZSI6IkxNS0JQb01UU1JialVyUnd4SUJKemc9PSIsIm1hYyI6IjhmMDc2YjVhYmNmYzcwYzRlM2UyNDM2MzQ2MjdmYjk2ZTU0NDhmNTZiYmQ0ZDUyMzZkZGNjZmRiMGViOGFhOTYifQ==

#### Steps To Reproduce:
Mostly happening in acknowledgement mails which are sent out on ticket fetching via cron command.

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [X] release-tag

**Comment by michaelsage** [comment]
Hi 
We are having the same issue for us its dropping the https:// and the /public

This is the link sent: http://support.pdcgroup.net/check_ticket/eyJpdiI6Ik9oWE1mYVM1MVRjRXFSUkE0M0JFUEE9PSIsInZhbHVlIjoieUV1UThhUkUyNzVXdU5xOTNQNFR5dz09IiwibWFjIjoiYTJjYzU2NTc1MzIyNmNhNjYzN2VjMzY5YTI5ZjUxMTNhNGZlNmNlNjllNzlmNzhiNTYwOWFjNDlmYmU2ZDk2MiJ9

Which should be

https://support.pdcgroup.net/public/check_ticket/eyJpdiI6Ik9oWE1mYVM1MVRjRXFSUkE0M0JFUEE9PSIsInZhbHVlIjoieUV1UThhUkUyNzVXdU5xOTNQNFR5dz09IiwibWFjIjoiYTJjYzU2NTc1MzIyNmNhNjYzN2VjMzY5YTI5ZjUxMTNhNGZlNmNlNjllNzlmNzhiNTYwOWFjNDlmYmU2ZDk2MiJ9

For your information I have a work around.

I have setup an apache2 site which does a redirect on the http to https and set the document root of that site to /var/www/html/public

Hope this helps
