### ISSUE TITLE
Mail settings: Email address used always as username

### ISSUE THREAD

**Issue by javijavo** [ladybirdweb/faveo-helpdesk#567]
- Faveo Version : 1.9.6
- PHP version : 5.6.33
- Database Driver & Version : N/A
- Server specification : N/A

#### Description:

The emails settings for IMAP and SMTP at least, assume the username will always be the email address. 
But this is not strictly true and there are some mail server where the username to login is not exactly the email address. For example sometimes the mail address is _`user.name@server.com`_ and the username is just _`user.name`_.
It would be nice to have different fields in the email settings one for the username to login to the server and other with the actual email address.

Many thanks

**Comment by ponchofiesta** [comment]
I created a patch which adds the username field in Faveo 1.9.6

You could pull it into your local git repo.

https://github.com/ladybirdweb/faveo-helpdesk/pull/587
