### ISSUE TITLE
Assign default SLA to customer / organization [Feature]

### ISSUE THREAD

**Issue by AlexDubstone** [ladybirdweb/faveo-helpdesk#57]
I think it would be handy if we had an option to assign a default SLA for each organization. Furthermore it should be possible to assign multiple email addresses to an organization so as soon as a ticket from that email address is submitted the system automatically knows until when it has to be answered.

Best regards and thanks for all the work so far!
Alex

**Comment by bhanu2217** [comment]
- Currently multiple users/email can be added to organisation.
- We will add SLA to organisation via workflow in future releases, not the coming release but after this one
- We are also working on new SLA right now where in it will account your organisation holiday calendar and work timing, This will be part of not this upcoming release but next after this one

**Comment by AlexDubstone** [comment]
That sounds great. Thank you for the fast response!
