### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [ladybirdweb/faveo-helpdesk#5776]
Hey there!

I belong to an open source security research community, and a member (@lfama) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by bindu95** [comment]
Hello @JamieSlome, Please share the details by sending an email to support@faveohelpdesk.com.

**Comment by JamieSlome** [comment]
@bindu95 - it looks like our system sent you to the organization e-mail. Sorry for that!

You can view the report directly here:

https://huntr.dev/bounties/68fd24d3-1f4f-4ed8-bac8-3562b0d1471a/

It is private and is only visible to maintainers with repository write permission.

**Comment by lfama** [comment]
Hi @bindu95 ,

were you (or someone from the team) able to take a look at the [report](https://huntr.dev/bounties/68fd24d3-1f4f-4ed8-bac8-3562b0d1471a/) ?

Thanks!

**Comment by Noor-mommadhi** [comment]
This issue is now resolved

**Comment by lfama** [comment]
@Noor-mommadhi @bhanu2217 Glad that the issue has been resolved! 
Could you please validate the report at [https://huntr.dev/bounties/68fd24d3-1f4f-4ed8-bac8-3562b0d1471a/](https://huntr.dev/bounties/68fd24d3-1f4f-4ed8-bac8-3562b0d1471a/) ?
Thanks!
