### ISSUE TITLE
Cannot get Faveo Installed. Documentation is in disarray.

### ISSUE THREAD

**Issue by Impyus** [ladybirdweb/faveo-helpdesk#582]
- Faveo Version : 1.9.6
- PHP version : 7.1.14
- Database Driver & Version : MariaDB 5.5.56 - mysqli
- Server specification : CentOS Linux 7.4.1708

#### Description:

I have tried to install Faveo now several times to review as my organisation is looking to evaluate the system as a replacement for our current helpdesk. I have had this installed a few versions ago using the autoinstaller script although that no longer works. It would appear that all the links in the autoinstall script are broken. Several links on your website are also broken. The documentation on both the Github wiki and the website is contradictory and incomplete. The ladybird website has a different CentOS 7 install guide (that seems to think its in CentOS 6?) to what is on the Github wiki. The PHP versions are different. The composer steps are incomplete. The site never loads to the initial installation. I've tried, and failed, to fix your autoinstall script (when I found it) and run it locally but that doesn't work. I cannot get it installed under any circumstances on CentOS as it doesn't seem to be supported despite all the documentation to the contrary. I have posted this issue after my 10th clean server build and subsequent failure as I am getting nowhere.

Unfortunately CentOS is my only option as we are a RHEL shop and eventually this would be built on a production RHEL server.

Am I to presume that the project is no longer live or that CentOS is no longer supported? 

Some clarification would he helpful thanks.

#### Steps To Reproduce:

Just follow any of your install guides as is and it will fail to work.

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by pleekit** [comment]
Have you tried using the Wiki pages ?
I had problems as well installing Faveo using php 7.1.14 try using a lower version of php 5.6.33 and see if that helps.

**Comment by Impyus** [comment]
Yeah used both versions on clean installs. No joy.

**Comment by pleekit** [comment]
My installation was on Ubuntu 16.04.3 LTS 32-bit system 
So it may be a bit different than the Centos 7 install.

Take a look at this site as the Wiki pages have links to ladybird that does not work when trying to copy the nginx config and php-fpm files.

https://github.com/ladybirdweb/faveo-server-images/tree/master/centos7

This helped me though the process.

**Comment by ponchofiesta** [comment]
I was in that situation too. But I'm using Ubuntu. Actually I got it working using the way used for there [Docker image](https://github.com/ladybirdweb/faveo-docker). I got Faveo 1.9.6 working using the steps from their Dockerfile. To get Faveo 1.10.0-BETA working you need to change the PHP version to 7.0.

I was not able to get this working using PHP FPM from the official PHP Docker image. And I had to do `chown -R www-data:www-data faveo-helpdesk`. 

It was a long way. And yes, the documentation and the error handling of Faveo is awful. But the System is a good candidate for our evaluation.

**Comment by Impyus** [comment]
Went with Zammad Helpdesk as just couldn't get this working. I would have been happy to help update the community documentation for CentOS myself except it was impossible to install in the end. Gave up.
