### ISSUE TITLE
Attachment not showing in the "Creation Ticket" form after the upload

### ISSUE THREAD

**Issue by Tifeo** [ladybirdweb/faveo-helpdesk#592]
- Faveo Version : 1.9.6
- PHP version : 5.6.34
- Database Driver & Version : Ver 15.1 Distrib 10.2.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Server specification : ubuntu16.04.1+deb.sury.org+1

#### Description:

When i create a new ticket and add an attachment, this one is not correctly viewed as I've not attached anything. But after I send the ticket, the attachment is correcty viewed in the agent panel.
I've also tried to switch the storage from local to database without any results.
Thanks for the support

#### Steps To Reproduce:

- Connect to Faveo Help Desk
- Open a ticket
- Add an attachment using the button
- After the end of the upload, there is no sign of the attachment uploaded
- When I connect to the system for pick up the ticket, the attachment is correctly showed

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by a-patel** [comment]
I am getting the same issue.
@bhanu2217
