### ISSUE TITLE
 Who has a Chinese language pack, can you share it? Thank you

### ISSUE THREAD

**Issue by L-Y** [ladybirdweb/faveo-helpdesk#597]
- Faveo Version : #.#.#
- PHP version :
- Database Driver & Version :
- Server specification :

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@L-Y we have not received the translation package for Chinese language yet but Chinese translation for Faveo is available for Pro edition for both simple and traditional. Which we got translated by some translation service providers. If you want you can checkout [demo of Faveo Pro](http://stablehelpdesk.faveodemo.com)  and see it working.

You can also follow [this article](https://www.support.ladybirdweb.com/show/how-to-translate-faveo-into-multiple-languages) which shows how to translate and create a language package for Faveo. Don't forget to send a PR with the translation files so we can make it available for other community users.

**Comment by L-Y** [comment]
@mverma16 How do I checkout it? There seems to be no Chinese package in the source code.
But there is a Chinese package in the demo website. Can I download it?

**Comment by bhanu2217** [comment]
Demo website is pro version.
We can send you language file of the community edition. You can translate and send it back to us and we can make a release with this new language.

**Comment by L-Y** [comment]
@bhanu2217  
I am translating now

**Comment by bhanu2217** [comment]
Thank You. Please share with us once done.

**Comment by L-Y** [comment]
That's of course. It's my pleasure
