### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by fajarwahyu99** [ladybirdweb/faveo-helpdesk#598]
- Faveo Version : #.#.#
- PHP version : 5.6
- Database Driver & Version : mysql
- Server specification : localhost

#### Steps To Reproduce:
composer install
php artisan key:generate
php artisan migrate
php artisan serve

Why is this?
![image](https://user-images.githubusercontent.com/11350854/38474339-e22c70d4-3bc7-11e8-8d09-1ea736e5c3a4.png)

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@fajarwahyu99 We'll check and resolve the issue ASAP. Meanwhile you can follow our [wiki articles](https://github.com/ladybirdweb/faveo-helpdesk/wiki) and install Faveo.

**Comment by fajarwahyu99** [comment]
yes i have read wiki.  and i get this problem

**Comment by fajarwahyu99** [comment]
yes . it must run virtualhost?

**Comment by m2ura** [comment]
Same issue/problem to me too


![](https://user-images.githubusercontent.com/11350854/38474339-e22c70d4-3bc7-11e8-8d09-1ea736e5c3a4.png)

**Comment by m2ura** [comment]
Same issue/problem to me too

![screenshot from 2018-04-17 20-19-36](https://user-images.githubusercontent.com/13012135/38891085-90479c2c-4283-11e8-80e4-431e2f993e51.png)

**Comment by m2ura** [comment]
Fixed it, followed all the installation steps.
