### ISSUE TITLE
Email Encription fall back to status "None"

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk#61]
I was trying to edit one of my E-mail account and I couldn't save the change.
Then I realized that the Encryption which I set to be SSL was fall back to None. 
I was able to save the change putting back the encryption to SSL but if I want to edit the E-mail again is still with Encryption None.

**Comment by sujit223** [comment]
This is a issue related to the html part of the code but not the actual settings. Your settings actually got save and working. We have fixed this issue in our development and you will get the update by the next release.

**Comment by csaeum** [comment]
I can confirm
But was already confirmed that it will be fixed

**Comment by bhanu2217** [comment]
@SarfrazS Can you please confirm if this issue has been fixed and in which version

**Comment by SarfrazS** [comment]
I have tested in version 1.0.7.9.1 it's working fine.
