### ISSUE TITLE
.env acces

### ISSUE THREAD

**Issue by cocos4n** [ladybirdweb/faveo-helpdesk#625]
i can acces config laravel .env 

1. https://www.faveohelpdesk.com/billing/.env
2. https://www.faveohelpdesk.com/.env

thanks for attention.. 
bug bounty?
cocos4njav@gmail.com | http://www.indonesiancode.party/

**Comment by bhanu2217** [comment]
We are doing bulk close for all old issues. If the issue still exists in v1.10 or later. Please reopen
