### ISSUE TITLE
IMAP not working after installation

### ISSUE THREAD

**Issue by Johnleads444** [ladybirdweb/faveo-helpdesk#627]
- Faveo Version : #.#.# Version Community 1.9.6
- PHP version : 7.0
- Database Driver & Version : Mysql 5.6 
- Server specification : Linux 4 Core 4 GB RAM

#### Description:
when I save the imap settings it gives me success message. But after that when email on the email address that we configured we still cannot get new tickets. when i resave the settings again only that time emails are being import.

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
Faveo requires a trigger to check mail server to fetch emails from mail server so they can reflect as tickets in the system. You can set cron job on server to fetch mails from your system configured mail. Please follow the article for more details. 

https://github.com/ladybirdweb/faveo-helpdesk/wiki/Cron-Job-or-any-Job-scheduler

> NOTE: PHP path may vary in your server so please correct php path while setting up cron command

**Comment by Johnleads444** [comment]
I have check that manually but that url giving me error like 404 not found

root@Webserver:~# curl -q http://192.168.10.96/ipssupport/reademails
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /index.php was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at 192.168.10.96 Port 80</address>
