### ISSUE TITLE
URL of the Status in email confirmation not correct

### ISSUE THREAD

**Issue by ikrudolf** [ladybirdweb/faveo-helpdesk#631]
•Faveo Version : Community 1.9.6
•PHP version : 5.6
•Database Driver & Version : MariaDB 10.1.24-MariaDB
•Server specification : unknown

Description: In the confirmation email sent to the user, the link in the bottem of the email to check the status is not correct?

It sais: You can check the status of or update this ticket online at: http://localhost/check_ticket/longnummersandletters

But it should be: 
https://blahblahblah.hostinghobby.com/public/check_ticket/longnummersandletters
(When manual changing this link and visting the link it gives: Sorry, something went wrong We're working on it and we'll get it fixed as soon as we can Go back)

Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment]
We are doing bulk close for all old issues. If the issue still exists in v1.10 or later. Please reopen

**Comment by hakanyanaz** [comment]
I have version this issue on v1.10.2

**Comment by ikyamoet** [comment]
I have the same issue on v1.10.6 
😨

**Comment by hossnys** [comment]
why there is no fix for this issue till now , as it make the user blind about his ticket status and can't reach it.

**Comment by rNianios** [comment]
Hi it seems that if you install it through Softaculous it doesn't populate all the .env entries correctly.

Workaround:

1. Locate .env file, it should be at the root of the domain / subdomain where you've installed Faveo
2. Edit
3. Change APP_URL= localhost to APP_URL=https://support.xxxxx.yyy/public

and test it again.
