### ISSUE TITLE
Weird Constant Error

### ISSUE THREAD

**Issue by c0fe** [ladybirdweb/faveo-helpdesk#64]
I keep getting this error whenever I navigate to a freshly uploaded N1, I have tried various FTP clients and use ASCII mode to transfer but it still crops up. Any ideas on how to resolve this?

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /home1/polar/public_html/support/app/Http/Kernel.php on line 40

**Comment by sujit223** [comment]
This error represents that your php version is not as per Faveo. To run Faveo please check this link for system requirements http://ladybirdweb.com/support/show/server-requirements
