### ISSUE TITLE
Outbound Mail wrong "From"

### ISSUE THREAD

**Issue by cstrock** [ladybirdweb/faveo-helpdesk#640]
- Faveo Version : Community 1.9.3
- Server specification : Docker image

#### Description:
If there are multiple email accounts created for send/receive and several of them receive emails at the same time, when the system polls the accounts and sends notifications, they all come from a single mail address.  They should send out via the correct mail address per group/account.

#### Steps To Reproduce:
Create several different mailboxes.  Send them EMails.  Poll the mailboxes with a single cron hit, and wait for the replies to come in.

#### Downloaded from
- [X] master-branch

**Comment by bhanu2217** [comment]
We are doing bulk close for all old issues. If the issue still exists in v1.10 or later. Please reopen
