### ISSUE TITLE
ITIL / ITSM Service Desk

### ISSUE THREAD

**Issue by ken2666** [ladybirdweb/faveo-helpdesk#65]
Can't see CMDB etc on the newly installed version. (Version Community 1.0.7.4)

also seeing " 500 Internal server Error. Be right back. Sorry! We are working on it." Error when navigating to workflow page.

any ideas?

Cheers
Ken

**Comment by ken2666** [comment]
Cant add email account 

![image](https://cloud.githubusercontent.com/assets/19742611/15797894/2412a6ae-2a44-11e6-8506-f808a3f7b8cd.png)

**Comment by bhanu2217** [comment]
Currently this feature is not there. It's already underdevelopment and will be released in July. Share your email address will email requirement and HTML prototype. Thank You 

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 4, 2016 at 10:46 AM, ken2666<notifications@github.com> wrote:   
Can't see CMDB etc on the newly installed version.

any ideas?

Cheers
Ken

**Comment by ken2666** [comment]
Thanks Bhanu.. Will do.. Could  you please also check the server errors we are getting on pages workflow and while creating emails?

Cheers
Ken

**Comment by bhanu2217** [comment]
Can you share the error message. If possible create test email account and share it with us so we can test. Email the details to support@ladybirdweb.com

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 4, 2016 at 11:04 AM, ken2666<notifications@github.com> wrote:   
Cant add email account

**Comment by mathieu-aubin** [comment]
Hi, please detail.

As much as this is a very pretty error message, what kind of output do you get in your log files?

There's plenty of **outside configurations** that WILL cause 500 errors to be displayed without the need for the actual app to be broken.

Issues/bug report (unless evident/unavoidable) generally contain environment variables and, as precise as the user can, ways to replicate

**Comment by ken2666** [comment]
Guys,

Error in apache logs is as below

 PHP Fatal error:  Call to undefined function App\\Http\\Controllers\\Admin\\helpdesk\\imap_open
() in /var/www/faveo/app/Http/Controllers/Admin/helpdesk/EmailsController.php on line 474, referer: http://support.infocellent.com/public/emails/create

Cheers
Ken

**Comment by bhanu2217** [comment]
I have requested our developers to look into it. Usually Saturday and Sunday we are off. 
We are also trying to reduce reliance on 500 error page as much as we can trying to display precise error message. Where ever we can catch  the error and know precise reason we display exact error message. Thank You. 
Sent from Yahoo Mail on Android 
 
 On Sat, Jun 4, 2016 at 11:17 AM, ken2666<notifications@github.com> wrote:  
Guys,

Error in apache logs is as below

PHP Fatal error: Call to undefined function App\Http\Controllers\Admin\helpdesk\imap_open
() in /var/www/faveo/app/Http/Controllers/Admin/helpdesk/EmailsController.php on line 474, referer: http://support.infocellent.com/public/emails/create

Cheers
Ken

**Comment by sujit223** [comment]
Hi ken we will try to have a look into your issue on monday

**Comment by mathieu-aubin** [comment]
Call to undefined function App\Http\Controllers\Admin\helpdesk\imap_open
Install php imap extension OR make sure it's enabled

**Comment by ken2666** [comment]
Thanks Mathieu,

That resolved the issue.

Cheers
Ken

**Comment by ken2666** [comment]
Hi Bhanu/Sujit

post enabling PHP imap. Workflow page is loading properly. Thanks for your help.

Cheers
Hitesh

**Comment by mathieu-aubin** [comment]
i should not have said anything about my feet and how i have to spend time at the hospital!!
