### ISSUE TITLE
ÄÖÜ in German mails

### ISSUE THREAD

**Issue by csaeum** [ladybirdweb/faveo-helpdesk#66]
The signature in German mails is displayed without umlauts.
The ÄÖÜäöü etc are incorrectly coded and are not displayed correctly.

So the signature is set in the Admin. In this ship but it looks like the screenshot
====
Mit freundlichen Grüßen aus Niederfüllbach

Christian Säum
Webmaster - SEO - Marketing

bk-solutions | Moebro
Kieselweg 6
D-96215 Lichtenfels

Moebro Office & Warehouse
Coburger Str. 8
D-96489 Niederfüllbach

Telefon: +49 (0) 9565 / 617 27 28
Telefax: +49 (0) 9574 / 65 24 24
Internet: http://www.Moebro.de
E-Mail: Christian.Saeum@Moebro.de

Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE 270966889

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
 
====
![umlautepng](https://cloud.githubusercontent.com/assets/1543510/15798992/d97abaa0-2a4d-11e6-919b-726d61823a8a.PNG)

**Comment by sujit223** [comment]
We will check this issue and will try to provide a fix as soon as possible

**Comment by mathieu-aubin** [comment]
I have a feeling this is due to the database collation, special characters not being supported.

**Comment by Gliba** [comment]
Same with Serbian chars čćšđž. I think the error is in the email fetching solution. Title is ok with characters čćšđž but body is messt up! Some html filter or ...?

**Comment by Gliba** [comment]
Maybe in momo-email-listener->mailController ...?

**Comment by mathieu-aubin** [comment]
What's the database collation setup to?
Look at the raw mail/smpt headers - if they are not fucked up, you have a database problem.

**Comment by bhanu2217** [comment]
We are using PHP mailer package which seems to be removing these German special character while sending out email. The encoding seems to be set wrongly in it. We are testing this further to find a solution and try to set UTF standard in this encoding.

**Comment by Gliba** [comment]
Email header is fine. DB colation is utf8_unicode_ci also fine.
Subject is passing fine with čćšđž characters but bodz does not. 

![image](https://cloud.githubusercontent.com/assets/1550782/15862957/a07ac6c4-2cd1-11e6-8718-4216dc9d8467.png)

**Comment by sujit223** [comment]
We have fixed this issue in our latest release. We will release by this week.

**Comment by csaeum** [comment]
When will this release.

The emails look partly like spam.

**Comment by bhanu2217** [comment]
We have pushed the new version here https://github.com/ladybirdweb/faveo-helpdesk
We have not yet made the release as we want to test more in detail tomorrow and than make a release.

**Comment by Gliba** [comment]
Tested new version and stil got problem with extended latin characters čćšđž

**Comment by bhanu2217** [comment]
Looking into it today

**Comment by sujit223** [comment]
Hi Csaeum,

We have tried to replicate this issue in Faveo directly. But didn't successfully replicated the issue. Instead everything worked quite well.
Here  are some screen shots
![capturegerman](https://cloud.githubusercontent.com/assets/11830376/16039225/423511da-3246-11e6-9ac2-a91bbf7fd51a.PNG)
![capturegerman2](https://cloud.githubusercontent.com/assets/11830376/16039226/423d8e50-3246-11e6-99af-5f72dc6acba0.PNG)
![capturegerman3](https://cloud.githubusercontent.com/assets/11830376/16039227/42429580-3246-11e6-9cc9-906a70882c4b.PNG)

Please let us know if the issue is still not fixed. We will try to login into your system and do the fixes

Thank You

**Comment by csaeum** [comment]
Ok, I'm sending you the data PHPMyAdmin and FTP and a Faveo account to support @?

**Comment by sujit223** [comment]
Thanks
