### ISSUE TITLE
PHP version issue??

### ISSUE THREAD

**Issue by AiFxApp** [ladybirdweb/faveo-helpdesk#6700]
Hi - I would love to test your build. 

Any chance you could advise me on how to overcome this?

My php version: (8.0.17)
Localhost (XAMPP)

 Problem 1
    - laravel/framework[v5.6.0, ..., v5.6.40] require php ^7.1.3 -> your php version (8.0.17) does not satisfy that requirement.
    - Root composer.json requires laravel/framework 5.6.* -> satisfiable by laravel/framework[v5.6.0, ..., v5.6.40].

**Comment by bhanu2217** [comment]
Added support for PHP 8.1. Closing the issue
