### ISSUE TITLE
Compose.json is messed , None of the php version is able to resolve dependencies

### ISSUE THREAD

**Issue by ubxty** [ladybirdweb/faveo-helpdesk#6755]
- Faveo Version : #.#.#
- PHP version :
- Database Driver & Version :
- Server specification :

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [x] release-tag

**Comment by bhanu2217** [comment]
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.
