### ISSUE TITLE
Email Fetching not working

### ISSUE THREAD

**Issue by ken2666** [ladybirdweb/faveo-helpdesk#68]
I can see that there are two cron items in CRON section but when i open the URL http://ourdomain/public/readmails

it opens up nothing but i get 200 OK status message.

I have tried sending emails to the email configured in faveo but they aren't processed.

Any ideas?

Cheers
Ken

**Comment by mathieu-aubin** [comment]
Hi Ken..
It 'opens up' nothing because this link is not meant to be visited from the outside world.
It's merely an internal link for php to process that reach out and gets emails. (hence setting up a cronjob on the system)

How did you configure the SMTP for Faveo

**Comment by ken2666** [comment]
This seems to be working now but is there any way to delete a user?

Date: Sat, 4 Jun 2016 22:40:02 -0700

**Comment by ken2666** [comment]
Also how we change the crone time to say 5 minutes?

**Comment by mathieu-aubin** [comment]
http://www.adminschoice.com/crontab-quick-reference
random link from google...

a crontab of every five minutes would look like this
*/5 * * * * action to be done

**Comment by ken2666** [comment]
Ok i thought, that this can be changed from the GUI. No worries.. I will give it a try from Linux crontab -e

Cheers mate.

**Comment by mathieu-aubin** [comment]
There will be ways to change the cronjob from the gui shortly, it's on the todo list Thank you

**Comment by ken2666** [comment]
Thanks Mate.. Any idea on how to remove the user especially customer user?

Date: Sat, 4 Jun 2016 23:11:28 -0700

**Comment by ken2666** [comment]
also
my cron tab looks like below

 5 * * * * /usr/bin/wget http://support.[ourdomain.com]/public/readmails
is that fine?
From: hitesh.vinzoda@live.com
To: reply@reply.github.com; faveo-helpdesk@noreply.github.com
CC: author@noreply.github.com
Subject: RE: [ladybirdweb/faveo-helpdesk] Email Fetching not working (#68)
Date: Sun, 5 Jun 2016 11:53:57 +0530




Thanks Mate.. Any idea on how to remove the user especially customer user?

Date: Sat, 4 Jun 2016 23:11:28 -0700

**Comment by mathieu-aubin** [comment]
No that's not...
what you are currently telling is to download the page at the address (wget is a downloader tool)
replace wget with curl and tell me if that solves anything ASAP

**Comment by mathieu-aubin** [comment]
Also if you have time right now please go to this address.
https://pad.zeroserieux.com/p/faveo-live-help

**Comment by SarfrazS** [comment]
Hi Mathieu-Aubin,

Currently there is no option to delete the user, you can just make the user inactive. We do plan to put this option in the future, we are just contemplating upon what should happen to this users replies and tickets after user is deleted.

Thank You.
