### ISSUE TITLE
Compatibility issue for PHP 7.2

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#681]
- Faveo Version : 1.10
- PHP version :7.2.7
- Database Driver & Version :MySQL5.6
- Server specification : Ubuntu18 LAMP stack

#### Description:
The application is breaking on various points while using with PHP 7.2.* Below are listed know issues so far
*Count method issue*
- Ticket reply not reading
- Unable to open organization view page
- Unable to see chart data
- When opening view all notification page it throws an error

#### Steps To Reproduce:
Use the application with PHP 7.2

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [X] release-tag

**Comment by mverma16** [comment]
Test comment for slack

**Comment by mverma16** [comment]
* Happening in change owner

**Comment by bindu95** [comment]
Version:1.10.1
PHP:7.2

**Ticket reply not reading**
--Both user/client and agent replies are fetching.

**Unable to open organization view page**
--Able to view organization page.

**Unable to see chart data**
--Able to see chart data in organization view,agent view,user view.

**When opening view all notification page it throws an error**
--Able to view all notification page.

**Happening in change owner**
--Able to change owner as new user as well as existing user also.
