### ISSUE TITLE
Script loading page blank

### ISSUE THREAD

**Issue by unlockpro2000** [ladybirdweb/faveo-helpdesk#684]
- Faveo Version : Latest Downloaded today from web
- PHP version : 7.2
- Database Driver & Version :
- Server specification :

#### Description:
Just downloaded today the script and install it
At the control was all ok ( all green )
Now trying to acess admin, page load blank and is automaticaly block
Chrome / firefox blocking for unsafe script

How to mofidy it plz ? wer to add a code ?

Thx 

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@unlockpro2000 Did you get it working, if yes then can you mention how did you solve the issue?
