### ISSUE TITLE
E-Mail Notification for Agent or Admins not Working

### ISSUE THREAD

**Issue by csaeum** [ladybirdweb/faveo-helpdesk#69]
The notification for administrators or agents sends us out emails.

The Cron are on and pick up emails etc goes. How can I log etc see around you to report bugs properly or exclude errors with us?

**Comment by SarfrazS** [comment]
Hi Csaeum,

Please send the ticket on Support@ladybirdweb.com.

Thank You

**Comment by bhanu2217** [comment]
1. The notification cron job will send one daily email to agent, manager of department & admins
2. We are working on integration Bugsnag error logger, once that is done, any error will get reported to us directly

**Comment by bhanu2217** [comment]
Bugsang integration is done in the latest edition. You can check error log settings in the admin panel
