### ISSUE TITLE
BUG- Agents are not able to see their tickets

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#690]
- Faveo Version : 1.10
- PHP version : 7.1/7.2
- Database Driver & Version : MySql
- Server specification : Ubuntu 18 configured with LAMP stack

#### Description:
After logging as an agent in ticket list pages table is not rendering data keep showing loader.

#### Steps To Reproduce:
Log in as an agent into the application and click on inbox/my tickets and other ticket page links.

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [X] release-tag

**Comment by mverma16** [comment]
Fixed in development.

**Comment by bindu95** [comment]
Version : 1.10.1 (master)
PHP version : 7.2

Replicated the above scenario, now agents are able to view the tickets in their inbox.
