### ISSUE TITLE
Agents are not able to see their tickets in departments folder

### ISSUE THREAD

**Issue by ideafixed** [ladybirdweb/faveo-helpdesk#702]
- Faveo Version : 1.10.1
- PHP version : 7.1
- Database Driver & Version : MySql
- Server specification : Ubuntu18

#### Description:
After logging as an agent, in Departments ticket list page is not rendering data .

#### Steps To Reproduce:
Log in as an agent, on the left side "Departments" --> my Department --> "open", ticket list page is not rendering data keep showing loader.

#### Downloaded from
- [X] master-branch

- [ ] development-branch

- [ ] release-tag
![error](https://user-images.githubusercontent.com/43880627/46536455-dc425700-c8ae-11e8-9fa0-6846fc578a71.png)

**Comment by mverma16** [comment]
To debug the issue first enable debugging mode. To enable debugging mode go to admin panel > errors and debugging > enable debugging mode.

Then check API response by opening developer console of the browser using `ctrl+shift+I`, navigate to **network** and then restrict it to show only XHR requests by clicking  XHR in filters. Once you are able to see API response share the error so I can troubleshoot the error.

**Comment by ideafixed** [comment]
![error](https://user-images.githubusercontent.com/43880627/46786141-46864c00-cd34-11e8-9299-ec2c834de2f1.png)

![errore2](https://user-images.githubusercontent.com/43880627/46786748-150e8000-cd36-11e8-802c-a377acd38a84.png)

![errore3](https://user-images.githubusercontent.com/43880627/46786927-9f56e400-cd36-11e8-8306-84424f1dbd1f.png)

GET /get-filtered-tickets?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=false&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=5&order%5B0%5D%5Bdir%5D=desc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&options=%7B%26quot%3Bdepartments%26quot%3B%3A%5B%26quot%3BArea+Funzionamento%26quot%3B%5D%2C%26quot%3Bstatus%26quot%3B%3A%5B%26quot%3BOpen%26quot%3B%5D%2C%26quot%3Bshow%26quot%3B%3A%5B%26quot%3Binbox%26quot%3B%5D%7D&_=1539241639244

**Comment by mverma16** [comment]
Check  [this commit](https://github.com/ladybirdweb/faveo-helpdesk/commit/99614b5ffd3c4e6ba6581fd1a62f69d9c84e242d) for the fix. Or update to v1.10.2 after tag is releases.

**Comment by ideafixed** [comment]
Now it works.
Many Thanks.
