### ISSUE TITLE
SSL Certificate shows as untrusted.

### ISSUE THREAD

**Issue by tmikaeld** [ladybirdweb/faveo-helpdesk#706]
Reference: 

https://www.ssllabs.com/ssltest/analyze.html?d=www.faveohelpdesk.com&latest

Latest Firefox is currently showing this:

![image 2018-10-13 at 1 33 54 pm](https://user-images.githubusercontent.com/907195/46904965-0fa76600-ceed-11e8-9c16-d096314ba2fe.png)

**Comment by bhanu2217** [comment]
We changed our SSL so thats why. You probably opened the website during transition period.
Please check again once.

**Comment by tmikaeld** [comment]
Alright, SSL Labs do the test on-request and it still shows the Revoced and Untrusted error, so you might want to take a closer look.
