### ISSUE TITLE
The language translation is easy, but what about Alerts ??

### ISSUE THREAD

**Issue by darkoor** [ladybirdweb/faveo-helpdesk#711]
Hello,
how can I translate system alerts to other language than English (my language Polish) (e.g.: Alarm ! The email field is required. ...) ? 
There are no alerts in lang.php file.

Regards, Darek

---
Faveo Version : Community 1.10.2

**Comment by mverma16** [comment]
You can update `validation.php` to translate the validation alert messages.

**Comment by darkoor** [comment]
ok
