### ISSUE TITLE
Forgot password form - validation exception

### ISSUE THREAD

**Issue by darkoor** [ladybirdweb/faveo-helpdesk#712]
- Faveo Version : Community 1.10.2
- PHP version : 7.1.23
- Database Driver & Version : MySQL 5.7.24
- Server specification : Ubuntu 16.04.1

#### Description:
ValidationException {#1082 ▼
  +validator: Validator {#1081 ▶}
  +response: null
  +status: 422
  +errorBag: "default"
  +redirectTo: null
  #message: "The given data was invalid."
  #code: 0
  #file: "/var/www/faveo/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Validation/Validator.php"
  #line: 306
  trace: {▶}
}

#### Steps To Reproduce:
Client Panel -> Logon -> Forgot password -> email field BLANK -> click on the "Send" button
I get validation exception (screen2).
Address page: "http://192.168.8.43/password/email"

![obraz](https://user-images.githubusercontent.com/36037799/48263553-c0d6e880-e426-11e8-8a46-eb601b2db402.png)
![obraz](https://user-images.githubusercontent.com/36037799/48263557-c7fdf680-e426-11e8-80fd-bb9cb67e2086.png)

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@darkoor thanks for reporting the issue, I'll share the patch commit soon so you can fix it from your end before we release next update.

**Comment by mverma16** [comment]
Check commit [#709931a](https://github.com/ladybirdweb/faveo-helpdesk/commit/709931ac59549ca669dcd0a147de39a03a677dd9) to fix the issue.
