### ISSUE TITLE
Email - can not authenticate to POP3 server

### ISSUE THREAD

**Issue by darkoor** [ladybirdweb/faveo-helpdesk#717]
- Faveo Version : Community 1.10.2
- PHP version : 7.1.23
- Database Driver & Version : MySQL 5.7.24
- Server specification : Ubuntu 16.04.1

#### Description:
When trying to configure email to fetch with POP3, Faveo showing an error message:
"**Can not authenticate to POP3 server: Authentication failed**."

In the log (Admin Panel -> Logs):
imap_open(): Couldn't open stream {pop3.bjanex.pl:110/pop/tls/novalidate-cert} {"exception":"[object] (ErrorException(code: 0): imap_open(): Couldn't open stream {pop3.bjanex.pl:110/pop/tls/novalidate-cert} at /var/www/faveo/faveo-helpdesk/vendor/tedivm/fetch/src/Fetch/Server.php:291) 

or

imap_open(): Couldn't open stream {pop3.bjanex.pl:995/pop/ssl/novalidate-cert} {"exception":"[object] (ErrorException(code: 0): imap_open(): Couldn't open stream {pop3.bjanex.pl:995/pop/ssl/novalidate-cert} at /var/www/faveo/faveo-helpdesk/vendor/tedivm/fetch/src/Fetch/Server.php:291) 

I tested pop3 connection from Linux:
1) over port 110
root@faveo:~# nc my.mail.server 110
+OK POP3 localhost.localdomain vXXXXXX server ready
user MY.USER
+OK
pass MY.PASS
+OK Logged in.
list
+OK 1 messages:
1 6115
.
quit
+OK Logging out.

2) over port 995
root@faveo:~# openssl s_client -connect my.mail.server:995
CONNECTED(00000005)
...... cert details ...........
+OK POP3 localhost.localdomain vXXXXXX server ready
user MY.USER
+OK
pass MY.PASS
+OK Logged in.
list
+OK 1 messages:
1 6115
.
quit
+OK Logging out.

Both connections are correct.

**With only SMTP configuration it works.**

#### Steps To Reproduce:
Admin Panel -> Emails -> Create email -> Email information and settings ...
My config:
- protcol (**PO3**)
- email address
- user name (email account <- it isn't email address (MY.USER))
- password (MY.PAS)
- mail server (my.mail.server)
- port (110 or 995)

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
@darkoor will look into it and update you soon.

**Comment by darkoor** [comment]
As I understand it, the problem unsolvable. it's a real shame. Regards..
