### ISSUE TITLE
Artisan command for listing registered routes does not work

### ISSUE THREAD

**Issue by mverma16** [ladybirdweb/faveo-helpdesk#727]
- Faveo Version: 1.9.6 and newer
- PHP version: 7.1/7.2
- Database Driver & Version :MySql 5.7
- Server specification: NA

#### Description:
When trying to run artisan command `php artisan route:list` system throws an exception shown in  the image below
![screenshot 2018-12-27 at 9 50 55 am](https://user-images.githubusercontent.com/10759797/50465378-f3c84200-09bc-11e9-8975-64901aa20832.png)

#### Steps To Reproduce:
Run artisan command in terminal.

#### Downloaded from
- [X] master-branch

- [X] development-branch

- [X] release-tag

**Comment by abstruse98** [comment]
I also have this problem

**Comment by privateWilliam** [comment]
Same problem for me.
Fresh installation (from master branch) without any modification.
There is no PushNotificationController.

**Comment by qq609641121** [comment]
![image](https://user-images.githubusercontent.com/33113407/95644708-0573ce80-0aeb-11eb-95e3-04b2d882c8fd.png)
how to fix it ?
