### ISSUE TITLE
question(pricing): Faveo cloud for open source users

### ISSUE THREAD

**Issue by Kristinita** [ladybirdweb/faveo-helpdesk#732]
### 1. Question

Is possible, that cloud (not self-hosted) Faveo help desk free for open source, non-commercial projects under certain conditions?

If no, is it planned in the future?

### 2. Not helped

I try find this information in Google and official Faveo site, and I found only these pages:

+ [**Faveo self-hosted for open source**](https://www.faveohelpdesk.com/pricing/#1539180063827-b8ee4b2d-7451)
+ [**We Love Open Source**](https://www.faveohelpdesk.com/love-open-source/)

I didn't find the answers to my question.

### 3. Examples in other services

Another help desk systems provide free cloud access for open source projects, examples:

+ [**JIRA**](https://www.atlassian.com/software/views/open-source-license-request)
+ [**YouTrack**](https://www.jetbrains.com/shop/eform/opensource?product=ALL)

Thanks.

**Comment by Kristinita** [comment]
**Type: Question** :question:

@bhanu2217, will the question be answered? You have closed the issue without leaving a single comment.

Thanks.

**Comment by bhanu2217** [comment]
> ### 1. Question
> Is possible, that cloud (not self-hosted) Faveo help desk free for open source, non-commercial projects under certain conditions?
> 
> If no, is it planned in the future?
> 
> ### 2. Not helped
> I try find this information in Google and official Faveo site, and I found only these pages:
> 
> * [**Faveo self-hosted for open source**](https://www.faveohelpdesk.com/pricing/#1539180063827-b8ee4b2d-7451)
> * [**We Love Open Source**](https://www.faveohelpdesk.com/love-open-source/)
> 
> I didn't find the answers to my question.
> 
> ### 3. Examples in other services
> Another help desk systems provide free cloud access for open source projects, examples:
> 
> * [**JIRA**](https://www.atlassian.com/software/views/open-source-license-request)
> * [**YouTrack**](https://www.jetbrains.com/shop/eform/opensource?product=ALL)
> 
> Thanks.

The cloud hosted Faveo product, is a different code base from Community(open source) version and is not offered free of cost. 

If you want to use free version of Faveo, best is to host on your own server.

We are a small organisation, We will not be able to bear the server cost for free service.
