### ISSUE TITLE
How To Download ng full version

### ISSUE THREAD

**Issue by johnkalangha** [ladybirdweb/faveo-helpdesk#734]
should i download the master? is it full version and latest? thanks you

**Comment by mverma16** [comment]
You can download the latest version either from [master](https://github.com/ladybirdweb/faveo-helpdesk/archive/master.zip) or from a tagged released [version v1.10.4](https://github.com/ladybirdweb/faveo-helpdesk/releases/tag/v1.10.4) both contain the full version of community edition.

However, if you are not looking forward to changing the source code and want a complete solution to bootstrap your Helpdesk System as soon as possible then you might want to try [Faveo Freelancer](https://www.faveohelpdesk.com/pricing/).

It is totally free and has all the advanced features available in the paid versions of Faveo.
