### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by c0fe** [ladybirdweb/faveo-helpdesk#74]
I am getting Error 500 just after uploading the files. I am running the following:

Debian 8
NGINX
PHP 5.6.20-0
Ajenti

I have selected that PHP is enabled but not sure what is going wrong here.

**Comment by bhanu2217** [comment]
Enable debugging mode and see the exact error message.
Location: /config/app.php debug='true'

**Comment by c0fe** [comment]
This is the error I get:

https://dpaste.de/kXxy

**Comment by c0fe** [comment]
Actually I saw that mcrypt wasn't enabled, I ran these commands: https://www.digitalocean.com/community/questions/enable-mcrypt-extension-in-nginx and now I get error 404: http://kb.polarpos.com/public/step1

**Comment by mathieu-aubin** [comment]
not only you need to restart nginx but you need to restart php-fpm, the core of php.
