### ISSUE TITLE
Authentication Broken, Temp Workaround

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#76]
app\Http\Controllers\Auth\AuthController.php

The function confirmIPAddress is currently failing. It returns the following error:
[2016-06-15 13:07:16] local.ERROR: ErrorException: Trying to get property of non-object in /home/vagrant/Code/app/Http/Controllers/Auth/AuthController.php:294

I tried to fix the root cause, but was unsuccessful. In the meantime, I have bypassed the function by placing  ' return 0; ' before line 294 to allow the application to function. But this is bypassing security functionality.

**Comment by sujit223** [comment]
Have Pulled the latest code

**Comment by bhanu2217** [comment]
You can download the master branch, that the latest code for 1.0.7.5. Release is not yet done as we are still testing the project in detail and release will be done probably by today evening or tomorrow after testing and bug fixing.
