### ISSUE TITLE
Blank site 

### ISSUE THREAD

**Issue by lukasd1** [ladybirdweb/faveo-helpdesk#7660]
I'm trying to install faveo but i have only blank white site , i checked the extensions etc and i have everything..... 
there is no GUI , i tried to install manually but the effect is the same. 
Any ideas ?

**Comment by lukasd1** [comment]
system is  : ubuntu server 22.04

**Comment by RafficMohammed** [comment]
@lukasd1 Open app/Exception/Handler.php and put dd($e) in  50 line and share me screenshot

**Comment by bhanu2217** [comment]
Please try Faveo Helpdesk Community version 2.0.0 and let us know if the issue is still occurring. For now closing the issue.
