### ISSUE TITLE
Auto complete users while creating a ticket from the backend

### ISSUE THREAD

**Issue by supportreq** [ladybirdweb/faveo-helpdesk#78]
Dear Team,

While creating a ticket from the create a ticket page from the backend, instead of entering the client details it should show an auto complete of the registered email id.. once the email is selected it should complete the phone, name and other parameters.. 

Not sure if this is present..

**Comment by sujit223** [comment]
Thanks for the idea we do have this in our roadmap

**Comment by mathieu-aubin** [comment]
Might have to use another method with Laravel but a very simple way to use auto-complete on html* files is to revert to using **typeahead.js**. It's powerfull, yet lightweight...
http://twitter.github.com/typeahead.js/
https://github.com/twitter/typeahead.js

**Comment by mbiolsi** [comment]
YES PLEASE! By NOT having this as a feature, it creates opportunity for agent to type in incorrect email and not have it get to client. It also provides the chance for a client to have multiple emails on file and then they cannot see all of their tickets when the log in.

**Comment by bhanu2217** [comment]
We are already working on this feature and it should be part of next 1 or 2 releases
