### ISSUE TITLE
Is Faveo still an active project ?

### ISSUE THREAD

**Issue by pvi-github** [ladybirdweb/faveo-helpdesk#7875]
Dear Faveo Team,

It seems that the latest release v1.11 is 2 about 2 years old.

I downloaded it and it works only with PHP 7.3 which is deprecated. For PHP 7.4, which is deprecated too i had to patch the code to make it run.

With PHP 8.1 i did not succeed.

Though the UI seems really nice... and the set of features really impressive.

Can you tell me the status of this project, if there is a roadmap for PHP 8.1 & PHP 8.2...

I need to know if i can tell people to use it with confidence of if they should move on and find an other opensource helpdesk system

Thanks in advance for your hints...

Kind regards,

**Comment by pvi-github** [comment]
The problem with the bot linked to @bhanu2217 account is that with the amount of issues opened by this robot the "real" issues created by users are like a handful of needles in a huge haystack...

Good luck to find them. 

You guys might want to address this point because it makes this issue tracker close to useless

**Comment by pvi-github** [comment]
I added a specific issue #7884 for the  @bhanu2217 robot account because it is not the same topic.

**Comment by bhanu2217** [comment]
Project is active, we have just made the release and we are further working on bug fixes and have another planned release this month

**Comment by pvi-github** [comment]
Hello,

Thanks for your answer. A bit late for my own deadlines : for lack of PHP8 support and uncertainty about paid support on free version i had to down-rate Faveo a little bit.

And as a consequence it was not chosen by the decision board... you have missed a huge french Ministry as a customer for the next 15 years guys, sorry :-/

I'll keep an eye on Faveo to see how it evolves, because it remains something potentially interesting. Maybe an other opportunity will raise later.

Regards,
