### ISSUE TITLE
Solve the flood of issues sent by bhanu2217 robot

### ISSUE THREAD

**Issue by pvi-github** [ladybirdweb/faveo-helpdesk#7884]
- Faveo Version : Not applicable
- PHP version : Not applicable
- Database Driver & Version : Not applicable
- Server specification : Not applicable

#### Description:
A robot obviously floods the Github repository with issues linked (probably) to the automated tests system getting very angry :)

#### Steps To Reproduce:
Just browse the Issues tab and see the vast amount of issues created by bhanu2217 account.

CI/CD Is not supposed to create such floods... unless faveo-helpdesk is abandoned you'd better tune your testing system to make sure the Issue system remains useable... or maybe use an external issue system to separate issues raised by humans from issues raised by the crazy robot...

#### Downloaded from
- [ ] master-branch
Not applicable
- [ ] development-branch
Not applicable
- [ ] release-tag
Not applicable

**Comment by bhanu2217** [comment]
Closing all bugsnag issues
