### ISSUE TITLE
Existing Bugs

### ISSUE THREAD

**Issue by RafficMohammed** [ladybirdweb/faveo-helpdesk#7916]
https://docs.google.com/document/d/1aZVQKevsCHaEAoa8vXYfSmaVgglLbrQnvV6b00nI2c0/edit

**Comment by Noor-mommadhi** [comment]
start development date:(20/2/2022)
Fixed issue:
1)Issue 9:For each ticket, the Ticket conversion/description is shown twice. (1 day)

2)Issue 15:Data is not vanishing in create organization page.click on create, input the data to organization name and click on close (half day)

3) Issue 47:While adding the language for the ISO-CODE, throwing the wrong alert message for the number of characters.(2hr)
