### ISSUE TITLE
Helpdesk - URL error

### ISSUE THREAD

**Issue by alexisskeates** [ladybirdweb/faveo-helpdesk#8]
I've managed to get Faveo working on my webhost (TSOHOST). All seems to working fine and managed to get the cron job working as well.

The only issues I have come across so far is when I go into the Admin Panel then click on Manage and then Help Topics the page does not load. I get an error message screen shot atached

![screen shot 2015-12-18 at 16 05 41](https://cloud.githubusercontent.com/assets/10001929/11901114/bd9285f6-a5a1-11e5-890c-d3838032af83.png)

The other one is when I add a new agent I get the following message. The agent adds to Faveo even though Faveo errors.

![screen shot 2015-12-18 at 16 10 40](https://cloud.githubusercontent.com/assets/10001929/11901181/0edc7f7a-a5a2-11e5-8050-6d63cec10802.png)

Any suggestions would be great.

**Comment by ayurmedia** [comment]
confirmed, i get the same "emailadd" is undefined bug.

**Comment by sujit223** [comment]
We have fixed the "emailadd" issue. But we cannot replicate the "helptopic page" issue. Please check that you are using the latest version of faveo. 
Thank You

**Comment by alexisskeates** [comment]
I was using 1.0.3 at the time of this comment which was the current build on github. I see it's now at 1.0.3.2 I'll see if I can update it to that. I assume I can just do a git update to bring it up to date. Hopefully that will fix it

**Comment by bhanu2217** [comment]
If you still face this issue, do lets us know the exact steps to replicate the issue.
Thank You.

**Comment by alexisskeates** [comment]
So just pulled 1.0.3.2 from github and that has fixed the add user account. Just checked the help topic and that is still producing the same issue. 

The full error message that displays. Basically just clicking on the Help Topic button from within the Admin Panel produces that error for me.

![screen shot 2015-12-21 at 09 16 42](https://cloud.githubusercontent.com/assets/10001929/11927398/2d976bb8-a7c4-11e5-814a-fd9481a59e1a.png)
![screen shot 2015-12-21 at 09 16 51](https://cloud.githubusercontent.com/assets/10001929/11927418/4ec7ec7c-a7c4-11e5-84d3-22298dc47322.png)
![screen shot 2015-12-21 at 09 17 03](https://cloud.githubusercontent.com/assets/10001929/11927421/540fc628-a7c4-11e5-81ea-47e6d2137fcb.png)
![screen shot 2015-12-21 at 09 17 09](https://cloud.githubusercontent.com/assets/10001929/11927424/59239a0e-a7c4-11e5-8e76-f75d4a1693b7.png)

**Comment by sujit223** [comment]
Hi can you create a ticket at support@ladybirdweb.com so that I can talk to you personally and solve this Issue
