### ISSUE TITLE
HTTP ERROR 500 step6post

### ISSUE THREAD

**Issue by bigAboo80** [ladybirdweb/faveo-helpdesk#8009]
- Faveo Version : ladybirdweb/faveo-docker:latest
- PHP version :PHP 7.1.20
- Database Driver & Version :mariadb 
- Server specification :Ubuntu server 22.04

#### Description:
Get this error after step 5 

https://hd.biz-cloud.ru/step6post

HTTP ERROR 500

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment]
Minimum PHP version required for Faveo to work is PHP 8.1

**Comment by bigAboo80** [comment]
I've deployed image from the docker hub, with tag latest)

**Comment by bigAboo80** [comment]
> > I've deployed image from the docker hub, with tag latest)
> 
> Please share the link here, so we can correct it there

https://hub.docker.com/r/ladybirdweb/faveo-docker

**Comment by bhanu2217** [comment]
> https://hub.docker.com/r/ladybirdweb/faveo-docker

Will get it updated, once done will update here

**Comment by bigAboo80** [comment]
> > https://hub.docker.com/r/ladybirdweb/faveo-docker
> 
> Will get it updated, once done will update here

Can you inform me about update here?

**Comment by shiekhaasif** [comment]
Please install Faveo on Docker using this link. 
<a href="https://docs.faveohelpdesk.com/docs/installation/providers/enterprise/faveo-helpdesk-docker/" target="_blank" rel="noopener">Faveo on Docker</a>
