### ISSUE TITLE
Client Panel theme update 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#8118]
Client Panel template is available here https://github.com/ladybirdweb/faveo-helpdesk/issues/3418
Our client panel template now also has support for Bootstrap 5.

For now use Bootstrap 4 template for client panel as Admin LTE currently doesn't support Bootstrap 5.

**Comment by Noor-mommadhi** [comment]
R&D Time: 2 hr
task breakdown: using the knowledge base dark theme(latest)
development time: 3 days
