### ISSUE TITLE
Helpdesk Freelance - app.css doesn't get my changes 

### ISSUE THREAD

**Issue by kilian099** [ladybirdweb/faveo-helpdesk#8152]
- Faveo Version : Version v2.0.1
- PHP version : 8.1
- Database Driver & Version : MariaDB 10.3 database server
- Server specification : Rocky linux 8.7

#### Description:

I have tried to customize the CSS style from the app, and make some re-branding

#### Steps To Reproduce:

change css selectors from app.css , no differences.

#### Downloaded from
- [ X ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment]
- We recommend to make branding changes from admin panel
- If you make any changes to source file, you will loose them when new update comes
- You can also think of building plugins on top of Faveo for your changes, that way changes will not be lost with each update

**Comment by kilian099** [comment]
> * We recommend to make branding changes from admin panel
> * If you make any changes to source file, you will loose them when new update comes
> * You can also think of building plugins on top of Faveo for your changes, that way changes will not be lost with each update

How would I get the baranding changes from admin panel? Is this a custom plugin I need to build ? or You guys supply in the community version?

**Comment by raghavfaveo** [comment]
Hi @kilian099 

You can make branding changes via Admin Panel -> Settings-> Company

Here you get the below options:
1. Change Footer
2. Change Color Pallette 
3. Change Header, Button colors
4. Use Your Own Logo, etc

**Comment by kilian099** [comment]
> Hi @kilian099
> 
> You can make branding changes via Admin Panel -> Settings-> Company
> 
> Here you get the below option to Use Your Own Logo, etc

That's for enterprise version, the Freelancer edition that's no include that. It's there any other method where I can see that feature? Thanks.

**Comment by raghavfaveo** [comment]
Hi @kilian099 

The Freelancer Edition also supports choosing your own logo. You can upload your own logo from Admin Panel -> Company

![image](https://user-images.githubusercontent.com/106146976/233617036-49163096-9045-484e-9f0e-5228c9cd4d8e.png)

**Comment by bhanu2217** [comment]
Our next release will include following

All client panel, agent and admin panel theme, js, css will be updated to latest version. You can check the progress here https://github.com/ladybirdweb/faveo-helpdesk/projects/4

If it's possible for you. You can download the Freelancer version from here https://billing.faveohelpdesk.com/group/1/2 and look at this feature in the freelancer product. If you can implement this feature in community version and raise P.R, we will get it tested, merged and make a release for it. 

To help you build this feature, we can schedule a meeting with our developer who can guide you how to make it generically, so all community can benefit from it.
