### ISSUE TITLE
Problem with type "select"

### ISSUE THREAD

**Issue by Hxcktivist** [ladybirdweb/faveo-helpdesk#8168]
- Faveo Version : 2.0.1 fresh install
- Database Driver & Version : MariaDB 10.4.28 xampp

#### Description:
Good afternoon, there is a problem.
When creating a form with the "select" option and adding it to the ticket. On the user side, a 404 error appears and agent. But on the administrator side everything is fine.
#### Steps To Reproduce:
->Log in administator
->Amin panel
->Manage
->Forms
->Create form
->Type "select"
->Help topics
->Support query ( Default ) edit
->Custom form
->Select from with "select"
->Udpate

->log out

And submit a ticket, scroll down, and we have error

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by DhanyaChengappa** [comment]
@Noor-mommadhi Please replicate this and we can then add to a milestone

**Comment by DhanyaChengappa** [comment]
@SarfrazS Please help with replicating this
