### ISSUE TITLE
Cant able to add any Email Id

### ISSUE THREAD

**Issue by azhab98** [ladybirdweb/faveo-helpdesk#8169]
- Faveo Version : 
- PHP version : 8.1
- Database Driver & Version : MariaDB
- Server specification : Windows 12 - Apache 

#### Description: Cant able add my email id. It shows same message again and again
![image](https://user-images.githubusercontent.com/114986919/234782091-017f5875-9ff1-46c7-93ea-135e894e1980.png)

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by bhanu2217** [comment]
- Please check server error log for any errors
- Are you getting any error messages or warning why saving email?
- which email are you trying to configure eg. gmail, office 365 etc?

**Comment by azhab98** [comment]
Errors:
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr: PHP Fatal error:  Uncaught ErrorException: Unknown: [AUTHENTICATIONFAILED] Invalid credentials (Failure) (errflg=1) in Unknown:0, referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr: Stack trace:, referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr: #0 C:\\Apache24\\htdocs\\cua-helpdesk-master\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Unknown: [AUTHE...', 'Unknown', 0), referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr: #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(8, 'Unknown: [AUTHE...', 'Unknown', 0), referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr: #2 {main}, referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create
[Thu Apr 27 23:58:05.886401 2023] [fcgid:warn] [pid 5992:tid 984] [client ::1:49442] mod_fcgid: stderr:   thrown in Unknown on line 0, referer: http://localhost/cua-helpdesk-master/public/index.php/emails/create

Are you getting any error messages or warning why saving email? - **No**
which email are you trying to configure eg. gmail, office 365 etc? - **Gmail**

**Comment by bhanu2217** [comment]
To configure gmail. You cannot put regular gmail password. You need to generate app password.

Check this article https://support.faveohelpdesk.com/show/how-to-configure-system-support-emails

**Comment by azhab98** [comment]
Tried this also, same issue! In faveo, it's not showing any error message also other than log!

**Comment by bhanu2217** [comment]
Download and install freelancer version from here https://billing.faveohelpdesk.com/group/1/2 Are you able to configure email on it?

**Comment by azhab98** [comment]
again i have to configure all! cant able to do in this?

**Comment by bhanu2217** [comment]
> again i have to configure all! cant able to do in this?

I am trying to see if the issue is in the app or your server configuration
The logs you shared, the message it shows is that authentication is failing. That means invalid credentials passed.

**Comment by azhab98** [comment]
I tried the password still not working! anything i have to do in php files?

**Comment by bhanu2217** [comment]
> I tried the password still not working! anything i have to do in php files?

I recommend following

- Read this article once again https://support.faveohelpdesk.com/show/how-to-configure-system-support-emails You need to enter gmail address and app password in Faveo and not email password
- Install Faveo on a online server instead of local host, You can even use AWS free tier service for testing. Follow installation document from here https://docs.faveohelpdesk.com
