### ISSUE TITLE
Organizations not showing

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#85]
Organizations page on the dashboard is returning multiple pages, but stating "No matching records found." I cannot see the organizations available.

![orgs](https://cloud.githubusercontent.com/assets/4474921/16150828/a0274ba0-3467-11e6-8e38-077a082c30f5.png)

**Comment by SarfrazS** [comment]
Hi Ajanes3,

It seems that the organization is working please let us know how do we replicate the issue to get that error you mentioned.

Thank You

**Comment by ajanes3** [comment]
I am still running into this issue.

I have added a total of three organizations.

As soon as I add a forth, it stops working.

I am doing additional testing to see if the data itself is the culprit.

**Comment by bhanu2217** [comment]
I hope you are using latest version 1.0.7.8
@SarfrazS Lets test this in detail

**Comment by ajanes3** [comment]
Additional testing results. I deleted the third one and attempted to re add it. Adding the third organization made the results disappear again. I am also experiencing similar symptoms with tickets.

**Comment by ajanes3** [comment]
I have found the issue.

chumper/datatable has released a fix for this issue caused by laravel 5.2. However, faveo is not on the branch with the fix. Changing the branch to master is not a drop in replacement fix either.

The only fix I have is to modify the chumper/datatable source within the vendor folder.

vendor\chumper\datatable\src\Chumper\Datatable\Engines\CollectionEngine.php

Edit on line 152. Change this:
`return $this->workingCollection->slice($this->skip,$this->limit)`
to this
`return $this->workingCollection->slice($this->skip,$this->limit)->values();`

This fix is further documented at [this link](https://github.com/Chumper/Datatable/pull/372).

**Comment by mverma16** [comment]
@ajanes3 thanks for notifying the issue. We'd been facing this issue after updating Laravel version to 5.2. We'd raised this issue [here](https://github.com/Chumper/Datatable/issues/366), and implemented the suggested fix in [v1.0.7.5](https://github.com/ladybirdweb/faveo-helpdesk/blob/a3fbf1acd4868728fb3d86a7a46ddf3fa9491fd1/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php)
Please check version of your application and update your application version to the latest version which is [`v1.0.7.8`](https://github.com/ladybirdweb/faveo-helpdesk/).

**Comment by ajanes3** [comment]
I am now. Composer update wants to change the file back to the incorrect code. So, for the moment, I am just manually editing every time i composer update.

**Comment by mverma16** [comment]
@ajanes3  Sorry for the delay in response, but in production stage user should not use composer update command as it may result in errors. We've tried to modify chumper package  at certain extent. Updating composer may revert the changes and error may occur. We are planning to handle this scenario for developers so that they can write their code on the top of Faveo core functions.
