### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by jjplaying** [ladybirdweb/faveo-helpdesk#87]
Hi,

Currently, you are always redirected to the http:// version of Faveo, and if you call it with https://, assets like the CSS files don't load because they are still http://. Maybe it would be important to implement it because many people, especially bigger companies use SSL.

**Comment by mathieu-aubin** [comment]
You are right on that.

It's something Faveo-Helpdesk's team is working on, amongst many other developments for the forseable future.

Definitively, we can't have hardcoded 'http' links that prevent proper SSL functionning. Hardcoded 'http' links generate mixed-content which is interpreted as miss configuration of SSL from the server thus rendering an unsecure warning in the browser and preventing the magical 'green lock' (all-OK) from being visible.

Thanks for submitting this, we really value your input.
Keep the feedback coming!

**Comment by bhanu2217** [comment]
We are still contemplating on this on how to go forward. 

**This is how we want to add this support:**
We want to have URL field in the settings page(Admin panel) and what ever URL you choose/set here appropriate redirection will be set using file moment, changes in Laravel structure wherever required, .htaccess access changes and so on

**This will solve two issues**
- Have HTTPS URL throughout including assets
- Remove public from URL if desired

We will  try and see this is released in version 1.0.7.7 or 1.0.7.8

**Comment by mbiolsi** [comment]
I am on an SSL cert for testing - if you need someone to test.

**Comment by mbiolsi** [comment]
We simply added an htaccess rule to force SSL
`RewriteEngine On 
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://my.domain.name/$1 [R,L]`

**Comment by mathieu-aubin** [comment]
@mbiolsi yes, nothing 'new' with what you posted..
Problem remains the links are hardcoded to http in the templates, thus resulting in mixed-content warning.
[https://github.com/ladybirdweb/faveo-helpdesk/issues/87#issuecomment-226961159](url)

**Comment by bhanu2217** [comment]
In next upcoming 1 or 2 releases we will put a fix for it and you will be able to control http or https redirection from Admin panel.

**Comment by jakobii** [comment]
I tried fixing the mixed content error by editing the css files. the mix content errors only got worse... lol. looking forward to the update.

**Comment by bhanu2217** [comment]
We have already implemented SSL option in new version. In the next release you should see it

**Comment by retorquere** [comment]
Where do I enable this? I can't find it anywhere in the admin panel. 

An alternative solution would have been to use [protocol-less URLs](https://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just) and it would have just worked without needing configuration.

**Comment by retorquere** [comment]
I see now Faveo already uses protocol-less URLs in many places, but some css files still explicitly import (e.g.) google fonts from http.

**Comment by retorquere** [comment]
Adding this to my `.htaccess` made the problem go away:

```
<ifModule mod_headers.c>
  Header set Content-Security-Policy "upgrade-insecure-requests; default-src https:"
</ifModule>
```

**Comment by retorquere** [comment]
except I can't get faveo to do a http-to-https redirect.

**Comment by retorquere** [comment]
So this is what did it for me (so far): in `.htaccess` and `public/.htaccess`, add this:

```
<ifModule mod_headers.c>
  Header set Content-Security-Policy "upgrade-insecure-requests; default-src https: 'unsafe-inline' 'unsafe-eval'"
</ifModule>
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</ifModule>
```
