### ISSUE TITLE
Usernme Email Provider Support

### ISSUE THREAD

**Issue by purwadarozatun** [ladybirdweb/faveo-helpdesk#89]
So My office has sendgrid account with username instead email for email service authentication ,  it will be cool if you guys can make sendgrid user use their username to for authentication  .

cheers

**Comment by purwadarozatun** [comment]
btw , i already make this enhancement happen , if you guys  want me to merge to current dev brach ,  i will make pull reuqest ?

cheers

**Comment by bhanu2217** [comment]
We are working on release of version 1.0.7.7, hopefully we will be able to release it today.
This is our dev branch https://github.com/ladybirdweb/faveo-helpdesk/tree/Faveo-development-branch but this is not the active one, active development we have in a different fork. After we make the release today to master we will update the same code to Dev branch, you can merge your code with dev, we will test it and make it part of next release which is 1.0.7.8

**Comment by purwadarozatun** [comment]
Oke , cool 😄 i will wait for the merges

**Comment by mverma16** [comment]
@purwadarozatun  We have released [Faveo v1.0.7.7](https://github.com/ladybirdweb/faveo-helpdesk). You can now merge your code in [Faveo-dev-branch](https://github.com/ladybirdweb/faveo-helpdesk/tree/faveo-dev)  and send us a merge pull request we will test it and make it a part of next release.
Thanks.

**Comment by mverma16** [comment]
@purwadarozatun Our team is waiting for your merge request, so that we can test your sendgrid authentication enhancement code and make it a part of Faveo's next release. You can merge your code in [Faveo-dev-branch](https://github.com/ladybirdweb/faveo-helpdesk/tree/faveo-dev).

**Comment by brianjking** [comment]
@purwadarozatun Any idea if this would work with Mailgun too? I hope you can get this PR submitted.

**Comment by mverma16** [comment]
@purwadarozatun Have you sent a PR?

**Comment by purwadarozatun** [comment]
@mverma16 Sorry For late comment , 
I cant manage to make the PR because all my data was deleted that time . 😭 
Again Im Sorry
