### ISSUE TITLE
form fields are not repopulated on validation errors

### ISSUE THREAD

**Issue by ayurmedia** [ladybirdweb/faveo-helpdesk#9]
if the form fields have an error in validation rules the form is emptied and the user has to type the ticket again from scratch. its common practice now to repopulate the form with the last state before the error. also there is a limit on the ticket description-text of more then x characters, causing an validation error "description too short" and deleting all fields. there should be a hint in the form that description needs to be of minimum length. this makes the usage of faveo very frustrating, as it clears userdata on mistakes.

**Comment by sujit223** [comment]
This issue has been resolved in v1.0.3.4. Thank you
