### ISSUE TITLE
Hanging on URL: faveo-helpdesk-master/public/500

### ISSUE THREAD

**Issue by easternspear** [ladybirdweb/faveo-helpdesk#92]
I'm not sure what's the problem, bt after step 5 and clicked install, it runs for a long time and stop at a page that shows:
The localhost page isn’t working

localhost redirected you too many times.
Try:
Reloading the page
Clearing your cookies
ERR_TOO_MANY_REDIRECTS

Regards

**Comment by bhanu2217** [comment]
The way we were using sessions before is not working in Laravel 5.2 after the upgrade from 5.0 to 5.2, we have fixed this issue. We are just testing Faveo version 1.0.7.7 in detail and will make a release today.
