### ISSUE TITLE
ÄÖÜ in German mails #2

### ISSUE THREAD

**Issue by csaeum** [ladybirdweb/faveo-helpdesk#94]
ÄÖÜ in German Subject

In the emails it now works great but unfortunately not in the subject.

See Screen

In German the subject in Screenshots:
Maße des Küchenschranks PS372[#AABC-0028-0000028]
Anfrage Farbmuster und Küchenschränke[#AAAF-0005-0000005]
![faveo-subject](https://cloud.githubusercontent.com/assets/1543510/16269568/13eacdda-3893-11e6-831d-69a790bc2b3b.JPG)

**Comment by SarfrazS** [comment]
Dear Csaeum,

We had implemented in body.In next release we have to  implement in subject Also.

**Comment by Gliba** [comment]
Subject previously worked for extended latin characters (čćšđž), now does not. Body still dont work. Tested with gmail. 
**Internally wen posting characters are working.**
![image](https://cloud.githubusercontent.com/assets/1550782/16318246/899d75c2-398e-11e6-9ae7-9fbc2cc5d26b.png)

**Comment by bhanu2217** [comment]
Which Faveo version are you using?

**Comment by Gliba** [comment]
1.0.7.7

**Comment by bhanu2217** [comment]
We are using UTF 8 encoding/decoding for emails, do let us know if you have any suggestions no how to make these characters work, what kind of decoding we should use

**Comment by Gliba** [comment]
Utf8 is fine. Probably something wrong with header decoding/encoding... I don't have time now to explore but i think u need to use mb_decode_mimeheader function for proper piping emails (subject and body). Application using Momo Email Listener? 
On Jun 24, 2016 15:38, Bhanu <notifications@github.com> wrote:We are using UTF 8 encoding/decoding for emails, do let us know if you have any suggestions no how to make these characters work, what kind of decoding we should use

**Comment by Gliba** [comment]
This is raw ermail mesage 
Testing =C4=8D =C4=87 =C5=A1 =C4=91 =C5=BE
and need to be decoded to
Testing č ć š đ ž

I think the problem is on line 244 (function decode_imap_text) in MailController.php
Maybe u can try to implement something like this [http://stackoverflow.com/questions/9350927/convert-inline-specified-utf-8-mail-subject](url)
Or [https://github.com/neitanod/forceutf8](url)

**Comment by sujit223** [comment]
Hi Gliba,

We are already using forceutf8 for saving the message body. But not in subject so far. But if in your body the text are not working we are unable to find the solution so far. 
Line number 209 https://github.com/ladybirdweb/faveo-helpdesk/blob/master/app/Http/Controllers/Agent/helpdesk/MailController.php

**Comment by Gliba** [comment]
This is the quick fix on line 209 
$body = Encoding::fixUTF8($body, Encoding::ICONV_TRANSLIT, ForceUTF8::ICONV_TRANSLIT);

For subject on line 143 utf8_decode mess up chars to ??? for me. I delete utf8_decode jus pass $mail->subject to subject var and it works

Subject for autorespon is still encoded, some help to find it?

**Comment by bhanu2217** [comment]
If we remove UTF8 than German characters stop working. 
Can we have some kind of encoding which will work for any language?

**Comment by Gliba** [comment]
German can use utf8mb4 db type. Not tested but shuld work without encoding.

**Comment by Gliba** [comment]
Encoding::fixUTF8($body, Encoding::ICONV_TRANSLIT) works for all characters, implement on subject for fixing character

**Comment by sujit223** [comment]
we will try it out
