### ISSUE TITLE
Unknown or bad timezone after login

### ISSUE THREAD

**Issue by Siva7891** [ladybirdweb/faveo-helpdesk#95]
After the installation is completed, when I tried to login using the admin account, I am getting a 500 error.

After debug is enabled on the app.php, I got the following error
[http://pastebin.com/kHW7s623](http://pastebin.com/kHW7s623)

OS: Ubuntu 14.04

Before installation even made the changes mentioned on this article: [http://www.ladybirdweb.com/support/show/500-error](http://www.ladybirdweb.com/support/show/500-error)

**Comment by bhanu2217** [comment]
We have posted new Ubuntu 14.04 installation instruction here http://ladybirdweb.com/support/show/how-to-install-faveo-helpdesk-on-ubuntu-1404-xenial-lts

See if everything is installed as per instructions here, we will also update a video for installation on this page soon

It looks like some PHP extension required is not enabled

**Comment by thanhpt** [comment]
Still got bot 500 error and this error.
Is Ngix is a must?

**Comment by bhanu2217** [comment]
You can use Apache also. Just Enable mod rewrite. Make debugging true and send the error message.

**Comment by thanhpt** [comment]
I tried to install many time. Install process completed without any error but still get 500 error, can not view dashboard and can not see the ticket that I created.

**Comment by bhanu2217** [comment]
Go to config/app.php and make debug as true and post the exact error message

**Comment by thanhpt** [comment]
[2016-06-30 02:34:41] production.ERROR: exception 'InvalidArgumentException' with message 'Unknown or bad timezone (-24)' in /var/www/faveo/vendor/nesbot/carbon/src/Carbon/Carbon.php:182

I got this error on screen :

Sorry, Something went wrong
Were working on it and we'll get it fixed as soon as we can.

**Comment by bhanu2217** [comment]
Please make this change
**In** App\Http\Middleware\CheckUpdate;  
**Replace** \Carbon\Carbon::now(-24); **With** \Carbon\Carbon::yesterday();

In next version we will fix this.

**Comment by thanhpt** [comment]
got it work! Thank you very much!

**Comment by mverma16** [comment]
Have you tried to install the latest version? Does the issue still persist in the latest version?

**Comment by Siva7891** [comment]
A few months back, I tried to install Faveo on Ubuntu for a client.

If you are confident, that the issue is fixed, feel free to close the issue.
