### ISSUE TITLE
Every morning database update on first login

### ISSUE THREAD

**Issue by csaeum** [ladybirdweb/faveo-helpdesk#97]
We are currently using the latest version 1.0.7.8.
Every day when first logging in Faveo I am prompted to update the database.
After a login is possible without problems until the next morning!

**Comment by sujit223** [comment]
Hi Chris,

Please add 1.0.7.8 to your database table **settings_system** over **version**.
We will fix this issue in the next release.

Thank you

**Comment by mathieu-aubin** [comment]
@csaeum if you need the proper sql command to run, just ask

**Comment by csaeum** [comment]
Here the Table settings_system

![unbenannt--](https://cloud.githubusercontent.com/assets/1543510/16444802/25b0f2f4-3de0-11e6-9914-32fd7cf8d97a.JPG)

Please the SQL Command ;)

**Comment by csaeum** [comment]
sorry false DB
