### ISSUE TITLE
Documentation on the API?

### ISSUE THREAD

**Issue by tttp** [ladybirdweb/faveo-helpdesk#99]
Hi,
My need is to integrate faveo with our CRM (civiCRM), so when a user has contacted us and we replied, add that ticket as an activity into the CRM for the contact.

is this something possible already? you mention API, but I didn't find a documentation about it, am I missing something?

**Comment by bhanu2217** [comment]
Can you please send us a email on support@ladybirdweb.com we will share the details there.

**Comment by tttp** [comment]
Not sure what happened, but FYI, I haven't received the documentation

**Comment by bhanu2217** [comment]
Please communicate via ticket raised.
